swiftlang/swift-docc-render

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Summary/LanguageSwitcher.vue
src/components/DocumentationTopic/Summary/LanguageSwitcherLink.vue
src/styles/core/colors/_dark.scss
src/styles/core/colors/_light.scss
src/utils/data.js
src/utils/json-patch.js
src/utils/json-pointer.js
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/Summary/LanguageSwitcher.spec.js
tests/unit/components/DocumentationTopic/Summary/LanguageSwitcherLink.spec.js
tests/unit/utils/json-patch.spec.js
tests/unit/utils/json-pointer.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 82968068
Adds renderer support for the newly introduced [`variantOverrides`][1] key in DocC Render JSON, which allows for using the same JSON file to represent documentation data for a symbol which is available in more than one variant—most commonly for a symbol available in both Swift and Objective-C languages.
For symbols available in both Swift/Objective-C, there will now be an affordance in the sidebar that can be used to toggle between the current language.
Example:
As described in https://github.com/apple/swift-docc/pull/11, the `variantOverrides` data may contain overrides for a given variant expressed as a [JSON Patch][2]—this patch can be applied to the Render JSON to obtain the language specific version of any data that may be rendered on the page. …

Add support for variant overrides

---

src/components/Tutorial/Assessments/Quiz.vue

Bug/issue #, if applicable: 82666933
Fixes a small CSS specificity issue, where styles from the docs are overwriting the ones from Tutorials/Quiz.vue, for the ButtonLink component.
NA
You can use the bundle attached:
[public.zip](https://github.com/apple/swift-docc-render/files/7453563/public.zip)
Steps:
1. run `VUE_APP_DEV_SERVER_PROXY=path/to/unzipped/bundle npm run serve`
2. go to http://localhost:8080/tutorials/slothcreator/creating-custom-sloths
3. Assert buttons are big
4. Click on the `Sloth` link in the header of the page
5. Go back
6. Assert the buttons are still big.

Fix quiz button width, when navigating from tutorial to docs and back

---

src/App.vue
tests/unit/App.spec.js

Bug/issue #, if applicable: 82736354
Stops the `<custom-header>` element from being rendered, if the `header` slot is used. This prevents the UI from rendering two header elements at once.
This may happen, when you have a theme that extends `swift-docc-render` with it's own header, and are previewing a doc bundle, that has a custom `header.html` file.
NA
Steps:
1. Create a Vue app that extends this branch of `swift-docc-render` as a theme.
2. Define a custom header that is rendered via the `header` slot of `docc-render/App.vue`
3. Run `npm run build` on your theme.
4. Using `swift-docc`, preview a bundle, that has a custom `header.html` file, while pointing to the just-built docc-render theme - `DOCC_HTML_DIR=/path/to/theme/dist docc preview`
4. Assert that the browser renders only your …

Prevent custom-header from rendering, if header slot is used

---

src/components/ReplayableVideoAsset.vue
tests/unit/components/ReplayableVideoAsset.spec.js

Bug/issue #, if applicable: 78842177
Since `HTMLMediaElement.play()` returns a `Promise` (in recent browsers)[1][1], the method calling it should ideally be an asynchronous function to avoid any potential race conditions.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play
Steps:
1. Checkout this branch and use `npm run build` to build this version of DocC-Render.
2. Configure `DOCC_HTML_DIR=/path/to/built/dist` and use DocC to compile a documentation catalog that has tutorials with video content in its sections.
3. Ensure that after section videos play, they can always be replayed using the "Replay" link.

Make `ReplayableVideoAsset.replay` asynchronous

---

src/components/DocumentationTopic/PrimaryContent/RestBody.vue
src/components/DocumentationTopic/PrimaryContent/RestParameters.vue

Bug/issue #, if applicable: 78800815
Ensures that the `required `and `deprecated` visual properties are always inline with the content of various REST components.
NA
Use the provided fixtures
[rest-parameters.json.zip](https://github.com/apple/swift-docc-render/files/7475154/rest-parameters.json.zip)
1. RestParameters - Ensure `required` is inline - http://localhost:8080/documentation/framework/rest-parameters
2. RestBody - Ensure `required` is inline - http://localhost:8080/documentation/framework/rest-parameters

Make "required" property inline with content, on all Rest type sections.

---

src/components/ContentNode/CodeListing.vue
src/components/ContentNode/CollapsibleCodeListing.vue
src/components/DocumentationTopic/ContentNode.vue

Bug/issue #, if applicable: 76070767
Adds a space to the scrollable code-listings, both on mobile and desktop. This fixes issues with code-listings flush to the right of the screen, when they are scrolled to the end.
NA
Use the added fixture - [public.zip](https://github.com/apple/swift-docc-render/files/7499081/public.zip)
Steps:
1. Go to `/tutorials/slothcreator/creating-custom-sloths` from the uploaded JSON
2. Make sure the code-listings have enough space on the right when they are scrollable horizontally. 
3. Go to `/documentation/framework/sloth`
4. Make sure all codelistings have enough space when scrolled.

Adds extra space to the right of scrollable code-listings

---

src/components/Tutorial/CodePreview.vue

Bug/issue #80957132, if applicable: 
White runtime preview's image should be differentiated from white code background in Tutorials when dark mode.
When modalBackgroundColor computed property returns white in dark mode, the shadow of preview images cannot be noticed. To fix it I applied a mix blend mode CSS property to make the preview image's shadow always contrasted with whatever code background color it has.
NA
[manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/7505297/manual-fixtures.zip)
Steps:
1. Run `VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve`
2. Go to http://localhost:8080/tutorials/slothcreator/creating-custom-sloths
3. Change to dark mode
3. Add the custom property `--background: white;` locally in the …

White runtime preview's image should be differentiated from white code background in Tutorials when dark mode

---

src/components/DocumentationTopic/PrimaryContent/DeclarationToken/TypeIdentifierLink.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken/TypeIdentifierLink.spec.js

Update URL in declaration to support external links
Bug/issue #, if applicable: rdar://82575979
In the Declaration Section of the documentation, we used to only be able to render internal, relative URLs and neglected the case where the Reference could be external. 
Before the fix, `swift-docc-render` would append the external URL as if it's a relative URL. 
With this PR, I updated the implementation in `/DeclarationToken/TypeIdentifierLink.vue` so this edge case is now supported. I updated the unit test with new expected behavior as well.
1. Download the fixture:
[fixture.zip](https://github.com/apple/swift-docc-render/files/7508547/fixture.zip)
2. Run `VUE_APP_DEV_SERVER_PROXY=/path/to/fixture/ npm run serve`
3. Open Safari and go to: http://localhost:8080/documentation/test
4. Check …

Update URL in declaration to support external links

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
src/components/Tutorial/NavigationBar.vue

Bug/issue #76457548, if applicable: 
Vertical align local nav for tutorials and documentation pages
| Before      | After |
| ----------- | ----------- |
| <img width="163" alt="b0850a80-4179-11ec-8523-5dc578f00073" src="https://user-images.githubusercontent.com/8567677/141131770-7eddb008-107d-498b-9133-773837a36bdb.png"> | <img width="163" alt="b975dc00-4179-11ec-9104-a8cebeea070a" src="https://user-images.githubusercontent.com/8567677/141131853-3e7f42cb-9d2b-4d93-beee-8fe7ab370b2f.png"> |
| Before      | After |
| ----------- | ----------- |
| <img width="153" alt="ffcb3b00-4179-11ec-841f-9418f72340a7" src="https://user-images.githubusercontent.com/8567677/141132185-0b4d0406-4cb3-4158-bc5e-29165bbe4cc0.png"> | <img width="153" alt="078adf80-417a-11ec-8b36-dcb186f89fe9" …

Vertical align local nav for tutorials and documentation pages

---

src/views/DocumentationTopic.vue
src/views/Topic.vue
src/views/TutorialsOverview.vue
tests/unit/views/DocumentationTopic.spec.js
tests/unit/views/Topic.spec.js
tests/unit/views/TutorialsOverview.spec.js

Bug/issue #, if applicable: 85271020
This fixes the following 2 issues with the logic for the new "variant overrides" support:
* Navigating to a _new_ page in Objective-C mode should still trigger a new request for data for the new page.
* Navigating to a _new_ page in Objective-C mode should apply a variant overrides patch (if available) after requesting its data.
These scenarios weren't accounted for because the majority of testing done previously was simply done by simulating toggling the language on the same page and didn't include example data for subsequent navigation.
Steps:
1. Download/unzip [archive.zip](https://github.com/apple/swift-docc-render/files/7524143/archive.zip) 
2. Configure `VUE_APP_DEV_SERVER_PROXY=/path/to/unzipped/archive` and run `npm run serve`
3. Load …

Fix bug preventing navigation to page after toggling language

---

src/utils/schema-version-check.js
tests/unit/utils/schema-version-check.spec.js

Bug/issue #, if applicable: N/A
Increments the minor value of the render node schema to 0.2.0 to account
for addition of the top-level `variantOverrides` property introduced in https://github.com/apple/swift-docc/pull/11.
This is related to https://github.com/apple/swift-docc/pull/43.
N/A
- ~[ ] Added tests~ N/A

Increment render node version for variantOverrides

---

package-lock.json
src/components/ContentNode.vue
src/components/ContentNode/Reference.vue
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Reference.spec.js

Bug/issue #, if applicable: 61211397
In the `TopicsSection`, we check if the `reference` has a human readable name before rendering. So, if a symbol reference has a human readable name, its title will be rendered in plain text instead of CodeVoice.
We did not consider this scenario anywhere else. This PR adds support to render symbols with human readable names in plain text. I added `ideTitle` and `titleStyle` to the props of the `Reference` component, so it can determine if a symbol has a human readable name and if it should be rendered as text or CodeVoice. 
[fixture.zip](https://github.com/apple/swift-docc-render/files/7621933/fixture.zip)
Steps:
1. Run VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve
2. Go to …

Add support to render `References` with human readable name in plain text

---

src/components/ContentNode.vue
tests/unit/components/ContentNode.spec.js

Bug/issue #, if applicable: rdar://73847907
While cmark-gfm saves the starting index of an ordered list, swift-markdown and Swift-DocC currently discards this information. This PR is part of a set that preserves the starting index when rendering documentation.
* https://github.com/apple/swift-markdown/pull/22
* https://github.com/apple/swift-docc/pull/53
Build this branch, then follow the testing instructions on https://github.com/apple/swift-docc/pull/53.
- [ n/a ] Updated documentation if necessary

use ordered list start index when rendering

---

app/index.html
app/main.js
bin/baseUrlPlaceholder.js
bin/transformIndex.js
package.json
src/components/ImageAsset.vue
src/components/Tutorial/Hero.vue
src/components/VideoAsset.vue
src/setup-utils/SwiftDocCRenderRouter.js
src/utils/assets.js
src/utils/data.js
src/utils/theme-settings.js
tests/unit/setup-utils/SwiftDocCRenderRouter.spec.js
tests/unit/utils/assets.spec.js
tests/unit/utils/data.spec.js
tests/unit/utils/theme-settings.spec.js
vue.config.js
webpack-asset-path.js

Bug #: 70509237
Allow for the baseURL configuration, to be configurable at build-time, as well as runtime. This allows for the app, to be served from static file hostings that do not support URL rewrites, like Github Pages. 
This PR utilizes already existing configurations from Vue CLI and Webpack.
1. All json based asset paths are now prefixed with a baseUrl, which defaults to root (`/`).
1. `process.env.BASE_URL` is a standard way to set the base url for Webpack and Vue CLI, so we use it to prefix our url.
1.  Adds a runtime configuration variable `var baseUrl`, allowing docc to inject a base url at runtime.
2. Generates a new `index-template.html` file, for usage inside docc
https://github.com/apple/swift-docc/pull/44
Steps:
1. Build the app as normal `npm run build`
2. Run …

Add static-hostable support, by allowing changing the baseUrl at runtime

---

src/components/NavBase.vue

Bug/issue #83836696, if applicable: 
Delete spacing between nav scrollbar and screen edge
NA
[manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/7513457/manual-fixtures.zip)
Steps:
1. Run `VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve`
2. Set scrollbars macOS conf to “Always”
3. Open Safari on desktop
4. Go to http://localhost:8080/tutorials/slothcreator/creating-custom-sloths
5. Go to responsive Design Mode and set a mobile resolution
6. Open the nav and assert that there is no space between the nav scrollbar and the screen edge

Delete spacing between nav scrollbar and screen edge

---

app/index.html
app/main.js
bin/baseUrlPlaceholder.js
bin/transformIndex.js
package.json
src/components/ImageAsset.vue
src/components/Tutorial/Hero.vue
src/components/VideoAsset.vue
src/setup-utils/SwiftDocCRenderRouter.js
src/utils/assets.js
src/utils/data.js
src/utils/theme-settings.js
tests/unit/setup-utils/SwiftDocCRenderRouter.spec.js
tests/unit/utils/assets.spec.js
tests/unit/utils/data.spec.js
tests/unit/utils/theme-settings.spec.js
vue.config.js
webpack-asset-path.js

* __Rationale:__ Adds support to allow a base URL to be configured after the app has already been built. In this way, the `docc` compiler can generate output that can be hosted at any base URL instead of just the root path at `/`.
* __Risk:__ Medium.
* __Risk Detail:__ There is added complexity to the build process to create a template that DocC can easily manipulate.
* __Reward:__ High
* __Reward Details:__ Allows DocC users to host their app at any given subpath of their website instead of just the root (this is needed for most GitHub Pages hosting scenarios).
* __Original PR:__ #24 
* __Issue:__ rdar://70509237
* __Code Reviewed By:__ @mportiz08 
* __Testing Details:__ Unit tests were added and updated. The expected `docc` compiler workflows utilizing this new feature were manually …

Allow the base URL for hosting to be configured post-build

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Summary/TechnologyList.vue
src/utils/strings.js
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/Summary/TechnologyList.spec.js
tests/unit/utils/strings.spec.js

* __Rationale:__ Changing the wording of the side bar from `Frameworks` to `Technologies` to improve the presentation of non-framework documentation. As a result of this change, we also updated the `pluralize` function to be more generic and ready for localized translation in the future. 
* __Risk:__ Low.
* __Risk Detail:__ There is mostly just a plain text change.
* __Reward:__ High
* __Reward Details:__ This supports the work landed in `Swift-Docc` and has been discussed on the Swift Forums [here]( and has been discussed on the Swift Forums [here](https://forums.swift.org/t/improve-presentation-of-non-framework-documentation-sr-15434/53388). ). 
* __Original PR:__ #28 
* __Issue:__ rdar://83451964
* __Code Reviewed By:__ @mportiz08 
* __Testing Details:__ Unit tests were added and …

Change `Frameworks` to `Technologies` to support documenting more product types

---

src/components/DocumentationTopic/PrimaryContent/PossibleValues.vue
tests/unit/components/DocumentationTopic/PrimaryContent/PossibleValues.spec.js

Bug/issue #48833910, if applicable: 
Avoid splitting characters in a way that leaves a single character by itself in Possible Values
NA
[manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/7712788/manual-fixtures.zip)
Steps:
1. Run `VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve`
2. Go to http://localhost:8080/documentation/framework/sloth
5. Go to responsive Design Mode and set a mobile resolution
6. Assert that long Possible Values are not being split by characters

Avoid splitting characters in a way that leaves a single character by itself in Possible Values

---

src/components/BreakpointEmitter.vue
src/constants/nav.js
src/utils/breakpoints.js
src/utils/router-utils.js
tests/unit/utils/router-utils.spec.js

Bug/issue #, if applicable: 78199719
This fixes an issue where the scroll position is off by 4 pixels when jumping to a part of the page using a fragment URL _only_ for devices/windows with small widths.
Since the base nav has a height of 48px instead of 52px only at the small breakpoint, this smaller value should be used as an offset when calculating the y scroll position value.
Here are example before/after screenshots showing the scroll position with main compared to this branch (notice how the background from the previous section bleeds over by a very small amount on main).
**main**
**this branch**
Steps:
1. Download/unzip [manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/7731114/manual-fixtures.zip)
2. Configure `VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures …

Adjust `scrollBehavior` for smaller nav at small breakpoint

---

src/components/DocumentationTopic/PrimaryContent/PossibleValues.vue

Bug/issue #, if applicable: 48833910
Fixes a very minor syntax issue with a recently added import statement to use the `docc-render` alias instead of `@`, which could cause issues for other applications using this project as a component library.
(This import statement was recently added with #34)
Steps:
1. Ensure all unit tests still pass and application still builds.

Fix minor import syntax issue

---

src/components/DropdownCustom.vue

Bug/issue #, if applicable:  86641543
In latest Safari Technology Preview if you click on the Tutorial pages navigation dropdowns, you get scrolled to the top.
This is a result of us focusing items inside the dropdown, and the page trying to scroll to those items.
NA
Steps:
1. Use any docc archive with a tutorial in it
2. Open the tutorial page and one of the two dropdowns in the Navigation bar
3. Assert that the page does not scroll to the top, upon opening the dropdowns.

Prevent scrolling the page, when using the custom dropdown component

---

src/components/Tutorial/Assessments.vue
src/components/Tutorial/Assessments/Quiz.vue
tests/unit/components/Tutorial/Assessments.spec.js
tests/unit/components/Tutorial/Assessments/Quiz.spec.js

Bug/issue #56352262, if applicable: 
When using VoiceOver at Check Your Understanding of a Tutorial, there is no clear feedback to let the reader know if a selected answer was right or wrong.
aria-live needs to be a single HTML element and every time that it gets its text updated with new information the screen reader will read its content out loud.
NA
[manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/7722113/manual-fixtures.zip)
Steps:
1. Run `VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve`
2. Go to http://localhost:8080/tutorials/slothcreator/creating-custom-sloths "Check Your Understanding" section
3. Open VoiceOver
4. Select an option and click the Submit button
5. Assert that every time you click the Submit …

VO should provide feedback after user answers a question in Tutorials' quiz

---

src/components/Article.vue
src/components/NavMenuItemBase.vue
src/components/Tutorial.vue
src/components/Tutorial/NavigationBar.vue
src/components/TutorialsOverview.vue
src/components/TutorialsOverview/Nav.vue
tests/unit/components/Tutorial/NavigationBar.spec.js
tests/unit/components/TutorialsOverview/Nav.spec.js

Bug/issue #, if applicable: 88095565
Fixes minor styling leftovers from prior refactors and allows for the tutorial navigations to be more extendable by external clients.
NA
Steps:
1. Mount using an archive with tutorials
2. Make sure the navigation looks identical on both TutorialOverview and TutorialTopic pages.

Add more extendability to tutorial navs

---

app/public/theme-settings.json
src/components/DocumentationTopic/PrimaryContent/DeclarationGroup.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
src/utils/indentation.js
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationGroup.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js
tests/unit/utils/indentation.spec.js

Bug/issue #, if applicable: 88594221
This implements a new formatting strategy for Swift declarations whereby each parameter of a multi-parameter symbol will be broken onto its own line and indented.
This should be an improvement over the way Swift declarations are currently rendered where they simply wrap at arbitrary points with some indentation. It should be easier for viewers of the documentation to visually and mentally scan/parse functions/initializers/etc for their parameters when symbols are presented in this manner.
**Example:**
Before:
After:
Steps:
1. Download/unzip [ExamplePackage.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8019198/ExamplePackage.doccarchive.zip) and configure `VUE_DEV_SERVER_PROXY=/path/to/ExamplePackage.doccarchive` (or use an alternate …

Improve swift declaration formatting

---

src/components/ImageAsset.vue
tests/unit/components/ImageAsset.spec.js

Bug/issue #, if applicable: 83366845
This updates the fallback image `alt` and `title` attributes so that the `alt` retains the unmodified alt text while the `title` now has a failure message indicating that the original image failed to load when the fallback image is hovered.
Example:
Refer to the ["improved testing instructions"](https://github.com/apple/swift-docc-render/pull/42#issuecomment-1021516452) from a previous PR. Now, the fallback image should have a tooltip on hover like the example image.

Present "Image failed to load" message in fallback image title tooltip

---

src/components/Navigator.vue
tests/unit/components/Navigator.spec.js

Bug/issue #89245661, if applicable: 
Sidenav not being displayed in the root page because of a type error
Regression introduced on https://github.com/apple/swift-docc-render/pull/51/commits/ba42e3940a8aeb08585e3eccdd57b3c387d2b624
NA
Example fixture folder:
[SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8111573/SlothCreator.doccarchive.zip)
Steps:
1. Use any data or docc documentation, example attached above
2. Run VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve
3. Go to any page, like http://localhost:8080/documentation/slothcreator/ if using example data
4. Open the theme-setting.json file and enable the "navigator" feature
4. Assert that you can see the sidenav properly
Make sure you check off the following items. If they cannot be …

Sidenav not being displayed in the root page because of a type error

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #64277424, if applicable: 
Add deprecated badge when item is deprecated on Sidenav
NA
Example fixture folder:
[SlothCreator-with-deprecated.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8127169/SlothCreator-with-deprecated.doccarchive.zip)
Steps:
1. Use the provided fixture folder
2. Run VUE_APP_DEV_SERVER_PROXY=/path/to/SlothCreator-with-deprecated.doccarchive/ npm run serve
3. Go to http://localhost:8080/documentation/slothcreator/
4. Open the theme-setting.json file and enable the "navigator" feature
5. Assert that you can see the deprecated badge on the "SlothGenerator" symbol

Add deprecated badge when item is deprecated on sidenav

---

src/components/Tutorial/Assessments/Quiz.vue

Bug/issue #87742486, if applicable: 
Prevents code listings inside questions to have border radius
NA
Example fixture folder:
[manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/8125486/manual-fixtures.zip)
Steps:
1. Use example attached above
2. Run VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve
3. Go to http://localhost:8080/tutorials/technologyx/tutorial and scroll to "Check Your Understanding"
4. Select first option with code listing
5. Click Submit
6. Assert that there is no border radius cutting the content

Prevents code listings inside questions to have border radius

---

src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 89580510
There may be a situation for a top level collection page where it does not have a reference to itself in the `references` map, so the minimal data for its URL needs to be created based on already existing page data.
Follow the testing instructions from https://github.com/apple/swift-docc-render/pull/51 and ensure that there are no regressions in the base sidebar functionality.

Update `DocumentationTopic.technology` to handle edge case

---

src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 89580510
This fixes a bug introduced in #60 where the logic to retrieve the URL path of the current page would only work for Swift frameworks. This change will allow it to work for any top level collection page.
Follow the testing instructions for #51 and ensure that there are no regressions in the base sidebar functionality.

Update `DocumentationTopic.technology` to retrieve current route path in improved way

---

src/components/AdjustableSidebarWidth.vue
src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/views/DocumentationTopic.vue
tests/unit/components/AdjustableSidebarWidth.spec.js
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js

Bug/issue #, if applicable: 86500277
Changes the sidebar breakpoints to use Medium as the point at which we go into a mobile view.
NA
Steps:
1. Point to a doccarchive with the index generated
2. View the page on desktop
3. Assert the sidebar is resizable and fully visible
4. Start resizing down to a tablet view, around 1000px it should follow the nav and move into a collapsed state.
5. Assert you can now toggle it open/closed
6. Keep it open and resize back into a larger screen.
7. Assert it automatically closes it without an animation

Change the sidenav breakpoints to use Medium instead

---

src/components/Filter/FilterInput.vue
src/components/Filter/Tag.vue
src/components/Filter/TagList.vue
src/mixins/handleScrollbar.js
src/mixins/multipleSelection.js
src/styles/core/_helpers.scss
src/styles/core/_vars.scss
src/utils/clipboard.js
src/utils/input-helper.js
tests/unit/components/Filter/FilterInput.spec.js
tests/unit/components/Filter/Tag.spec.js
tests/unit/components/Filter/TagList.spec.js
tests/unit/mixins/handleScrollbar.spec.js
tests/unit/utils/clipboard.spec.js
tests/unit/utils/input-helper.spec.js

Bug/issue #88010647 if applicable: 
Adding a filter input component with tag selection.
Some of the features it has are:
- Multiple tag selection implementing macOS keyboard shortcuts 
- Great AX
- Reversed Tags UI
- Tags truncation
NA

Filter input component with tag selection

---

src/components/DocumentationTopic.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 89691775
This fixes potential issues when there are no language `variants` in the RenderJSON for a technology.
NA
[SlothCreator 2.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8172001/SlothCreator.2.doccarchive.zip)
Steps:
1. Use the attached archive
2. Go to http://localhost:8080/documentation/slothcreator
3. Make sure it does not error out anymore

Remove duplicate languagePaths and fix issue with variants being undefined

---

src/components/AdjustableSidebarWidth.vue
src/components/DocumentationTopic.vue
src/components/Navigator.vue
src/views/DocumentationTopic.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

Bug/issue #, if applicable: 89638066
Cleans up all the borders on the navigator and the content around it, so they are shown only when needed.
It adds an extra border while expanding on mobile, that is later hidden.
Open transition on mobile is slightly improved as well.
NA
Steps:
1. Serve using a doccarchive with an index
2. Assert left/right borders are not visible below 1800px
3. Assert borders are applied beyond 1800px
4. Assert on mobile, no extra borders are applied
5. Assert the aside applies a border-right, only while being toggled open

Make sure borders on the navigator show only when needed and clean up animation.

---

src/components/AdjustableSidebarWidth.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

Bug/issue #, if applicable: 89070026
Fixes a small bug when trying to resize the sidebar on a zoomed in device
NA
Use a doccarchive with a sidebar index in it. - 
[SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8154866/SlothCreator.doccarchive.zip)
Steps:
1. Change the theme-settings.json to enable the sidenav
2. Go to `documentation/slothcreator`
3. Zoom in on your mobile device, iPad or using the Simulator
4. Start resizing the sidebar
5. Assert it works properly.

Fix sidebar resizing, when zoomed in on touch device

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator.spec.js

Bug/issue #, if applicable: 89376072
This fixes the sticky filter in the sidebar to not be choppy on Safari
NA
Steps:
1. Serve with a doccarchive with index
2. Scroll pages, open/close the items. Open on mobile. Everything should look OK without out of place components. 

Fix the sidebar filter sticky animation

---

src/components/Filter/FilterInput.vue
src/components/Navigator/NavigatorCard.vue
src/constants/TopicTypes.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 88001866
Allows filtering in the sidebar, using a pre-defined list of Tags
NA
Steps:
1. Serve a doccarchive that has articles or tutorials
2. Click on the filter and select Tutorial or Article tag
3. Assert only those are shown + their parents are open

Add sidenav tag filtering

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/NavBase.spec.js

Bug/issue #, if applicable: 89774411
Closes the nav, if it was open and trying to open the sidenav. This fixes a bug where the sidenav is not scrollable, when the nav is toggled open.
NA
Steps:
1. On a mobile device, toggle the nav open
2. While open, click on the sidebar toggle
3. Assert you can scroll the sidenav. Open a few items if there are not enough items for a scrollbar.

Close the nav, before toggling the sidenav open

---

src/components/DocumentationTopic.vue

Bug/issue #, if applicable: 89837079
This fixes a regression with the page layout that was introduced in #51.
In certain edge cases for IDE targets, top level elements of documentation pages like the "Relationships" section may occasionally break out horizontally into a second column, which should never happen.
This seems to only happen in WebKit based browsers.
Steps:
1. Configure `VUE_APP_TARGET=ide` when running the dev server with `npm run serve`.
2. Using Safari, find examples of problematic pages and verify that they now look normal as the window is resized from large to small.
3. View other pages and ensure that there are no new regressions with the layout.

Fix regression with page layout where it can wrap horizontally in certain scenarios

---

src/components/Filter/FilterInput.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/Filter/FilterInput.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 89502803
Adds a toggle to the FilterInput (tagging component), to allow it to lose it's focus when moving focus from it to an Input or a button. Should make re-use of the component easier in forms.
NA
Steps:
1. While focused on the input, click on a button or other input on the same page
2. Assert that the input is no longer focused/blue/open

Allow the FilterInput to loose focus when the blur target is an action item

---

src/components/AdjustableSidebarWidth.vue
src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/views/DocumentationTopic.vue
tests/unit/components/AdjustableSidebarWidth.spec.js
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 89956881
Fixes an issue with the sidebar filter going on top of the header, on mobile sizes.
Before
After
NA
Steps:
1. Go to any page with a navigator
2. Resize the screen to a mobile size and open the navigator
3. Inspect the filter at the top

Fix sidebar filter position on mobile

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/Navigator/NavigatorCard.vue

Bug/issue #, if applicable: 89903890
Changes clickable area of the sidenav toggles, so its easier to click on mobile devices.
NA
Steps:
1. Serve a doccarchive with sidebar index
2. Assert that the toggles to open/close the nav on mobile devices are larger and easier to click, while the icons are in the same place and size.

Make the sidenav toggle easier to click on mobile

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #89153793, if applicable: 
It adds aria-live regions to NavigationCard so when a VoiceOver user filters the sidenav, they instantly get notified on:
- What content has changed on Sidenav
- If there is no children
- It there is no results
- If there has been an error fetching
NA
Make sure you download and unzip the .doccarchive - [SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8082216/SlothCreator.doccarchive.1.zip)
Steps:
1. run VUE_APP_DEV_SERVER_PROXY=/path/to/SlothCreator.doccarchive npm run serve
2. Enable navigator on theme-settings.json file
3. Visit http://localhost:8080/documentation/slothcreator
4. Open VoiceOver
5. Use the filter input and assert that live region updates you with the correct information described in the summary depending …

[AX] Add aria-live regions to NavigationCard

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 89588542
Fixes the filtering logic of the navigator, stop showing children of a parent, that is a direct match of your current query. It fixes the logic for tags and title filtering. It was already fixed for API changes.
NA
Steps:
1. Type a filter that matches a parent item directly.
2. Assert none of it's children, that dont match the same query are shown.
3. This works the same for Tags. If you pick a tag, it should only show children with the same tag. (Their parents dont count, as they have to be rendered in order to show the children).

Fix navigator tag filtering logic - stop showing none-matching children

---

src/components/NavBase.vue

Bug/issue #, if applicable: 90172898
Fixes the nav spacing on Medium.
NA
Steps:
1. Assert the spacing on the Nav on Medium is 22px

Fix navigation gutter spacing on Medium

---

src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #, if applicable: 89718125
Allows navigating to items in the navigator, that have the same path as the currently open item.
NA
You need a doccarchive that has duplication in the children, inside the tree. You can use the attached one.
[SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8244846/SlothCreator.doccarchive.zip)
Steps:
1. Serve the app using the above doccarchive
2. Navigate to `Sloth > Sloth Generator > func generateSloth`
3. Assert item is highlighted, and its parents
4. Navigate to `Sloth Generator > func generateSloth`
5. Assert item is highlighted and its parents. The previous item is not collapsed. 
6. Navigate back/forward and assert they are properly highlighted
7. Refresh the page
8. Assert highlighting continues
9. Assert that …

Fix duplicate path navigation

---

src/components/Filter/FilterInput.vue
tests/unit/components/Filter/FilterInput.spec.js

Bug/issue #, if applicable: 90383936
This fixes the logic to truncate the suggestedTags inside the FilterInput.
NA
Steps:
1. Make sure the FilterInput should never show more than 5 items, when ShouldTruncateTags is true.

Properly limit the tags on the FilterInput

---

src/components/Navigator/NavigatorCard.vue
src/utils/loading.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 90321277
Refactors the focus handling on the RecycleScroller, in instances where it updates the elements, from open/close events or from scrolling the virtual scroller.
NA
Serve the app with a doccarchive that has the navigator data
Steps:
1. Using only the keyboard, start navigating with Tabbing across the items.
2. Once you focus one of the last items at the end of the screen, it will jump to the next one, moving it to the center of the scrollable area
3. Assert that focus is still kept on the item. (we used to loose focus on that element here)
4. Assert that after focusing, initiating a filter (by tag or text) resets the focus order. (try to focus back into the items)
5. Assert that clicking on items and navigating to their page, focus is still kept on it. …

Improve focus handling from scroller re-rendering all items and losing focus

---

src/components/Filter/FilterInput.vue
src/components/Navigator/NavigatorCard.vue
src/mixins/multipleSelection.js
tests/unit/components/Filter/FilterInput.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 89796778
Allows disabling the `clear on tag selection` feature in the FilterInput. This should allow the Navigator filter to apply tags, without clearing your query.
NA
Steps:
1. Go to a page with a navigator
2. Apply a title filter
3. Pick a Tag
4. Assert the filter is not removed

Allow disabling the filter clear on FilterInput tag selection

---

package-lock.json
package.json

Bug/issue #, if applicable: 90502137
This PR bumps the vue-cli packages to `4.5.17` which removes the dependency on `node-ipc` which can be considered vulnerable from `v9.2.2` forward.
We were depending on `9.2.1`.
NA
NA

Bump the vue-cli packages versions, so we dont accidentally install malware packages

---

src/components/AdjustableSidebarWidth.vue
src/components/NavBase.vue
src/styles/core/_nav.scss
tests/unit/components/AdjustableSidebarWidth.spec.js

Bug/issue #, if applicable: 89903794
This fix prevents the navigator mobile overlay from overlaying potential third party content, above the nav.
NA
Steps:
1. Open/close the navigator on mobile screen size
2. Assert it's not cutoff at the top/bottom, nothing from the background is shining through.
3. Try to add a custom element in the `header` slot in App.vue and assert the overlay does not step over it.

Make sure the navigator mobile overlay does not hide potential custom top navigators

---

src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 90717877
Fixes an issue, where the navigator cannot highlight the current page.
This was because I was passing the last, more detailed set of paths from the `hierarchy`, but that may not always point to the same technology as we are on now.
This means that if a page is linked to from many places in your docs, upon first visit of the page, we will try to match it with the shortest path, which matches the nav breadcrumbs.
NA
[SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8339480/SlothCreator.doccarchive.zip)
Steps:
1. Mount with the provided archive
2. Go to http://localhost:8080/documentation/slothcreator/namegenerator/generatename(seed:)
3. Assert the page is properly highlighted in the navigator, using the same path as the …

Make sure navigator properly highlights the current page

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 90558554
Fixes an issue with the sidebar navigator, where it shows no children, even if there are. 
This can happen if you go to another technology, search and then go back.
NA
Steps:
1. Go to any page on a technology
2. In the navigator, click on a link that points to another technology
3. Search for something
4. Go back using the browser Back
5. Assert it does not apply the filter, (its cleared from SessionStorage as well), and it properly renders the children.

Fix persisted state when navigating across technologies, while filter is applied

---

src/components/Navigator/NavigatorCard.vue

Bug/issue #, if applicable: 90601855
Fixes a small spacing issue with the cutoff from the filter height.
NA
Steps:
1. Serve the app and go to a page with a navigator
2. Assert that when scrolling to the bottom of the navigator (you need a few expanded children), all items are fully visible.

Fix the assumed filter height for the NavigatorCard

---

src/components/AdjustableSidebarWidth.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

Bug/issue #, if applicable: 89828514
Removes a class helper, that adds extra width to the resize handler of the sidebar. This is so it can be gripped when at the far left/right. This is no longer needed, as we have hard limits on the sidebar to never go 100% open/closed.
NA
Steps:
1. Expand the sidebar as much as it will go
2. Hover over the resize handler
3. Assert it's width is 5px and not more

Fix - Vertical divider line gets 10px stroke in thickness

---

src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #, if applicable: 89797030
When cmd + click-ing on a dropdown in the navigator, it should open it and all of its siblings.
NA
Steps:
1. Cmd + click on an item
2. Assert all of its siblings are open. 
3. Assert that previously open items stay open and dont get extra items appended.
4. Assert item order and hierarchy is not broken
5. Cmd + click to close
6. Assert all are closed and can then be individually opened.
7. Assert that root level items also open.
8. Assert that deeply open children of siblings are closed when cmd+click-ing on an item.

Allow toggling all siblings when cmd + click-ing on a tree item.

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 90843143
Fixes errors when changing the page language.
Errors were caused by the `children` changing, but the `activeUID` that is stored was updated after the fact, when the RenderJSON gets updated, so we had a stale activeUID.
The fix is a simple guard, as the component handles the rest gradually.
NA
You need an archive that has a language variants and the `index`.
Steps:
1. Change the language
2. Assert it does not throw errors in the console.
3. Assert that navigating back and forth does not break anything.

Make sure that changing the language does not break the activePath tracking

---

src/components/Tutorial/NavigationBar.vue

Bug/issue #, if applicable: 90843609
This PR fixes the titles on Tutorial pages navigation bar from being truncated on small viewport sizes.
This is a regression from introducing the pre-title slot for the sidenav toggle.
NA
Steps:
1. Go to a tutorial
2. Resize screen to a mobile viewport
3. Assert it does not truncate the title anymore

Fix tutorial title truncation in nav

---

src/components/Navigator/NavigatorCard.vue

Bug/issue #, if applicable: 90845942
Changes the no-children text, when the navigator could not match and find any children.
NA
Use the provided archive [TinyMixedLanguageLibrary.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8379204/TinyMixedLanguageLibrary.doccarchive.zip)
Steps:
1. Visit `/documentation/tinymixedlanguagelibrary`
2. Assert the no children text is updated

Change the no-data text on the navigator

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #, if applicable: 89840827
This PR prevents the arrows from animating open/closed, when scrolling long lists too fast.
NA
Steps:
1. Open a few levels in a tree in different hierarchies.
2. Start scrolling fast up/down
3. Assert it does not animate the arrows upon rendering on the screen.

Prevent arrows from animating, when scrolling too fast

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 90845143
Fixes an issue where scrolling fast in the navigator, shows empty spaces.
NA
Steps:
1. Open a few large trees
2. Assert that scrolling fast shows little to now empty spaces. (It is still possible to see these if you are very fast with the scroll :D )

Fix issue where fast scrolling shows empty spaces

---

app/public/theme-settings.json
src/components/Navigator/NavigatorCard.vue
src/utils/arrays.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/utils/arrays.spec.js

Bug/issue #, if applicable: 90840717
This fix prevents keeping tutorials highlighted, when clicking on them in the Navigator, then going back.
This was caused because we kept an activeUID for that item upon clicking, but it navigates you to a different page type altogether. 
The fix is a more generic one, to clear the cached state, if the activeUID path is NOT the same as the current route path.
**Alternative**
An alt fix could be to not emit a click event for Tutorial types, but that is a slippery slope I think.
NA
Steps:
1. Open an archive with a tutorial
2. Click on a none-tutorial item
3. Then click on a tutorial
4. Assert you get navigated to the tutorial
5. Go back with browser Back
6. Assert the tutorial is no longer highlighted, but the current page is.
Make sure you check off the …

Fix to not highlight Tutorials, when navigating to them from the navigator links, then going back.

---

src/components/Navigator/NavigatorCard.vue
src/components/Tutorial/NavigationBar/MobileDropdown.vue
src/styles/core/_nav.scss

Bug/issue #, if applicable: 90950058
Adds extra bottom spacing to the bottom of mobile navigator. Fixes the issues where iOS Safari hides the bottom most items, even upon scrolling.
NA
Steps:
1. Navigate go any page with a navigator, using iPhone or the simulator
2. Open the navigator and open a few items
3. Scroll down
4. Assert if bottom nav does not show, it does not hide any of the last items.

Add extra bottom spacing to the bottom of mobile navigator. Fixes ios nav hiding items

---

src/components/NavMenuItemBase.vue

Bug/issue #, if applicable: 90970180
This PR fixes cases, where a nav has more than 8 child items on mobile, and siblings never get shown, because of an assumption we make on the CSS part.
The fix ensures any child will be visible, and the complex loops are only used to change the transition-delay, to generate the stagger effect.
**Alternative Fix**
An alternative I tried and got working was to use CSS Custom properties instead. We can add `--index` to the items and do all the math necessary using `calc` expressions. The downside of this is that we need to add `--index` to every item/place where we want staggered items. This would be the `Hierarchy`, `MobileDropdown` and maybe 1 or 2 more places in TutorialOverview. This is a much bigger change, so I am leaving it here just for a …

Show child nav items, when more than 8 siblings

---

src/components/AdjustableSidebarWidth.vue

Bug/issue #, if applicable:  89903794
Adds a top border to the navigator, in cases where there might be an extra nav or header above it and we offset for it.
NA
Steps:
1. Open the navigator on mobile
2. Assert by default these is no border
To test out the border, just add something to the `header` slot in the `App.vue` file, to simulate a custom header.

Adds top-border to navigator, if it has a top-offset

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 90289411
It will now simply read:
> Filter
instead of
> Filter in [technology]
Steps:
1. Enable the navigator feature flag and preview some documentation.
2. Verify that the placeholder text for the navigator filter now says "Filter" instead of "Filter in [technology]"

Simplify navigator filter placeholder text

---

src/components/Navigator/NavigatorCardItem.vue

Bug/issue #, if applicable: 91070240
Changes the horizontal spacing on the navigator items from 10 to 20px, to match the root technology header
NA
Steps:
1. Open enough child items, so they start getting truncated
2. Assert the right padding is 20px, while the rest are untouched.

Fix Navigator item right horizontal spacing

---

src/components/Navigator/NavigatorCard.vue

Bug/issue #89368692, if applicable: 
When a query doesn't match results in the sidebar, the feedback text should be:
“No results found. Try changing or removing text and tags.”
NA
Steps:
1. Run any documentation with sidenav
2. Type a random query that has no matches on the navbar's filter input
3. Assert that feedback text is correct

When a query doesn't match results in the sidebar, the feedback text should be different

---

src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue
tests/unit/components/DocumentationTopic/DocumentationNav/LanguageToggle.spec.js

Bug #: 90289062
Fixes an issue with zooming in/out and the language toggle getting cutoff.
NA
Steps:
1. Zoom in with `cmd +` until you see the mobile localnav
2. Zoom out with `cmd -` or do `cmd 0` to zoom 100% out.
3. Assert the toggle is no longer cutoff

Fix language toggle overflowing, when zooming in on iOS

---

src/components/Navigator/NavigatorCardItem.vue

Bug/issue #, if applicable: 
Limit VoiceOver cursor
| Before      | After |
| ----------- | ----------- |
| ![before](https://user-images.githubusercontent.com/8567677/161607312-3768284a-a476-4070-bf97-1f0c33d213cc.gif) | ![after](https://user-images.githubusercontent.com/8567677/161607327-d799300e-a11d-41fa-8aeb-983e4a37114b.gif) |
NA
Steps:
1. Open a documentation with sidenav and enable sidenav on it
2. Turn on VoiceOver
3. Use arrow key to navigate to the items in the sidenav
4. Assert that VoiceOver cursor is the same as the item's outline

Limit VoiceOver cursor

---

src/components/DocumentationTopic/DocumentationHero.vue

Bug/issue #, if applicable: 90999537
Fixes an issue where the sample code button text color is accidentally being overwritten to blue instead of white, which makes it look disabled.
Steps:
1. Open an example sample code page with the download button
2. Verify that the download button text is white again instead of blue

Don't override button link color in doc hero

---

src/components/Navigator/NavigatorCardItem.vue

Bug/issue #90845397, if applicable: 
Limit VoiceOver cursor
| Before      | After |
| ----------- | ----------- |
| ![before](https://user-images.githubusercontent.com/8567677/161607312-3768284a-a476-4070-bf97-1f0c33d213cc.gif) | ![after](https://user-images.githubusercontent.com/8567677/161607327-d799300e-a11d-41fa-8aeb-983e4a37114b.gif) |
PR cherrypicking: https://github.com/apple/swift-docc-render/pull/118
It affects AX on Sidenav
Low
NA
Steps:
1. Open a documentation with sidenav and enable sidenav on it
2. Turn on VoiceOver
3. Use arrow key to navigate to the items in the sidenav
4. Assert that VoiceOver cursor is the same as the item's outline

[5.7] Limit VoiceOver cursor

---

app/public/theme-settings.json
src/utils/schema-version-check.js
src/views/DocumentationTopic.vue
tests/unit/utils/schema-version-check.spec.js
tests/unit/views/DocumentationTopic.spec.js

- Rationale: Removes the global feature flag and dynamically enables the navigator for compatible Render JSON versions.
- Risk: Medium
- Risk Detail: Impacts all documentation pages, updates logic to show/hide major UX feature.
- Reward: High
- Reward Details: Enables the navigator by default for compatible DocC output.
- Original PR: https://github.com/apple/swift-docc-render/pull/78
- Issue: rdar://89089597
- Code Reviewed By: @mportiz08 
- Testing Details: Updated unit tests, tested that the sidebar is enabled as expected for pages compiled with the appropriate DocC version, tested that the sidebar is not enabled as expected for pages with older DocC output.
\cc @dobromir-hristov

[5.7] Enable the sidebar only for schema versions above certain value

---

src/components/Navigator/NavigatorCard.vue
src/utils/arrays.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/utils/arrays.spec.js

- **Rationale:** Fix issues with losing state when navigating or opening/closing items while filtering
- **Risk Detail:** The PR refactors the way we track which items are being rendered, upon opening/closing
- **Reward Details:** Fixes all issues related to filtering, and opening/closing branches.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/117
- **Issue:** rdar://90843762
- **Code Reviewed By:** @mportiz08 @marinaaisa 
- **Testing Details:** Updated unit tests, manually tested all possible interactions, like toggle, toggle siblings, toggle all children.

[5.7] Fix issues with losing state when navigating or opening/closing items while filtering

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- **Rationale:** Navigator labels should not be clickable
- **Risk Detail:** We just added a check to the type of item, before emitting an event on click.
- **Reward Details:** Fixes an issue with the Navigator, where a user might click on a label and highlight it, nothing breaks.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/119
- **Issue:** rdar://90633560
- **Testing Details:** Tested with Unit tests and by manually clicking on navigator items

[5.7] Navigator labels should not be clickable

---

src/components/Navigator/NavigatorCard.vue

- **Rationale:** Updates the styling for the navigator toggle on Medium screen sizes
- **Risk Detail:** Only a few small CSS additions scoped to new navigator components.
- **Reward Details:** Fixes an issue where the Navigator Toggle looks badly positioned and is hard to click.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/121
- **Issue:** rdar://90968150
- **Testing Details:** Visually inspected in browser on Medium sizes mobile devices

[5.7] Fix navigator mobile toggle spacing (#121)

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** We should only suggest tags that can yield results
- **Risk Detail:** The change is only scoped to the Navigator filters, but it does need to iterate over all items of a technology.
- **Reward Details:** Users will not see tags, that would not yield any results
- **Original PR:** https://github.com/apple/swift-docc-render/pull/122
- **Issue:** rdar://89482723
- **Testing Details:** Added Unit Tests + manually tested in the browser

[5.7] Suggest only tags in the Navigator, that can return results

---

src/mixins/keyboardNavigation.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/mixins/keyboardNavigation.spec.js

- **Rationale:** Fixes the keyboard related actions for the tagging component in the Navigator
- **Risk Detail:** Changes some of the internals, but the change is scoped only to the tagging input.
- **Reward Details:** Fixes an issue where the filter tags cannot be navigated to with the keyboard
- **Original PR:** https://github.com/apple/swift-docc-render/pull/120
- **Issue:** rdar://90973785
- **Testing Details:** Added Unit tests and verified manually in the browser

Fix selecting tags with the keyboard on Navigator (#120)

---

src/components/AdjustableSidebarWidth.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

Bug/issue #, if applicable: 91400301
Makes sure the items in the navigator can always be scrolled to. This fixes cases, where there can be another header above the default nav.
NA
Steps:
1. Either build using Docc and a custom header template OR just add some content to the `header` slot in `App.vue`.
2. Assert when scrolled to the top of the page, if you expand enough items in the navigator, you can scroll all of them into view.

Make sure items are always scrollable in the navigator

---

src/components/AdjustableSidebarWidth.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

- **Rationale:** Adds extra padding on the bottom of the navigator, so extra navs dont obscure the last items in the list
- **Risk Detail:** Only a few small CSS additions scoped to new navigator components.
- **Reward Details:** Fixes an issue where UI elements may be obstructed by extra header items in custom tempaltes
- **Original PR:** https://github.com/apple/swift-docc-render/pull/139
- **Issue:** rdar://91400301
- **Code Reviewed By:** @marinaaisa
- **Testing Details:** Visually inspected on themes with custom header.

[5.7] Make sure items are always scrollable in the navigator 

---

src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardItem.vue
src/styles/core/_helpers.scss

- **Rationale:** Updates the navigator styles to respect device safe area insets.
- **Risk Detail:** Only a few small CSS additions scoped to new navigator components.
- **Reward Details:** Fixes an issue where UI text may be obstructed by safe area insets in certain devices.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/129
- **Issue:** rdar://89775264
- **Code Reviewed By:** @marinaaisa, @dobromir-hristov
- **Testing Details:** Visually inspected in simulator with problematic devices and checked to ensure no regressions were introduced with spacing on other devices.

[5.7] Update navigator spacing to better respect safe area insets

---

src/components/Filter/FilterInput.vue

Bug/issue #, if applicable: 91100473
This fixes a bug where if you fill in a FilterInput and follow a link to another website then go back, Safari will not respect the pre-filled input, and will show it as empty, until you click into it.
NA

Fix bug with Safari not pre-filling tagging input when going back

---

src/components/Icons/SingleLetterSymbolIcon.vue
src/components/Icons/TwoLetterSymbolIcon.vue

- **Rationale:** Minor spacing refactor on the single letter icon SVGs
- **Risk Detail:** Changes are only in that icon's SVG
- **Reward Details:** Fixes some minor visual issues, where the letters were not centered in the icon
- **Original PR:** https://github.com/apple/swift-docc-render/pull/127
- **Issue:** rdar://89653708
- **Code Reviewed By:** @marinaaisa @SamLanier 
- **Testing Details:** Visually inspected

[5.7] Fix single letter icon spacing

---

src/components/Filter/FilterInput.vue

- **Rationale:** Removes an attribute, that is causing a Safari bug when going back from another website to docc-render
- **Risk Detail:** The change removes a helper attribute
- **Reward Details:** Fixes an issue where tagging input would not get pre-filled in Safari, when going to another website , then back.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/140
- **Issue:** rdar://91100473
- **Code Reviewed By:** @marinaaisa
- **Testing Details:** Manually tested in Safari

[5.7] Fix bug with Safari not pre-filling tagging input when going back (#140)

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

Bug/issue #, if applicable: 89151255
Adds an optional above-hero-content slot so third parties can render content outside the hero content container and padding.
NA
Steps:
1. Assert the styling of the hero is untouched by the changes

Expose an above-hero-content slot

---

src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- Rationale: Updates the hero icon placement to align with the new design. 
- Risk: Low
- Risk Detail: Only a few small CSS additions scoped to hero component.
- Reward: High
- Reward Details: Better visual in the hero section to align with the content style change and the navigator.
- Original PR: https://github.com/apple/swift-docc-render/pull/131
- Issue: rdar://89970511
- Testing Details: Visually inspected in simulator. Icons should not be visible in small viewport and should be pinned to the right on all other viewports.

[5.7] Update Hero Icon Placement - pin to the right (#131)

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- **Rationale:** Adds an extra slot above the documentation topic hero, for third party toolings to insert UI elements.
- **Risk Detail:** The change just adds a slot, no visual changes for default theme.
- **Reward Details:** Adds extra flexibility to third party tooling
- **Original PR:** https://github.com/apple/swift-docc-render/pull/132
- **Issue:** rdar://89151255
- **Code Reviewed By:** @marinaaisa
- **Testing Details:** Manually tested in the browser and added unit tests

Expose an above-hero-content slot in DocumentationTopic.vue (#132)

---

src/components/DocumentationTopic/PrimaryContent/PossiblyChangedTextAttribute.vue
src/components/DocumentationTopic/PrimaryContent/PropertyTable.vue
src/components/DocumentationTopic/PrimaryContent/RestBody.vue
src/components/DocumentationTopic/PrimaryContent/RestParameters.vue
tests/unit/components/DocumentationTopic/PrimaryContent/PossiblyChangedTextAttribute.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/PropertyTable.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestBody.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestParameters.spec.js

Bug/issue #, if applicable: 89264865
This adds support for rendering the "(Read only)" text alongside abstracts of REST API object properties when it is relevant.
https://github.com/apple/swift-docc/pull/134
Steps:
1. Find an example REST API page that has a readonly object property
2. Verify that the abstract for that property is prefixed with the text "(Read only)" in the same visual style that is done for required properties.

Indicate readonly properties when possible for REST APIs

---

src/components/Navigator.vue
tests/unit/components/Navigator.spec.js

Bug/issue #, if applicable: 91443710
This PR fixes a bug Ethan found on [Argument Parser docs](https://ethan-kusters.github.io/swift-argument-parser/documentation/argumentparser/argumenthelp/shoulddisplay/), where docc-render would not highlight the current page in the navigator. 
This turns out to be caused by the trailing slash in the URL, which was causing the current page matching to fail.
NA
Steps:
1. Using any docc-archive, visit a page and just add a trailing slash at the end of the URL
2. Make sure you clear any SessionStorage cache
3. Assert the current page gets highlighted

Highlight current item in Navigator, when there is a trailing slash in the URL

---

src/components/DocumentationTopic/PrimaryContent/PossiblyChangedTextAttribute.vue
src/components/DocumentationTopic/PrimaryContent/PropertyTable.vue
src/components/DocumentationTopic/PrimaryContent/RestBody.vue
src/components/DocumentationTopic/PrimaryContent/RestParameters.vue
tests/unit/components/DocumentationTopic/PrimaryContent/PossiblyChangedTextAttribute.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/PropertyTable.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestBody.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestParameters.spec.js

- **Rationale:** Adds support for rendering "(Readonly)" text when relevant for REST API properties.
- **Risk Detail:** Narrow focus on less common UI element, only adds some minor text output.
- **Reward Details:** Adds important clarifying detail to specific API properties.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/142
- **Issue:** rdar://89264865
- **Testing Details:** Updated unit tests, verified that the new "(Readonly)" text looks correct visually.

[5.7] Indicate readonly properties when possible for REST APIs

---

src/components/Navigator.vue

- Rationale: Remove an extra border from navigator, that we dont need.
- Risk: Low
- Risk Detail: Its removing a line of css, that was left out from previous refactors.
- Reward: Medium
- Reward Details: Fixes a small visual problem.
- Original PR: https://github.com/apple/swift-docc-render/pull/154
- Issue: rdar://89638066
- Code Reviewed By: @marinaaisa 
- Testing Details: Visually inspected on all supported viewports.

[5.7] Remove extra borders from Navigator (#154)

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #91493171, if applicable: 
Sidenav toggle button should have aria-label description
NA
Steps:
1. Run a .doccarchive with sidenav
2. Go into mobile view
3. Assert that sidenav toggle button has aria label of the action that it does

Sidenav toggle button should have aria-label description

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Rationale: Update aria-labels for documentation navigator
Risk: Low
Risk Detail: Only aria-labels changes.
Reward: High for VoiceOver users
Reward Details: Better VoiceOver descriptions
Original PR: https://github.com/apple/swift-docc-render/pull/161
Issue: rdar://91493171
Code Reviewed By: @dobromir-hristov @[hqhhuang](https://github.com/hqhhuang)
Testing Details: Using VoiceOver

[5.7] Sidenav toggle button should have aria-label description

---

src/stores/ApiChangesStoreBase.js
tests/unit/stores/ApiChangesStoreBase.spec.js

- **Rationale:** the `selectedAPIChangesVersion` should only be changed from a toggle
- **Risk Detail:** The change is only scoped to a store, that is not yet utilised in docc-render.
- **Reward Details:** Users will not get `selectedAPIChangesVersion` reset via page navigation.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/166
- **Issue:** rdar://91334846
- **Testing Details:** Added Unit Tests

[5.7] Stop resetting the selectedAPIChangesVersion, on each page navigation

---

src/components/Navigator.vue
src/components/Navigator/NavigatorDataProvider.vue

- **Rationale:** Improves the Navigator rendering performance
- **Risk Detail:** The change only implements more performant loops and removes reactivity where not needed.
- **Reward Details:** Users should see a much improved loading speed on large indexes. 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/157
- **Issue:** rdar://91610791
- **Testing Details:** Manually tested in the browser using performance profiling

[5.7] Improve the children flattening performance in the Navigator

---

src/components/Navigator/NavigatorCard.vue

Bug/issue #, if applicable: 89775264
For some reason, there is a CSS `left` property assignment that is inconsistently being evaluated as expected on devices with left inset values.
I've simply updated this to be a `padding` rule, which seems to resolve this issue and the spacing works consistently now.
Steps:
1. Open a page with the sidebar on a device that has a left inset when in landscape orientation (like the iPhone 13 Pro as an example).
2. Open the mobile sidebar and verify that the close icon is not obscured by the device.

Convert `left` rule to `padding` rule to fix inset issue

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 91824384
Fixes an issue, where if you visit a url that has a capital case letter, it would not find a match if the current page you are on.
It also fixes a small issue with stale activeUID in cache, where it may be null, but we could have actual items to match against.
NA
Steps:
1. Serve any archive
2. Go to a page the archive supports, but change some letters in the URL to capitalcase.

Cast to lower case the current path in the navigator, to ensure matching paths with capital letters.

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** Navigator should only show tags, that can yield results.
- **Risk Detail:** The change only touches the navigator tag filtering logic.
- **Reward Details:** Users will not get an empty navigator, if they select a tag in certain situations
- **Original PR:** https://github.com/apple/swift-docc-render/pull/172
- **Issue:** rdar://89482723
- **Code Reviewed By:** @mportiz08 @hqhhuang 
- **Testing Details:** Manually tested in the browser and in unit tests

[5.7] Make sure we show only tags, that match the currently filtered items in navigator

---

src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- **Rationale:** Allows users to user the keyboard left/right arrows to expand/contract the navigator items.
- **Risk Detail:** A focused change for parent items in the navigator
- **Reward Details:** Users would be able to use the keyboard to navigate more efficiently
- **Original PR:** https://github.com/apple/swift-docc-render/pull/169
- **Issue:** rdar://90865355
- **Testing Details:** Manually tested in the browser and with Unit tests

[5.7] Improve the left/right arrow navigation inside the Navigator

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** Fixes a bug where urls with capital case segments cannot be matched against in the navigator
- **Risk Detail:** Cast the current URL to lowercase, before we do any matching.
- **Reward Details:** Fixes issues related to mixed-case urls and Navigator finding the current page item
- **Original PR:** https://github.com/apple/swift-docc-render/pull/181
- **Issue:** rdar://91824384
- **Testing Details:** Manually tested in the browser by changing the URL to have capital case letters and with unit tests

[5.7] Cast to lower case the current path in the navigator, to ensure matching paths with capital cases

---

src/components/DocumentationTopic/TopicsLinkBlock.vue
src/styles/core/_changes.scss

Bug/issue #, if applicable: 89800555
Fix width of highlight in S viewport to avoid it being cut off.

Fix width of highlight in S viewport

---

src/components/DocumentationTopic/DocumentationHero.vue
src/components/Navigator/NavigatorLeafIcon.vue
src/constants/HeroColors.js
src/constants/TopicTypes.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js
tests/unit/components/Navigator/NavigatorLeafIcon.spec.js

- **Rationale:** Icon color was not applying for collectionGroup and sampleCode pages
- **Risk Detail:** The change moved the color mapping logic to a different file, but is only changes affecting color and there's no change in the logic itself.
- **Reward Details:** Fixes the issue where the icons on those pages are not visible at all.  
- **Original PR:** https://github.com/apple/swift-docc-render/pull/158
- **Issue:** rdar://91450969
- **Testing Details:** Manually tested in the browser

[5.7] Update Icon color for collectionGroup and sampleCode 

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 91008709
Fixes the lack of space between the DocumentationHero and any deprecation warnings.
NA
[TinyMixedLanguageLibrary.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8512538/TinyMixedLanguageLibrary.doccarchive.zip)
Use the provided archive to test out this exact scenario, but its also a good idea to test with other archives, to make sure I did not introduce a regression.
Steps:
1. Go to http://localhost:8080/documentation/tinymixedlanguagelibrary
2. Assert there is enough space between the Hero and the deprecation notice

Fix no space between Deprecated warning and the DocumentationHero

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

- **Rationale:** Fixes a bug where there is no space between deprecated aside and the DocumentationHero
- **Risk Detail:** It conditionally adds an extra space to the description section and the DocumentationHero.
- **Reward Details:** Fixes a visual regression, where it has no space between items
- **Original PR:** https://github.com/apple/swift-docc-render/pull/188
- **Issue:** rdar://91008709
- **Testing Details:** Manually tested in the browser and added Unit tests

[5.7] Fix no space between description and the DocumentationHero

---

src/utils/custom-highlight-lang/swift.js
tests/unit/utils/custom-highlight-lang/swift.spec.js

Bug/issue #, if applicable: 89083261
This temporarily adds support for highlighting the `distributed` keyword for Swift code listings until highlight.js officially supports that itself with the next release.
A PR has already been [merged](https://github.com/highlightjs/highlight.js/pull/3523) in highlight.js for this, but this next v11.6 release may not be included as part of an official release for some time, so this is a workaround until then.
Add the following example Swift code listing to `SwiftDocCRender.docc/SwiftDocCRender.md`:
```swift
distributed actor Foobar {
distributed func baz() {
}
func qux() {
}
}
```
Steps:
1. Run `npm run build`. 
2. Run `DOCC_HTML_DIR=/path/to/swift-docc-render/dist npm run docs:preview` 
3. Open http://localhost:8000/documentation/swiftdoccrender and …

Patch swift syntax language to support `distributed` keyword

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/components/Navigator/NavigatorLeafIcon.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

Bug/issue #, if applicable: 91810837
This fixes the icon mapping so that technologies, API collections, articles, and sample code all have the right icons in both the sidebar and the documentation intro element.
In addition to changing the icon used for collections, the following mappings were needed to make things consistent in both places:
* `role` `"collection"` => `type` `"module"`
* `role` `"collectionGroup"` => `type` `"collection"`
Steps:
1. Verify that the right icon is used for the top level **technology** page in _both_ places
2. Verify that the right icon is used for the **API collections** in _both_ places
3. Verify that the right icon is used for **articles** in _both_ places
4. Verify that the right icon is used for **sample code** pages in _both_ places. 
5. Verify that the …

Fix issue where inconsistent icons are used between the sidebar and intro

---

src/components/DocumentationTopic/TopicsLinkBlock.vue

- **Rationale:** Fixes a bug where api diff highlight box gets cut off in small viewport.
- **Risk Detail:** Just 1-liner CSS change
- **Reward Details:** Fixes regression so the visual looks as intended.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/178
- **Issue:** rdar://89800555
- **Testing Details:** Manually tested in the browser.

[5.7] Fix width of highlight in S viewport

---

src/styles/core/_vars.scss

Bug/issue #, if applicable: 91070521
Make sure the spacing between elements is 40px.
Fixes issue where when Asides are shown, the spacing is 2rem (34px).

Make sure spacing between elements in body content is 40px

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

Bug/issue #, if applicable: 90792025
In order to optimize how icons look in the hero section, we want to add extra padding for short hero sections.
Note: anything that has less than 3 items, should be considered a short hero.

Extra padding for pages with short hero section 

---

src/components/Navigator/NavigatorCard.vue
src/constants/Changes.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 91762298
This PR adds available API change types as tags to the Navigator. Only types, that yield results will be available to the users to pick.
NA
Not yet testable, rely on Unit Tests

Add possible API changes as suggested tags in the sidebar Navigator

---

src/utils/strings.js
tests/unit/utils/search-utils.spec.js
tests/unit/utils/strings.spec.js

Bug/issue #, if applicable: 91443929
This PR simplifies the filter matching pattern on the Navigator. Now it wont highlight leading/trailing spaces on potential matches.
**Old Behaviour:**
`FooBar` would match `FooBar` and `Foo Bar`.
`Foo` would match `Foo` and ` Foo `
**Now:**
`FooBar` matches only `FooBar`
`Foo` matches only `Foo`
Matches are case-insensitive, so casing doesnt matter much.
NA
Steps:
1. Serve using any archive with an index
2. Type in the filter input on the Navigator a single word
3. Assert only the word is highlighted as matching in the results.

Simplify the matching pattern in the Navigator filter

---

src/utils/strings.js
tests/unit/utils/search-utils.spec.js
tests/unit/utils/strings.spec.js

- **Rationale:** Simplifies the filter matching pattern on the Navigator. Now it wont highlight leading/trailing spaces on potential matches.
- **Risk Detail:** Small change to the text matching pattern, that is used in the Navigator.
- **Reward Details:** Users get an improved text matching highlight.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/148
- **Issue:** rdar://91443929
- **Code Reviewed By:** @hqhhuang @SamLanier 
- **Testing Details:** Updated unit tests and manually tested in the browser.

[5.7] Simplify the matching pattern in the Navigator filter

---

src/utils/custom-highlight-lang/swift.js
tests/unit/utils/custom-highlight-lang/swift.spec.js

- **Rationale:** Adds support for syntax highlighting Swift 5.7 language feature.
- **Risk Detail:** Very small/focused change, adding one item to an array
- **Reward Details:** Allows `distributed` keyword to be syntax highlighted as expected in docs with Swift code.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/191
- **Issue:** rdar://89083261
- **Testing Details:** Visually verified example DocC pages with Swift code listings using the `distributed` keyword.

[5.7] Patch swift syntax language to support `distributed` keyword

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/components/Navigator/NavigatorLeafIcon.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- **Rationale:** Fixes an issue where different icons are used in the intro element when compared to the sidebar.
- **Risk Detail:** Small JS only change to fix one icon mapping and one place where the wrong data was being used to determine which icon to show.
- **Reward Details:** The same icon will always be shown in the intro element now, matching the icon in the sidebar for that page.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/194
- **Issue:** rdar://91810837
- **Testing Details:** Updated unit tests and visually checked each unique page type with an intro element (technology, API collection, article, sample code), and verified that there is no regression with icons for other page …

[5.7] Fix issue with mapping topic kind values

---

src/styles/core/_breakpoints.scss
src/styles/core/_vars.scss

- **Rationale:** Update padding in S viewport to use variable.
- **Risk Detail:** Added a mixin to calculate width and a variable for padding of body content.
- **Reward Details:** Allows styling override as a result of adding the mixin.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/177
- **Issue:** rdar://90844182
- **Testing Details:** Visually test in browser and verify that padding on either side of body content in small vp is still 20px.

[5.7] Update padding in S viewport

---

src/styles/core/_vars.scss

- **Rationale:** Change value for padding in body content to be 40px.
- **Risk Detail:** Only 1 variable change.
- **Reward Details:** Makes sure all the spacing on the page is 40px, removes inconsistency.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/193
- **Issue:** rdar://91070521
- **Testing Details:** Visually test in browser and verify that spacing between sections in the body content is 40px.

[5.7] Make sure spacing between elements in body content is 40px 

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- **Rationale:** Add extra padding for pages with short hero section (2 items or less), in order to optimize the look of hero icon.
- **Risk Detail:** Change only concerns the hero section.
- **Reward Details:** Makes sure icons look good in pages with short hero section, especially API Collection pages.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/184/
- **Issue:** rdar://90792025
- **Testing Details:** Visually test in browser and verify that padding is 60px in the hero section for pages that have 2 items or less in that section.

[5.7] Extra padding for pages with short hero section

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #, if applicable: 92119086
Adds support for rendering a "Beta" badge in the navigator alongside an item name when the relevant topic has been indicated as being so.
Example:
The behavior should be consistent with the deprecated badge, and the deprecated badge will take precedence over the beta badge in the rare scenario where an item happens to be both beta and deprecated, matching existing behavior for these badges at the top level of a page.
Steps:
1. Download/unzip [ExamplePackage.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8535415/ExamplePackage.doccarchive.zip)
2. Run `VUE_APP_DEV_SERVER_PROXY=/path/to/Example.doccarchive npm run serve`
3. Open http://localhost:8080/documentation/examplepackage and verify that a beta badge is rendered in the navigator …

Render beta badge in navigator when applicable

---

src/components/NavBase.vue

- **Rationale:** Fixes a bug where the chevron icon in the nav bar disappears at a certain zoom level
- **Risk Detail:** Isolated CSS changes in the nav bar.
- **Reward Details:** UI is now consistent when users zoom in/out
- **Original PR:** https://github.com/apple/swift-docc-render/pull/179
- **Issue:** : SR-16120
- **Code Reviewed By:** @hqhhuang @dobromir-hristov 
- **Testing Details:** In safari, enter simulator, set browser window to 800 x 700 VP, 1x res, Safari 15.3 - macOS - Mac; Zoom out to around 85%, verify that the chevron icon in nav bar appears consistently when zooming in/out

[5.7] Fix chevron icon in collapsed top nav bar is not visible 

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- **Rationale:** Adds support for rendering beta badge for items in navigator.
- **Risk Detail:** Very small, focused JS additions.
- **Reward Details:** Allows navigator to indicate which items are currently in beta.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/204
- **Issue:** rdar://92119086
- **Code Reviewed By:** @dobromir-hristov, @hqhhuang 
- **Testing Details:** Added unit tests, visually inspected example documentation with beta items.

[5.7] Render beta badge in navigator when applicable

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Title.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/Title.spec.js

Bug/issue #, if applicable: 92081750
This fixes a regression introduced on main with f12b885045341728ebf94329f0581747a933753e as part of the updated layout changes in support of the new navigator UX.
This happened because the `WordBreak` component only works with string slot content, and there was some shuffling of slots in the title component to add beta/deprecated text that caused it to stop working as expected.
main:
this branch:
Steps:
1. Run `env VUE_APP_DEV_SERVER_PROXY=https://ethan-kusters.github.io/swift-argument-parser npm run serve`
2. Open http://localhost:8080/documentation/argumentparser/parsablecommand/helpmessage(for:includehidden:columns:) (or any other long symbol whose title wraps to the next line)
3. Verify that the string is broken at the start of individual parameter …

[regression] Fix bug where long titles are now broken at arbitrary characters

---

src/App.vue
src/styles/base/_typography.scss
tests/unit/App.spec.js

- **Rationale:** Fixes issue where default footer with color scheme toggle may briefly flash on screen in IDE targets in rare scenarios where pages are being navigated very rapidly.
- **Risk Detail:** One JS conditional added, one color mapping changed
- **Reward Details:** Fixes visual bug where UI that shouldn't be shown is.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/215
- **Issue:** rdar://89998805
- **Code Reviewed By:** @dobromir-hristov, @hqhhuang 
- **Testing Details:** Added unit tests, manually reproduced problematic scenario and verified that the footer/toggle no longer flashes on-screen with these changes.

[5.7] Don't render default footer for IDE target

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Title.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/Title.spec.js

- **Rationale:** Fixes regression causing documentation page title headings to wrap at arbitrary characters when needed.
- **Risk Detail:** Minor shuffling of components to ensure existing JS logic continues to run.
- **Reward Details:** Fixes regression that has a negative impact on the UX of documentation.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/220
- **Issue:** rdar://92081750
- **Code Reviewed By:** @dobromir-hristov, @hqhhuang 
- **Testing Details:** Updated unit tests and visually verified that titles now wrap like they used to without reintroducing any new issues.

[5.7] Fix bug where long titles are now broken at arbitrary characters

---

src/components/Navigator/NavigatorCard.vue

- **Rationale:** Navigator scrollbar in Safari cannot be dragged with mouse
- **Risk Detail:** single css line added to a very isolated place
- **Reward Details:** Users can now click and drag the navigator scrollbar
- **Original PR:** https://github.com/apple/swift-docc-render/pull/221
- **Issue:** rdar://92337769
- **Code Reviewed By:** @marinaaisa @mportiz08 
- **Testing Details:** Assert you can drag the navigator scrollbar in Safari

[5.7] Fix bug in Safari, where the navigator cannot be scrolled by dragging scrollbar

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- Rationale: Prevent losing focus when navigating using the keyboard nav in Safari in the sidenav
- Risk: Low
- Risk Detail: it only resets the last focus target
- Reward: Medium
- Reward Details: Users won't lose focus when navigating using the keyboard nav in Safari in the sidenav
- Original PR: https://github.com/apple/swift-docc-render/pull/219/
- Issue: rdar://92082015
- Code Reviewed By: [@dobromir-hristov](https://github.com/dobromir-hristov)
- Testing Details: Assert you use the keyboard navigation in the sidenav in Safari

[5.7] Prevent losing focus when navigating using the keyboard nav in Safari in the sidenav

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #92082015, if applicable: 
When using the sidebar with keyboard arrows, pressing Enter on an item *with children* loses focus on the sidebar item, so you can’t use arrows to navigate the sidebar anymore. This doesn’t happen when you press Enter on rows that don’t have children though.
NA
Steps:
1. Open a .doccarchive with navigation
2. Open Safari
3. Use the keyboard arrows to navigate through the items in the sidenav
4. Press enter on a item and assert that it does not loses focus
5. Assert that there are no regressions

Sidebar AX: Focus is lost when pressing Enter on a row that has children

---

src/utils/syntax-highlight.js
tests/unit/utils/syntax-highlight.spec.js

- **Rationale:** Allows "objective-c" as language in fenced code blocks for syntax highlighting.
- **Risk Detail:** Minor JS adjustments to syntax highlighting logic.
- **Reward Details:** Added flexibility/convenience for users writing docs for ObjC APIs.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/233
- **Issue:** rdar://92454948
- **Testing Details:** Added unit test, manually tested that "objective-c" can be used in a fenced code block using DocC and syntax highlighting works as expected.

[5.7] Allow "objective-c" to be alias for syntax highlighting

---

src/components/Navigator/NavigatorDataProvider.vue
tests/unit/components/Navigator/NavigatorDataProvider.spec.js

Bug/issue #, if applicable: 91959429
Fixes a bug where the sidebar says "Fetching..." and stays like that indefinitely when the request for index data succeeds but is empty. There was one place in the code that was crashing and needed a default value.
Steps:
1. Download/unzip [empty-example.zip](https://github.com/apple/swift-docc-render/files/8592351/empty-example.zip) fixture
2. Run `env VUE_APP_DEV_SERVER_PROXY=/path/to/empty-example npm run serve`
3. Open http://localhost:8080/documentation/examplepackage
4. Verify that the sidebar promptly says "No data available." instead of getting stuck at "Fetching..."

Fix issue where sidebar says "Fetching..." indefinitely when index is empty

---

src/styles/core/_breakpoints.scss

Bug/issue #, if applicable: 91071765
Optimize the timing of adding extra padding to the side of the body content
Steps:
1. Manually verify that padding becomes 120px when the window width reaches 1251px. 

Optimize padding on either side of body content

---

src/components/DocumentationTopic/RelationshipsList.vue

Bug/issue #, if applicable: 92325863
Fixes a UI regression where column layout is broken in the `Relationships` section when API Change is turned on.
Steps:
1. Navigate to a page that has API Changes turned on in the `Relationships` section
2. Verify that the content in `Relationships` section is displayed vertically in a column form, instead of horizontally.

Fix column layout in `Relationships` section when API Change is on

---

src/styles/core/_breakpoints.scss

**Rationale:** Optimize the timing of adding extra padding to the side of the body content
**Risk:** Low
**Risk Detail:** only breakpoint change.
**Reward:** High
**Reward Details:** Better experience reading documentation in a medium to large viewport when navigator is expanded.
**Original PR:** https://github.com/apple/swift-docc-render/pull/239
**Issue:** rdar://91071765
**Code Reviewed By:** @marinaaisa 
**Testing Details:** Manually test in browser and verify that padding becomes 120px when the window width reaches 1251px.

[5.7] Optimize padding on either side of body content

---

src/components/DocumentationTopic/RelationshipsList.vue

**Rationale:** Fixes a UI regression where column layout is broken in the Relationships section when API Change is turned on.
**Risk:** Low
**Risk Detail:** only CSS changes affecting the Relationship section when API Change is on.
**Reward:** High
**Reward Details:** Fixes a bad UI regression introduced by the content style changes. 
**Original PR:** https://github.com/apple/swift-docc-render/pull/246
**Issue:** rdar://92325863
**Code Reviewed By:** @marinaaisa @dobromir-hristov  
**Testing Details:** Navigate to a page that has API Changes turned on in the Relationships section; Verify that the content in Relationships section is displayed vertically in a column form, instead of horizontally.

[5.7] Fix column layout in Relationships section when API Change is on

---

src/components/Navigator/NavigatorDataProvider.vue
tests/unit/components/Navigator/NavigatorDataProvider.spec.js

- **Rationale:** Fixes bug where sidebar says "Fetching..." forever if it successfully fetches an index without any navigator tree data.
- **Risk Detail:** Updates existing JS logic with a single additional OR case with a default empty array.
- **Reward Details:** Fixes UX issue that is uncommon but could be very confusing for users.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/238
- **Issue:** rdar://91959429
- **Testing Details:** Added unit tests, manually reproduced problematic scenario and verified that the sidebar now says "No data" instead of "Fetching...".

[5.7] Fix issue where sidebar says "Fetching..." indefinitely when index is empty

---

src/components/Navigator/NavigatorCard.vue

- Rationale: Update no results found text
- Risk: Low
- Risk Detail: it only changes a text string
- Reward: Low
- Reward Details: Users will get a new text message when no results on navigator were found
- Original PR: https://github.com/apple/swift-docc-render/pull/232
- Issue: rdar://92612891
- Code Reviewed By: @hqhhuang
- Testing Details: use the navigator's filter input with random text, assert that feedback text when no results is updated

[5.7-04252022] Update no results found text

---

src/components/Navigator/NavigatorCard.vue

- Rationale: Update no results found text
- Risk: Low
- Risk Detail: it only changes a text string
- Reward: Low
- Reward Details: Users will get a new text message when no results on navigator were found
- Original PR: https://github.com/apple/swift-docc-render/pull/232
- Issue: rdar://92438198
- Code Reviewed By: @hqhhuang
- Testing Details: use the navigator's filter input with random text, assert that feedback text when no results is updated

[5.7] Update no results found text

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Title.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 92420916
Users often triple click to select a paragraph and copy text. This PR fixes the issue where the `Deprecated` and `Beta` tags would be selected and copied as well.
Steps:
1. Triple clicking on the title of a documentation that has the `Deprecated` and `Beta` tag in different browsers.
2. Copy the text
3. Verify that only the title is copied, not also the `Deprecated` and `Beta` text

Avoid copying `Deprecated` and `Beta` tags when triple clicking to select the title

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Title.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/Title.spec.js

- **Rationale:** Fixes regression where documentation page titles no longer wrap as nicely as before.
- **Risk Detail:** Minor shuffling of DOM elements for page title.
- **Reward Details:** Fixes regression, improves readability of page titles.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/220
- **Issue:** rdar://92417513
- **Code Reviewed By:** @hqhhuang, @dobromir-hristov 
- **Testing Details:** Updated unit tests, visually tested that titles wrap in the manner they previously did.

[5.7-04252022] [regression] Fix bug where long titles are now broken at arbitrary characters

---

src/App.vue
src/styles/base/_typography.scss
tests/unit/App.spec.js

- **Rationale:** Fixes issue where default footer with color scheme toggle may briefly flash on screen in IDE targets in rare scenarios where pages are being navigated very rapidly.
- **Risk Detail:** One JS conditional added, one color mapping changed
- **Reward Details:** Fixes visual bug where UI that shouldn't be shown is.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/215
- **Issue:** rdar://92417724
- **Code Reviewed By:** @dobromir-hristov, @hqhhuang 
- **Testing Details:** Added unit tests, manually reproduced problematic scenario and verified that the footer/toggle no longer flashes on-screen with these changes.

[5.7-04252022] Don't render default footer for IDE target

---

src/components/Navigator/NavigatorCard.vue

- **Rationale:** Navigator scrollbar in Safari cannot be dragged with mouse
- **Risk Detail:** single css line added to a very isolated place
- **Reward Details:** Users can now click and drag the navigator scrollbar
- **Original PR:** https://github.com/apple/swift-docc-render/pull/221
- **Issue:**  rdar://92713735
- **Code Reviewed By:** @marinaaisa @mportiz08 
- **Testing Details:** Assert you can drag the navigator scrollbar in Safari

[5.7-04252022] Fix bug in Safari, where the navigator cannot be scrolled by dragging scrollbar

---

src/components/DocumentationTopic/RelationshipsList.vue

**Rationale:** Fixes a UI regression where column layout is broken in the Relationships section when API Change is turned on.
**Risk:** Low
**Risk Detail:** only CSS changes affecting the Relationship section when API Change is on.
**Reward:** High
**Reward Details:** Fixes a bad UI regression introduced by the content style changes. 
**Original PR:** https://github.com/apple/swift-docc-render/pull/246
**Issue:** rdar://92325863
**Code Reviewed By:** @marinaaisa @dobromir-hristov  
**Testing Details:** Navigate to a page that has API Changes turned on in the Relationships section; Verify that the content in Relationships section is displayed vertically in a column form, instead of horizontally.

[5.7-04252022] Fix column layout in Relationships section when API Change is on 

---

src/styles/core/_breakpoints.scss

**Rationale:** Optimize the timing of adding extra padding to the side of the body content
**Risk:** Low
**Risk Detail:** only breakpoint change.
**Reward:** High
**Reward Details:** Better experience reading documentation in a medium to large viewport when navigator is expanded.
**Original PR:** https://github.com/apple/swift-docc-render/pull/239
**Issue:** rdar://92360701
**Code Reviewed By:** @marinaaisa 
**Testing Details:** Manually test in browser and verify that padding becomes 120px when the window width reaches 1251px.

[5.7-04252022] Optimize padding on either side of body content

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Title.vue
tests/unit/components/DocumentationTopic.spec.js

- **Rationale:** Users often triple click to select a paragraph and copy text. This PR fixes the issue where the Deprecated and Beta tags would be selected and copied as well when users attempt to select the title.
- **Risk Detail:** only affects selecting titles of each page
- **Reward Details:** Improves the use case where users triple click to select the title and copy. Now they will only be able to copy the title, not the `Deprecated` and `Beta` tag.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/241
- **Issue:** rdar://92620913
- **Code Reviewed By:** @dobromir-hristov @marinaaisa 
- **Testing Details:** Navigate to a deprecated or beta page, triple click on the title and copy, paste the text and make sure only the title itself …

[5.7-04252022] Avoid copying Deprecated and Beta tags when triple clicking to select the title

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 91188362
If there is an item in the navigator, that links to another technology/documentation, going back should still re-apply the old filters.
https://github.com/apple/swift-docc-render/pull/234
Steps:
1. Assert there are no regressions when working with normal doccarchives.

Persist navigator data across technologies

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** Items should be scrolled into little by little, when focused, instead of jumping to the middle of the navigator scroll area.
- **Risk Detail:** affects the focus and scrolling logic on the navigator, when focusing new items
- **Reward Details:** Users will no longer see a jump in items when they reach the visible end of the list
- **Original PR:** https://github.com/apple/swift-docc-render/pull/247
- **Issue:** rdar://90601877
- **Code Reviewed By:** @marinaaisa @biamx3
1. Using keyboard arrows or VO, navigate up/down across the navigator.
2. Assert items are scrolled as you reach the bottom

[5.7] Scroll to items as you navigate to them 

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** Add tag to hide deprecated items in the Navigator
- **Risk Detail:** Adds a new filtering method, on top of the already complex filtering 
- **Reward Details:** Users will now be able to filter out any deprecated items
- **Original PR:** https://github.com/apple/swift-docc-render/pull/251
- **Issue:** rdar://92684644
- **Code Reviewed By:** @marinaaisa @biamx3
1. Assert you can see Hide Deprecated as a tag.
2. Assert that picking it, hides all deprecated items.

[5.7] Add ability to hide deprecated items in the Navigator

---

src/components/Icons/SpinnerIcon.vue
src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardInner.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCardInner.spec.js

- **Rationale:** Updates navigator loading UI to show spinner icon if data takes more than 1 second to load (replaces "Fetching..." text).
- **Risk Detail:** Adds new icon and makes minor update to loading UI to use the new icon.
- **Reward Details:** Improves the UX for the navigator when it takes a while to load.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/244
- **Issue:** rdar://92438279
- **Code Reviewed By:** @dobromir-hristov, @marinaaisa 
- **Testing Details:** Added/updated unit tests, visually tested that the spinner icon works/looks as expected for long loading navigator scenario.

[5.7] Use spinner icon to indicate indefinite progress while loading navigator

---

src/components/DocumentationTopic/BetaLegalText.vue

Bug/issue #, if applicable: 92669937
Prevent Beta legal text from getting cut off on the right when resizing window
Steps:
1. Navigate to a window with Beta legal text at the bottom of the page.
2. Verify that the text resizes correctly when going from L vp to M vp.

Prevent Beta legal text getting cut off on the right when resizing window

---

src/components/DocumentationTopic/BetaLegalText.vue

- **Rationale:** Prevent Beta legal text getting cut off on the right when resizing window when navigator is enabled
- **Risk Detail:** Only affects the Beta legal text badge at the bottom of the page.
- **Reward Details:** Beta pages with navigators will no longer have broken UI
- **Original PR:** https://github.com/apple/swift-docc-render/pull/260
- **Issue:** rdar://92669937
1. Navigate to a window with Beta legal text at the bottom of the page.
2. Verify that the text resizes correctly when going from L vp to M vp.

[5.7] Prevent Beta legal text getting cut off on the right when resizing window 

---

src/components/Icons/SpinnerIcon.vue
src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardInner.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCardInner.spec.js

- **Rationale:** Updates navigator loading UI to show spinner icon if data takes more than 1 second to load (replaces "Fetching..." text).
- **Risk Detail:** Adds new icon and makes minor update to loading UI to use the new icon.
- **Reward Details:** Improves the UX for the navigator when it takes a while to load.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/244
- **Issue:** rdar://92697154
- **Code Reviewed By:** @dobromir-hristov, @marinaaisa 
- **Testing Details:** Added/updated unit tests, visually tested that the spinner icon works/looks as expected for long loading navigator scenario.

[5.7-04252022] Use spinner icon to indicate indefinite progress while loading navigator

---

src/components/DocumentationTopic/BetaLegalText.vue

- **Rationale:** Prevent Beta legal text getting cut off on the right when resizing window when navigator is enabled
- **Risk Detail:** Only affects the Beta legal text badge at the bottom of the page.
- **Reward Details:** Beta pages with navigators will no longer have broken UI
- **Original PR:** https://github.com/apple/swift-docc-render/pull/260
- **Issue:** rdar://92669937
1. Navigate to a window with Beta legal text at the bottom of the page.
2. Verify that the text resizes correctly when going from L vp to M vp.

[5.7/04252022] Prevent Beta legal text getting cut off on the right when resizing window

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** Add tag to hide deprecated items in the Navigator
- **Risk Detail:** Adds a new filtering method, on top of the already complex filtering 
- **Reward Details:** Users will now be able to filter out any deprecated items
- **Original PR:** https://github.com/apple/swift-docc-render/pull/251
- **Issue:** rdar://92735740
- **Code Reviewed By:** @marinaaisa @biamx3
1. Assert you can see Hide Deprecated as a tag.
2. Assert that picking it, hides all deprecated items.

[5.7-04252022] Add ability to hide deprecated items in the Navigator

---

src/components/Tutorial/MobileCodePreview.vue

Bug/issue #76652132, if applicable: 
Adjust min-height value to match the lowest height to support WatchOS' screen ratio on the narrowest client
NA
Steps:
1. Run a .doccarchive with tutorials containing screenshots of watchOS
2. In the narrowest client (320px width) assert that previews containing screenshots of watchOS look correct

Adjust min-height value to match the lowest height to support WatchOS' screen ratio on the narrowest client

---

src/components/DocumentationTopic/BetaLegalText.vue
tests/unit/components/DocumentationTopic/BetaLegalText.spec.js

Bug/issue #, if applicable: 92980768
With the most recent content layout changes, the `BetaLegalText` component looks a little out of place due to its centered layout. Now, it will flow like normal page content, which looks more natural with the updated sidebar layout.
Steps:
1. Preview any content with beta APIs
2. Verify that the beta legal disclaimer now flows naturally along with the Overview/Topics content instead of being centered

Simplify layout of `BetaLegalText`

---

src/components/DocumentationTopic/PrimaryContent/ParametersTable.vue

- **Rationale:** ParameterTable changes should not go outside of container bounds, no matter screen size.
- **Risk Detail:** css only fix for very specific component
- **Reward Details:** Users will not see occasional overflowing content, on narrow devices with expanded navigator
- **Original PR:** https://github.com/apple/swift-docc-render/pull/285
- **Issue:** rdar://92961798
- **Testing Details:** Make sure rest components that have API changes, do not overflow content.

[5.7] make sure ParametersTable changes dont go outside of bounds

---

src/components/DocumentationTopic/PrimaryContent/ParametersTable.vue

- **Rationale:** ParameterTable changes should not go outside of container bounds, no matter screen size.
- **Risk Detail:** css only fix for very specific component
- **Reward Details:** Users will not see occasional overflowing content, on narrow devices with expanded navigator
- **Original PR:** https://github.com/apple/swift-docc-render/pull/285
- **Issue:** rdar://93032331
- **Testing Details:** Make sure rest components that have API changes, do not overflow content.

[5.7-04252022] make sure ParametersTable changes dont go outside of bounds

---

src/components/DocumentationTopic/BetaLegalText.vue
tests/unit/components/DocumentationTopic/BetaLegalText.spec.js

- **Rationale:** Updates layout of beta API disclaimer to be simpler to better align with recent design changes for documentation content.
- **Risk Detail:** Minor JS change to remove CSS classes.
- **Reward Details:** Improves suboptimal visual layout of component used on all beta SDK content pages.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/283
- **Issue:** rdar://92980768
- **Testing Details:** Updated unit tests, visually inspected pages with updated layout.

[5.7] Simplify layout of `BetaLegalText`

---

src/components/NavBase.vue
src/constants/nav.js
tests/unit/components/NavBase.spec.js

- **Rationale:** Adds support for overriding default behavior of links automatically closing the mobile nav.
- **Risk Detail:** Minor JS conditional change to check if element has a class.
- **Reward Details:** Allows for improved nav UX where links don't always close the nav when clicked.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/284
- **Issue:** rdar://92984703
- **Testing Details:** Added unit tests

[5.7] Allow non-menu-closing tray links

---

src/components/Filter/FilterInput.vue
tests/unit/components/Filter/FilterInput.spec.js

Bug/issue #90896758, if applicable: 
Tags and text should scroll as a unique element in filter input
NA
Steps:
1. Open a .doccarchive that has navigation
2. Select a tag and write a long string in the filter input
3. Assert that when scrolling, tags and input scroll along the way. Before only the text was scrolling.
4. Assert that AX is correct

Tags and text should scroll as a unique element in filter input

---

src/components/Filter/FilterInput.vue
tests/unit/components/Filter/FilterInput.spec.js

- Rationale: Adds support for scrolling tags and text on the filter input in navigator
- Risk: Low
- Risk Detail: Possible regressions on the filter input in navigator
- Reward: Medium
- Reward Details: Allows for improved nav UX where tags and text scroll as a unique element in filter input
- Original PR: https://github.com/apple/swift-docc-render/pull/291
- Issue: rdar://90896758
- Testing Details: unit and manual tests

[5.7] Tags and text should scroll as a unique element in filter input

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/components/Tutorial/MobileCodePreview.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

Bug/issue #, if applicable: 93050293
Current icon positioning looks odd on pages with longer hero sections.
This refactor centers the icons on those page, instead of pinning them to the top.
Steps:
1. Navigate to a page that has a few items in the hero section
2. Verify that icons is centered in the hero section.
3. Navigate to a page with short hero section
4. Verify that in bigger viewports, the icon is still pinned to the top of the page. As we shrink the viewport to medium and increase the size of the sidebar, verify that the icon is dynamically positioned in the center as well.

Refactor hero icon position; center on long hero sections 

---

src/components/AdjustableSidebarWidth.vue
src/components/Tutorial/MobileCodePreview.vue
src/utils/scroll-lock.js
tests/unit/utils/scroll-lock.spec.js

Bug/issue #, if applicable:  closes #293
Fixes a bug where the navigator would not unlock scrolling on mobile devices.
NA
You need an archive with Tutorials, like sloth creator
Steps:
1. From a doc page open the navigator on a mobile device
2. Click on a link, that leads to a tutorial
3. Assert scrolling is possible again

Ensure navigator unlocks scrolling when navigating away

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardInner.vue

Bug/issue #, if applicable: 93162464
Fixes the navigator height on mobile devices, because it was getting cutoff at the bottom.
NA
Steps:
1. On a mobile device, try to open the navigator and expand a few items
2. Assert it no longer cutsoff the bottom

Fix navigator height on mobile devices

---

src/components/AdjustableSidebarWidth.vue
src/utils/scroll-lock.js
tests/unit/utils/scroll-lock.spec.js

- **Rationale:** Fixes a bug where scrolling is locked, when navigating to a tutorial page from docs on mobile
- **Risk Detail:** Minor JS change to allow unlocking scrolling, even if lock target is no longer in the DOM.
- **Reward Details:** Users can scroll the page
- **Original PR:** https://github.com/apple/swift-docc-render/pull/294
- **Issue:** rdar://93326920
- **Testing Details:** Updated unit tests and manually tested in the browser.

[5.7] Ensure navigator unlocks scrolling when navigating away

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardInner.vue

- **Rationale:** Fixes a CSS layout bug, which was causing the navigator to have very large empty space at the bottom on Mobile devices
- **Risk Detail:** Minor CSS refactor
- **Reward Details:** Removes unnecessary large empty space for mobile devices
- **Original PR:** https://github.com/apple/swift-docc-render/pull/297
- **Issue:** rdar://93162464
- **Testing Details:** Visually inspected in the browser

[5.7] fix NavigatorCardInner height for mobile devices

---

src/components/DocumentationTopic/ContentTable.vue
src/styles/core/colors/_light.scss

Bug/issue #, if applicable: 92993225
Remove the background for topics section in IDE mode to be consistent with the web view.
Steps:
1. Verify that in IDE mode, there is no background color for topics section.

Remove background color for topics section in IDE

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- Rationale: Current icon positioning looks odd on pages with longer hero sections. This refactor centers the icons on those page, instead of pinning them to the top.
- Risk: Low
- Risk Detail: Change only related to the icon placement UI
- Reward: High
- Reward Details: Fixes broken looking UI in IDE mode, and when hero section is very long.
- Original PR: https://github.com/apple/swift-docc-render/pull/299
- Issue: rdar://93050564
- Testing Details: Manual test in browser
Navigate to a page that has a few items in the hero section, verify that icons is centered in the hero section; Navigate to a page with short hero section, verify that in bigger viewports, the icon is still pinned to the top of the page. As we shrink the viewport to medium and …

[5.7/04252022] Refactor hero icon position; center on long hero sections 

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardInner.vue

- **Rationale:** Fixes a CSS layout bug, which was causing the navigator to have very large empty space at the bottom on Mobile devices
- **Risk Detail:** Minor CSS refactor
- **Reward Details:** Removes unnecessary large empty space for mobile devices
- **Original PR:** https://github.com/apple/swift-docc-render/pull/297
- **Issue:** rdar://93346870
- **Testing Details:** Visually inspected in the browser

[5.7-04252022] fix NavigatorCardInner height for mobile devices

---

src/components/Navigator/NavigatorCardItem.vue

Bug/issue #, if applicable: 93331047
Fixes a small css bug, where focus outlines are shown when mouse clicks are used, causing issues both visually, and when clicking on the edge of the item as well.
I tried an alternative approach to the outlines, which uses box-shadows instead, but I think the current code can stay as well
```scss
.fromkeyboard & {
&:focus-within {
// simulate outline with box-shadow instead of border so it does not move items.
// outline is getting cutoff, so we cannot use it.
box-shadow: 0 $form-focus-size 0 0 inset var(--color-focus-color),
0 -#{$form-focus-size} 0 0 inset var(--color-focus-color);
box-sizing: border-box;
// add a small vertical padding, so active elements dont hide the box-shadow.
padding: $form-focus-size 0;
}
}
}
```
NA
Steps:
1. Click on items …

Remove focus outline for mouse clicks and allow clicking on edge of navigator items

---

src/components/DocumentationTopic.vue
src/components/Navigator.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/Navigator.spec.js

Bug/issue #91649938, if applicable: 
The 3 states are:
-  Router changes into a new page
-  Navigation is loading
-  Navigation is ready
NA
Steps:
1. Open a .doccarchive that has navigator
2. Turn on VoiceOver
3. Assert that when navigator is loading VoiceOver notify the user about it
4. Assert that when navigator is reading VoiceOver notify the user about it
5. Click on another technology in the navigator and go to its page
6. Assert that VO notify that current page has been changed 

[AX] VoiceOver should read when router changes into a new page, navigation is loading or is ready

---

src/components/DocumentationTopic.vue
src/components/Navigator.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/Navigator.spec.js

Rationale: VoiceOver should notify when router changes into a new page and navigation is loading or is ready 
Risk: Low
Risk Detail: Only VO changes
Reward: Low, only to VO users
Reward Details: Improves AX experience
Original PR: https://github.com/apple/swift-docc-render/pull/310
Issue: rdar://91649938
Code Reviewed By: @dobromir-hristov
Testing Details: Manual test in browser
1. Turn on VoiceOver
2. Assert that when navigator is loading VoiceOver notify the user about it
3. Assert that when navigator is reading VoiceOver notify the user about it
4. Click on another technology in the navigator and go to its page
5. Assert that VO notify that current page has been changed

[5.7] VoiceOver should read when router changes into a new page, navigation is loading or is ready 

---

src/components/Navigator/NavigatorCardItem.vue

Bug/issue #, if applicable: 93332275
Fixes a bug where if you navigate down in the navigator, it skips the Headings and throws errors in the console.
This is caused by a recent refactor, where we call `$refs.reference.$el.focus()`, but the `reference` can be a Vue component or a DOM element, in the second case it throws an error. That would be when we render an H3 instead of the Reference component.
NA
Steps:
1. Navigate down the navigator using arrow keys.
2. Assert no errors are visible in console.

Fix issue with navigating up/down in navigator

---

src/components/Navigator/NavigatorCardItem.vue

- **Rationale:** Fixes a bug where a console error gets thrown and headings are skipped, when navigating up/down in Navigator.
- **Risk Detail:** Minor JS change to allow focusing across headings in navigator.
- **Reward Details:** Users will not get errors in JS console and skipped items in Navigator
- **Original PR:** https://github.com/apple/swift-docc-render/pull/306
- **Issue:** rdar://93332275
- **Code Reviewed By:** @marinaaisa @hqhhuang 
- **Testing Details:** Updated unit tests and manually tested in the browser.

[5.7] Fix console error when navigating up/down in navigator

---

src/components/AdjustableSidebarWidth.vue
src/utils/scroll-lock.js
tests/unit/utils/scroll-lock.spec.js

- **Rationale:** Fixes a bug where scrolling is locked, when navigating to a tutorial page from docs on mobile
- **Risk Detail:** Minor JS change to allow unlocking scrolling, even if lock target is no longer in the DOM.
- **Reward Details:** Users can scroll the page
- **Original PR:** https://github.com/apple/swift-docc-render/pull/303
- **Issue:** rdar://93478881
- **Testing Details:** Updated unit tests and manually tested in the browser.

[5.7-04252022] Ensure navigator unlocks scrolling when navigating away

---

src/components/DocumentationTopic/RelationshipsList.vue

Bug/issue #, if applicable: 93456752
Fix a regression caused by the content style redesign where API changes highlight box is cut off on the right in S viewport
Manually verify in browser

Fix API Changes highlight cut off for relationship section in S viewport

---

src/components/DocumentationTopic/RelationshipsList.vue

- Rationale: Fix a regression caused by the content style redesign where API changes highlight box is cut off on the right in S viewport
- Risk: Low
- Risk Detail: Change only affects small viewport when API change is turned on
- Reward: High
- Reward Details: Fixes regression and broken UI
- Original PR: https://github.com/apple/swift-docc-render/pull/313
- Issue: rdar://93456752
- Testing Details: Manual test in browser

[5.7] Fix API Changes highlight cut off for relationship section in S viewport

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- Rationale: Current icon positioning looks odd on pages with longer hero sections. This refactor centers the icons on those page, instead of pinning them to the top.
- Risk: Low
- Risk Detail: Change only related to the icon placement UI
- Reward: High
- Reward Details: Fixes broken looking UI in IDE mode, and when hero section is very long.
- Original PR: https://github.com/apple/swift-docc-render/pull/299
- Issue: rdar://93050293
- Testing Details: Manual test in browser
Navigate to a page that has a few items in the hero section, verify that icons is centered in the hero section; Navigate to a page with short hero section, verify that in bigger viewports, the icon is still pinned to the top of the page. As we shrink the viewport to medium and …

[5.7] Refactor hero icon position; center on long hero sections

---

src/components/DocumentationTopic/RelationshipsList.vue

- Rationale: Fix a regression caused by the content style redesign where API changes highlight box is cut off on the right in S viewport
- Risk: Low
- Risk Detail: Change only affects small viewport when API change is turned on
- Reward: High
- Reward Details: Fixes regression and broken UI
- Original PR: https://github.com/apple/swift-docc-render/pull/313
- Issue: rdar://93517250
- Testing Details: Manual test in browser

[5.7-04252022] Fix API Changes highlight cut off for relationship section in S viewport

---

bin/check-source
src/setup-utils/license-header-built-files.js
src/setup-utils/vue-config-utils.js

- **Rationale:** Removes the license header from generated HTML files.
- **Risk Detail:** Minor build-time configuration change.
- **Reward Details:** Users will not get the apple license embedded into their public facing HTML pages.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/316
- **Issue:** rdar://93453002
- **Code Reviewed By:** @mportiz08
- **Testing Details:** Updated tests and ran test-builds to manually verify

[5.7] Remove the license header from generated HTML files

---

tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

Bug/issue #, if applicable: 93050293
This PR adds a test for the new language switchr prop for DocumentationHero and will fix vue warning in CI

Add test for new language switcher prop for DocumentationHero 

---

tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- **Rationale:** Added missing test for the new language switcher prop for DocumentationHero
- **Risk Detail:** Only modified test
- **Reward Details:** Fixes a cue warning in CI 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/321
- **Issue:** rdar://93050293
- **Testing Details:** Only updated test, run `npm run test` to verify

[5.7] Add test for new language switcher prop for DocumentationHero

---

tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

- **Rationale:** Added missing test for the new language switcher prop for DocumentationHero
- **Risk Detail:** Only modified test
- **Reward Details:** Fixes a cue warning in CI 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/321
- **Issue:** rdar://93577096
- **Testing Details:** Only updated test, run `npm run test` to verify

[5.7-04252022] Add test for new language switcher prop for DocumentationHero

---

src/utils/custom-highlight-lang/swift.js
tests/unit/utils/custom-highlight-lang/swift.spec.js
tests/unit/utils/syntax-highlight.spec.js

Bug/issue #, if applicable: 93358075
fixes #279 
Fixes a custom regex logic we have for detecting class functions in Swift code samples.
NA
You can use the archive attached
[TinyMixedLanguageLibrary 2.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8730599/TinyMixedLanguageLibrary.2.doccarchive.zip)
Steps:
1. Go to http://localhost:8080/documentation/tinymixedlanguagelibrary?language=objc
2. Assert the code sample is correctly highlighted

Prevent swift code samples from wrong highlighting keywords

---

src/components/TutorialsOverview/ChapterTopicList.vue
tests/unit/components/TutorialsOverview/ChapterTopicList.spec.js

Bug/issue #, if applicable: 93444894
In TutorialOverviews, when there is no time estimate provided for a tutorial, on mobile the link text is not aligned with the icon.
NA
Steps:
1. Use an archive that has tutorials without time estimates
2. On mobile size, assert that links are properly alligned

Properly align ChapterTopicList links to the icon, when no time estimate is passed

---

src/utils/custom-highlight-lang/swift.js
tests/unit/utils/custom-highlight-lang/swift.spec.js
tests/unit/utils/syntax-highlight.spec.js

- **Rationale:** Fixes a syntax highlighter bug for swift code
- **Risk Detail:** Changes the regex that matches some swift keywords.
- **Reward Details:** Users will get properly highlighted code listings.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/325
- **Issue:** rdar://93358075
- **Code Reviewed By:** @mportiz08
- **Testing Details:** Updated tests and tested manually in the browser

[5.7] Prevent swift code samples from highlighting wrong keywords

---

src/components/TutorialsOverview/ChapterTopicList.vue
tests/unit/components/TutorialsOverview/ChapterTopicList.spec.js

- **Rationale:** In Tutorial Overviews, when there is no time estimate provided for a tutorial, on mobile the link text is not aligned with the icon.
- **Risk Detail:** Changes vertical alignment of the links, only on items without an estimation.
- **Reward Details:** Users will get vertically offset items on mobile
- **Original PR:** https://github.com/apple/swift-docc-render/pull/317
- **Issue:** rdar://93444894
- **Code Reviewed By:** @mportiz08
- **Testing Details:** Updated tests and tested manually in the browser

[5.7] Vertically align ChapterTopicList links to icons, with no time estimations

---

src/components/ContentNode/CodeListing.vue

Bug/issue #, if applicable: 78783950
Fixes a bug where codelisting scrollbars are sometimes hidden in Safari, until you resize the screen.
NA
You can use SlothCreator to test.
Try setting scrollbars to `Always Show` in macOS settings.
Steps:
1. Use a resolution that would show horizontal scrollbars. Expand the navigator as much as possible.
2. Go to http://localhost:8082/documentation/slothcreator/sloth
3. Assert that scrollbars are always visible in safari and its fully scrollable
4. Try the same here - http://localhost:8082/tutorials/slothcreator/creating-custom-sloths

Fix scrollbars not showing for CodeListing in Safari

---

src/components/AdjustableSidebarWidth.vue
src/components/Navigator/NavigatorCard.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

- **Rationale:** Fixes a bug where there is always extra space at the bottom of the navigator, when there are extra items above the navigation
- **Risk Detail:** Animates the extra space away as you scroll down, noticeable in very specific conditions
- **Reward Details:** Users will not have extra space when they scroll down to the end of the Navigator list.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/298
- **Issue:** rdar://91002984
- **Code Reviewed By:** @mportiz08
- **Testing Details:** Tested manually in the browser and added unit tests

[5.7] Remove extra spacing from navigator bottom

---

src/components/AdjustableSidebarWidth.vue
src/components/Navigator/NavigatorCardInner.vue
src/styles/_base.scss
tests/unit/components/AdjustableSidebarWidth.spec.js

Bug/issue #, if applicable: 93506244
Exposes the viewport height as a Custom CSS Property, so it can be used for CSS calc expressions, instead of using `100vh` units.
This is to fix a mis-calculation on iPads, where the height of the top and bottom safari navbars are not accounted for in the height of the navigator
NA
Please test this on Android, Safari and on Desktop on the popular browsers. This could not only add a performance degradation, but as you scroll, it may shift the height of the navigator, causing stuttering.
Steps:
1. Open a page with a navigator on iPad
2. Assert you can scroll all the way down and see the last navigator items, while still having the Safari nav items visible

Fix iOS navigator not calculating height properly

---

src/components/AdjustableSidebarWidth.vue
src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
src/utils/FocusTrap.js
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/NavBase.spec.js
tests/unit/utils/FocusTrap.spec.js
tests/unit/views/DocumentationTopic.spec.js

- Rationale: Keyboard navigation shouldn't tag on hidden items in the navigator
- Risk: Low
- Risk Detail: It fixes FocusTrap and keyboard navigation
- Reward: Medium for keyboard navigation
- Reward Details: Keyboard navigation users won't tab on hidden elements
- Original PR: https://github.com/apple/swift-docc-render/pull/296
- Issue: rdar://91660503
- Testing Details: Tested manually in the browser and added unit tests

[5.7] [AX] Keyboard navigation shouldn't tag on hidden items in the navigator

---

src/components/AdjustableSidebarWidth.vue
src/components/Navigator/NavigatorCardInner.vue
src/styles/_base.scss
tests/unit/components/AdjustableSidebarWidth.spec.js

- **Rationale:** Fix a mis-calculation on iPads, where the height of the top and bottom safari navbars are not accounted for in the height of the navigator
- **Risk Detail:** Replaces a css only value with a JS generated one
- **Reward Details:** Only iOS users on a tablet will see a difference, when at the very top of the page
- **Original PR:** https://github.com/apple/swift-docc-render/pull/328
- **Issue:** rdar://93506244
- **Testing Details:** Tested manually in the browser and added unit tests

[5.7] Fix iOS navigator not calculating height properly

---

src/components/Navigator.vue
src/views/DocumentationTopic.vue
tests/unit/components/Navigator.spec.js

- Rationale: Navigator doesn't need a aside element but it needs an aria-label for better VO interpretation
- Risk: Low
- Risk Detail: VO readability
- Reward: Low
- Reward Details: It improves VO readability on the navigator
- Original PR: https://github.com/apple/swift-docc-render/pull/340/
- Issue: rdar://94043661
- Code Reviewed By: @dobromir-hristov 
- Testing Details: Added automation tests and tested manually in the browser

[5.7] [AX] Aside element not needed as parent of Navigator and Navigator needs aria-label

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/Navigator/NavigatorCard.vue

- **Rationale:** Centers the icon that toggles the navigator on mobile devices vertically, as it was a couple of pixels off.
- **Risk Detail:** Changes isolated css styling
- **Reward Details:** Users will get vertically aligned items in the navbar.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/248
- **Issue:** rdar://92095402

[5.7] Optically center the navigator toggle icon in Nav

---

src/components/Tutorial/CodePreview.vue
tests/unit/components/Tutorial/CodePreview.spec.js

- **Rationale:** Fixes an issue where tutorial previews display incorrectly after second click
- **Risk Detail:** minor refactor
- **Reward Details:** Users will no longer see obvious UI issue when previewing a tutorial 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/338
- **Issue:** rdar://93843834
- **Code Reviewed By:** @marinaaisa @dobromir-hristov   

[5.7] Fix preview box getting cut off for Tutorial pages

---

src/components/ImageAsset.vue
tests/unit/components/ImageAsset.spec.js

- **Rationale:** Fixes issue where 2x images may appear too large on 1x displays if the RenderJSON does not provide image size attributes or a 1x image equivalent.
- **Risk Detail:** Adds additional JavaScript logic that runs every time an image is loaded.
- **Reward Details:** Fixes issue that could have noticeable impact for certain images on 1x displays.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/292
- **Issue:** rdar://88195563
- **Testing Details:** Added unit tests, manually tested problematic scenario with example documentation.

Calculate image sizes when not provided by Render JSON

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 54931063
Since the logic in the `WordBreak` component was mainly needed and designed for symbol pages (those without the enhanced hero background), it should only be used there and not for every kind of generic page title (like articles, etc).
Steps:
1. Run `env VUE_APP_DEV_SERVER_PROXY=https://ethan-kusters.github.io/swift-argument-parser npm run serve` to start the dev server using data from an example project
2. Open http://localhost:8080/documentation/argumentparser/gettingstarted and verify that the word "ArgumentParser" in the page title heading **no longer contains** a `<wbr>` HTML element between the text "Argument" and "Parser"
3. Open http://localhost:8080/documentation/argumentparser/optiongroup and verify that the word "OptionGroup" in the page …

Stop using word break logic in titles for "enhanced" pages

---

src/errors/FetchError.js
src/errors/RedirectError.js
src/utils/data.js
tests/unit/setup-utils/SwiftDocCRenderRouter.spec.js
tests/unit/utils/data.spec.js

- **Rationale:** Fixes an issue with following redirect rules.
- **Risk Detail:** Changes the logic that handles 301 and 302 redirects
- **Reward Details:** Users will now be properly redirected to the new path.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/352
- **Issue:** rdar://74717074
- **Code Reviewed By:** @mportiz08  

[5.7] Fix fetch redirects

---

src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue
src/components/Navigator/NavigatorCardItem.vue

Bug/issue #, if applicable: 89923444
Language toggle should have a pointer cursor icon.
NA
Open an archive that has language versions
Steps:
1. Assert that hovering over the language toggle shows a pointer cursor

LanguageToggle dropdown should have a cursor-pointer

---

src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue

- **Rationale:** Fixes a visual issue with hovering the Language picker
- **Risk Detail:** Scoped CSS only change
- **Reward Details:** Users will now see a pointer hand, when hovering over the dropdown.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/363
- **Issue:** rdar://89923444

[5.7] LanguageToggle dropdown should have a cursor-pointer

---

src/components/Article.vue
src/components/Tutorial.vue
src/components/Tutorial/NavigationBar.vue
src/views/Topic.vue
tests/unit/components/Article.spec.js
tests/unit/components/Tutorial.spec.js
tests/unit/components/Tutorial/NavigationBar.spec.js
tests/unit/views/Topic.spec.js

- **Rationale:** Modifies the NavigationBar to use paths from the references to build the URLs for SecondaryDropdown and MobileDropdown elements.
- **Risk Detail:** Changes the logic that builds the nav dropdowns in Tutorials
- **Reward Details:** The app will use the proper data to build the Tutorials, which currently is not user facing
- **Original PR:** https://github.com/apple/swift-docc-render/pull/337
- **Issue:** rdar://63628221
- **Code Reviewed By:** @mportiz08  
- **Testing Details:** Tested manually in the browser and added unit tests.

[5.7] Use references to build secondary navigation urls in NavigationBar

---

src/styles/core/_breakpoints.scss

Bug/issue #, if applicable: 95981164
Remove `min-width` property from `breakpoint-dynamic-sidebar-content`; this change only affects the web. 
Steps:
1. Inspect the body content `container` class in ContentTable, DocumentationTopic, and BetaLegalText; and `__content` class in DocumentationHero. Assert that no `min-width` property are applied.

Remove `min-width` from web content container

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 94295219
Removes the "Hide Deprecated", when API changes are Enabled.
NA
NA

Make sure "Hide Deprecated" is not shown, when API changes are enabled

---

src/styles/core/_breakpoints.scss

- **Rationale:** Fixes a regression introduced by recent style changes for padding in the small viewport.
- **Risk Detail:** Minimal CSS changes
- **Reward Details:** Fixes a regression introduced by recent style changes.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/369
- **Issue:** rdar://95981164
- **Code Reviewed By:** @dobromir-hristov @SamLanier 
- **Testing Details:** Tested manually in the browser.

[5.7] Remove `min-width` from web content container

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Rationale:** Modifies the Navigator tags to now show "Hide Deprecated" tag, if API changes are available.
- **Risk Detail:** Changes the logic that shows tags
- **Reward Details:** Users no longer will see Deprecated items, even though they clicked Hide Deprecated.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/375
- **Issue:** rdar://94295219
- **Code Reviewed By:** @mportiz08  
- **Testing Details:** Tested manually in the browser and added unit tests.

[5.7] Make sure "Hide Deprecated" is not shown, when API changes are enabled

---

src/components/Footer.vue

- **Rationale:** Fixes the footer gutters on small screen sizes to match those of the navigator.
- **Risk Detail:** CSS Only changes to the footer
- **Reward:** Small
- **Reward Details:** Gutter sizes are now the same as the header.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/362
- **Issue:** rdar://91829676
- **Code Reviewed By:** @marinaaisa   

[5.7] Fix footer gutters on small sizes

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #92738111
Adds support for recursively expanding all of the children underneath a given navigator item by using Option-Click or Option-Right Arrow. This matches the behavior of standard navigators like the one used in Finder.
NA
Steps:
1. Start docc-render with a doccarchive
2. Navigate mouse/select to navigation sidebar on left.
3. Press Option (or Alt)+ Right Arrow
4. Assert that all children items in navigator are open.

Open Navigator Recursively with Option-Right Arrow

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- **Rationale:**  Adds support for recursively expanding all of the children underneath a given navigator item by using Option-Click or Option-Right Arrow.
- **Risk Detail:** Small, additional keyboard shortcut introduced
- **Reward Details:** Allows for additional shortcut of option-right-arrow to expand navigator
- **Original PR:** https://github.com/apple/swift-docc-render/pull/383
- **Issue:** rdar://92738111
- **Code Reviewed By:** @marinaaisa   
- **Testing Details:** Updated unit tests

[5.7] Open Navigator Recursively with Option-Right Arrow

---

src/components/NavBase.vue
tests/unit/components/NavBase.spec.js

Bug/issue #, if applicable: 94461604
Fixes a regression from #367 , where on mobile it would not open the navigator
NA
Steps:
1. On mobile viewport try to open the navigator from the Nav toggle
2. Assert it opens the navigator

Fix bug where mobile navigator does not open

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue
src/components/NavBase.vue
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/DocumentationTopic/DocumentationNav/LanguageToggle.spec.js
tests/unit/components/NavBase.spec.js

- **Rationale:** The language switcher will now wait for the nav to collapse itself, before changing the language. This will prevent glitchy collapse animation from changing breadcrumbs.
- **Risk Detail:** Adds logic to wait for the animation to finish, before changing the language
- **Reward Details:** Users no longer get a glitchy language switching exp on mobile
- **Original PR:** https://github.com/apple/swift-docc-render/pull/367
- **Issue:** rdar://94461604
- **Code Reviewed By:** @hqhhuang     
- **Testing Details:** Tested manually in the browser and added unit tests

[5.7] Wait for the nav collapse animation to end before changing the language on mobile

---

src/components/DocumentationTopic/TopicsLinkBlock.vue
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js

Bug/issue #94293647: 
Framework name links in Topics are now rendered in body text styling not code voice
NA
1. Use a docc archive with a rendernode with body text styling in code, (where a topic role is also a collection)
2. Run local environment
3. Assert that Framework name links in topics are now rendered in body text styling instead of code voice

Framework Name Links In Body Styling

---

src/components/DocumentationTopic/TopicsLinkBlock.vue
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js

Bug/issue #, if applicable: 62751444
Plist links in the Topics section should not be in code voice
Manually verify in browser 
Steps:
1. Navigate to a documentation with links to property list pages in the topics section
2. Verify that the link is rendered in plain text instead of code voice

Plist links in topics section should not be in code voice

---

src/components/DocumentationTopic/PrimaryContent/DeclarationGroup.vue
src/components/DocumentationTopic/PrimaryContent/ParametersTable.vue
src/components/DocumentationTopic/RelationshipsList.vue
src/components/DocumentationTopic/TopicsLinkBlock.vue
src/styles/base/_changes.scss
src/styles/core/_changes.scss
src/styles/core/_vars.scss
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js

- Rationale: Move API changes icons to the left
- Risk: Medium
- Risk Detail: Affects most of the API changes styling for Documentation pages
- Reward: Medium
- Reward Details: Aligns the design and position of API changes with the new visuals of the navigator
- Original PR: https://github.com/apple/swift-docc-render/pull/249
- Issue: rdar://91807576
- Code Reviewed By: @marinaaisa 
- Testing Details: Tested manually in the browser and added relevant unit tests

[5.7] Move changes icons left and remove width compensation

---

src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- Rationale: Toggle entire tree when clicking while pressing alt key on title symbol at Navigator
- Risk: Low
- Risk Detail: Only affects a small interaction in the navigator
- Reward: Low
- Reward Details: Users will be able to toggle the entire tree in a new interaction, similar to the macOS experience
- Original PR: https://github.com/apple/swift-docc-render/pull/389
- Issue: rdar://94150776
- Code Reviewed By: @hqhhuang @dobromir-hristov 
- Testing Details: Tested manually in the browser and added relevant unit tests

[5.7] Toggle entire tree when clicking while pressing alt key on title symbol at Navigator

---

src/components/DocumentationTopic/TopicsLinkBlock.vue
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js

- **Rationale:**   Framework name links in Topics to be rendered in body text styling instead of code voice
- **Risk Detail:**  Small conditional logic changes for TopicsLinksBlock
- **Reward Details:** Proper rendering of framework name links 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/371
- **Issue:** rdar://94293647
- **Code Reviewed By:** @mportiz08 @hqhhuang @marinaaisa @dobromir-hristov 
- **Testing Details:** Updated unit tests, tested manually on rendernodes

[5.7] Framework name links in Topics to be rendered in body text styling instead of code voice

---

src/components/DocumentationTopic/TopicsLinkBlock.vue
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- Rationale: Plist links are being displayed in code voice in the topics section, which is misleading and inconsistent with how the same links are displayed on other sections of the page
- Risk: Low
- Risk Detail: Only affects plist links in the topic section; does not affect other types of pages.
- Reward: High
- Reward Details: Plist items will no longer be incorrectly displayed in code voice in the Topics section
- Original PR: https://github.com/apple/swift-docc-render/pull/390
- Issue: rdar://62751444
- Code Reviewed By: @mportiz08 
- Testing Details: Tested manually in the browser and added relevant unit tests
Note: dependency: https://github.com/apple/swift-docc-render/pull/388

[5.7] Plist links in topics section should not be in code voice

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: 97024618
Moves the multiline code detection after we indent ObjC code, so we can properly detect newly created new lines.
NA
This bug is seen in Safari only, so use that to test.
Steps:
1. Go to a page that has a multiline declaration in ObjC language
2. Assert with the inspector, that there is a `.has-multiple-lines` class on the `.source` class.

Fix multiline detection in DeclarationSource for ObjC

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/stores/QuickNavigationStore.js
src/views/DocumentationTopic.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js

Bug/issue #97377452, if applicable: 
Preventing storing quick navigator if the feature flag is off.
This fix is to prevent performance issues when rendering big frameworks in the Navigator with the quick navigator flag off.
NA
Steps:
1. Use a large framework that has navigator
2. Assert that everything works correctly and there isn't performance issues

Preventing storing quick navigator if the feature flag is off

---

src/components/ColorSchemeToggle.vue
src/components/Filter/FilterInput.vue
src/components/Navigator/NavigatorCardItem.vue
src/styles/core/_helpers.scss

Bug/issue #94221573, if applicable: 
Color scheme toggle keyboard navigation should follow radio buttons standards: https://www.w3.org/WAI/ARIA/apg/example-index/radio/radio.html
https://user-images.githubusercontent.com/8567677/182437276-458b790e-e91d-4d8a-b1c9-ee6f49f761df.mov
NA
Steps:
1. Run any doccarchive
2. Go to footer
3. Tab and assert that you focus the radio buttons for the Color scheme toggle
4. Assert that by pressing the arrow keys you can select different color schemes

[AX] Color scheme toggle keyboard navigation should follow radio buttons standards

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 99279409
Fixes a bug where the navigator does not scroll to the active item, if deeply in to the tree.
NA
Steps:
1. Navigate to a deep item in your docs navigator
2. Assert that when you refresh, i scrolls to the active item

Fixes scrolling the navigator to the active item

---

src/components/AdjustableSidebarWidth.vue

Bug/issue #, if applicable: 99316400
Fixes an issue where the navigator filter gets cutoff when you expand a few items in the Navigator.
This happens because we were trying to catch transition events the adjustable sidebar in order to apply some extra styling mid transition. However, those event listeners would also catch deep child events as well, which was causing the bug.
A good practice with `transitionstart` event is to use the `.self` modifier, which I totally forgot.
NA
Steps:
1. Open/close a few items in the navigator
2. Assert filter is not cutoff when you click into it.

Fix navigator filter getting cutoff

---

src/components/Asset.vue
src/components/ReplayableVideoAsset.vue
src/components/VideoAsset.vue
tests/unit/components/Asset.spec.js
tests/unit/components/ReplayableVideoAsset.spec.js
tests/unit/components/Tutorial/SectionIntro.spec.js
tests/unit/components/VideoAsset.spec.js

Bug/issue #, if applicable: 97715398
1. Refactors the Video component to allow rendering videos with sound.
2. Properly pass `posterVariants` to `VideoAsset.vue` from `ReplayableVideoAsset.vue`. This was a bug left from before.
3. Make sure `ReplayableVideoAsset.vue` shows the proper text in it's "Play" butotn, if its not autoplayed yet.
NA
This PR can be best tested with 
Steps:
1. Assert Videos can be rendered with sound ON.
2. Assert that videos with Sound and Autoplay, show a "Play" button.
3. Assert that the "Play" button changes to "Replay", upon video completion. 
4. Assert that in Safari, it shows a "Play" button, even if autoplay is ON with sound.

Refactor Video assets to allow sound, poster support to replayable videos, text fixes.

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 99748634
Fixes a bug where `alt` + clicking on a tree to deep toggle it, would add extra spaces under each groupMarker.
This is indirectly caused by #355, as `groupMarkers` now have references to items they label, which was not handled properly, when considering toggling.
NA
Steps:
1. Toggle items on/off while holding the `alt` key.
2. Assert items behave as expected, without adding extra space.

Make sure toggling full trees takes groupMarkers into consideration and does not add extra space

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 99747732
Fixes a bug where `cmd` + clicking on an item to toggle-off it and it's siblings was removing all clickable links from the list.
This was caused by a refactor in #355 to `groupMarkers`, and that extra data was not handled properly for toggling situations.
NA
Steps:
1. `cmd` + click on an item with children.
2. Assert all siblings are opened and closed without any issues or missing items from the list.

Fix toggling off sibling items removes everything but groupMarkers

---

src/components/ContentNode.vue
src/components/ContentNode/Figure.vue
src/components/ContentNode/FigureCaption.vue
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Figure.spec.js
tests/unit/components/ContentNode/FigureCaption.spec.js

Bug/issue #, if applicable: 97715120
Extends support for the `@Image` directive, by allowing users to add captions to images. 
It uses the already available `InlineImage` component, and just extends the `Figure` logic to wrap, if either an `anchor` or `abstract` is present.
DocC PR - 
You can add this RenderJSON piece to the `content` array of your render json `primaryContentSections`:
```json
{
"type": "image",
"identifier": "reference-for-image",
"metadata": {
"abstract": [
{
"type": "text",
"text": "Image Caption"
}
]
}
}
```
Or use the attached JSON:
[example_image.json.zip](https://github.com/apple/swift-docc-render/files/9289833/example_image.json.zip)
Steps:
1. Assert the caption is rendered below the image
Make sure you check off the following items. If they cannot be completed, …

Add support for the `@Image` directive

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/components/DocumentationTopic/TopicLinkBlockIcon.vue
src/components/DocumentationTopic/TopicsLinkBlock.vue
src/components/IconOverrideProvider.vue
src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardItem.vue
src/components/Navigator/NavigatorDataProvider.vue
src/components/SVGIcon.vue
src/components/TopicTypeIcon.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js
tests/unit/components/DocumentationTopic/TopicLinkBlockIcon.spec.js
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js
tests/unit/components/IconOverrideProvider.spec.js
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js
tests/unit/components/Navigator/NavigatorDataProvider.spec.js
tests/unit/components/TopicTypeIcon.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 97715925
Allow overriding the icons and images related to a page. These can be navigator icon, DocumentationHero icon or the Topics links.
**Note 1**
This PR sort of builds upon the #402, and more particularly the icon overriding. There should be minimal changed needed for both to co-exist.
#402
DocC PR - https://github.com/apple/swift-docc/pull/367
Use the DocC PR to build an archive with image overrides or use the attached one below
[archive_with_icon_override.zip](https://github.com/apple/swift-docc-render/files/9564779/archive_with_icon_override.zip)
Steps:
1. Point docc-render's serve to the archive of your choice
2. Go to a page that has page overrides, in my case `http://localhost:8081/documentation/docc/formatting-your-documentation-content`
3. Assert …

Support custom page icons and image overrides

---

src/components/NavMenuLink.vue
tests/unit/components/NavMenuLink.spec.js

Bug/issue #, if applicable: 97716953
Navigation links use router-link directly, but if we use the References, we can add links to external sites, disable links if they are falsy and more.
NA
1. Assert everything works just as before

Use Reference for NavMenuLink

---

src/components/DocumentationTopic/BetaLegalText.vue

Bug/issue #, if applicable: 99979298
Removes an old background color override that used to be necessary with a previous layout design (pre sidebar) but is no longer needed now since the "Topics" section always has the same background color now.
Steps:
1. Find pages with beta content, ideally both examples _with_ a "Topics" section and also one _without_ a "Topics" section.
2. Verify that the background color for the "Beta Software" element is always using the same secondary fill color.

Remove unnecessary background color override for legal text

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/Topics.vue
src/components/DocumentationTopic/TopicsLinkCardGrid.vue
src/components/DocumentationTopic/TopicsTable.vue

The `'docc-render'` prefix should be preferred over `'@'` when relevant to prevent issues with other Vue apps integrating these components.

Adjust syntax for some root relative imports

---

src/components/ContentNode.vue
src/components/ContentNode/Table.vue
tests/unit/components/ContentNode.spec.js

Bug/issue #, if applicable: rdar://100337272
This PR takes a new `alignments` property from Render JSON and adds new styles to table cells to control their text alignments.
https://github.com/apple/swift-docc/pull/389
See the testing instructions from the linked Swift-DocC PR.
- [ n/a ] Updated documentation if necessary

use table column alignments when available

---

tests/unit/utils/throttle.spec.js

Bug/issue #, if applicable: 100137207
This should make these tests more stable and reliable while also ensuring that they don't take a fixed amount of real time to run.
Steps:
1. Run `npm test` and verify that all unit tests still pass.

Re-write throttle specs to use fake timers

---

src/components/CardCover.vue

Bug/issue #, if applicable: 100705861
Fixes an issue with cards not styling fallback images as cover, when the correct image cannot be loaded.
NA
Mount the provided docc-archive - [docc-build.zip](https://github.com/apple/swift-docc-render/files/9695519/docc-build.zip)
Steps:
1. Go to http://localhost:8081/documentation/docc/formatting-your-documentation-content
2. Block the card image in Developer Tools from downloading
3. Refresh and assert the fallback is properly aligned. 

fix: card cover styling for fallback images

---

src/components/NavBase.vue
tests/unit/components/NavBase.spec.js

Bug/issue #, if applicable: 101062950
This PR fixes: Localnav should not FocusTrap for documentation pages without breaking navigator toggle after expanding nav menu.
Steps:
1. Expand nav menu with mouse, cmd+tab to navigate through the links. Assert that focus is not trapped (can go up to the browser menu bar). Assert that we can't tab to links outside of the nav menu 
2. Assert that navigator toggle works after expanding and closing nav menu. Assert that navigator toggle works even with nav menu expanded. 

Prevent tabbing to body links without breaking Navigator toggle

---

src/constants/ContentSectionAnchors.js
tests/unit/components/DocumentationTopic/PrimaryContent/Declaration.spec.js
tests/unit/mixins/__snapshots__/onThisPageRegistrator.spec.js.snap

Bug/issue #, if applicable: 101549478
This fixes a minor typo introduced in #438 where the top level "Declaration" sections heading was mistakenly rewritten as "Declaration**s**".
Steps:
1. Run `env VUE_APP_DEV_SERVER_PROXY=https://sofiaromorales.github.io/swift-argument-parser npm run serve`
2. Open http://localhost:8080/documentation/argumentparser/option/init(wrappedvalue:name:parsing:help:completion:)-7ilku/
3. Verify that the declaration section heading reads "Declaration" (singular)

Fix typo: "Declarations" section should be "Declaration"

---

src/components/ImageAsset.vue
src/components/VideoAsset.vue
src/utils/assets.js
tests/unit/components/VideoAsset.spec.js

Bug/issue #, if applicable: 101373576
Sets the width/height of video to match those of their poster image, if provided. This prevents jumping on the page, if the video and poster are different dimensions.
NA
Steps:
1. Use an archive that has a video with a cover image. The image should be smaller than the video.
2. Assert the video is rendered with the same dimensions as the poster image.
3. Assert that switching dark/light mode follows the dimensions of the poster image.

Make sure videos are as big as their poster image.

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/ContentTable.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 101513120
Removes extra border from Topics title, if there is no primary content above the Topics section.
NA
Steps:
1. Go to a page that has no content, only topics.
2. Assert there is no border rendered on the page.

Remove extra content border

---

src/components/ContentNode/TabNavigator.vue

Bug/issue #, if applicable: 101627936
Makes sure content is updated when switching across tabs in a TabNavigator. If using a `@Video` tag, the video element is currently cached and never re-renders.
NA
Steps:
1. Create a TabNavigator with a video in each
2. Assert that switching tabs also switches the video sources.
3. Play one video and switch tabs. Assert the Replay button becomes Replay and video is chagned.

Make sure content updates, when switching TabNavigator tabs

---

src/components/ContentNode.vue
src/components/ContentNode/Row.vue
src/components/DocumentationTopic/TopicsLinkCardGrid.vue
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Row.spec.js
tests/unit/components/DocumentationTopic/TopicsLinkCardGrid.spec.js

Bug/issue #, if applicable: 101583390
The compactGrid style for Topics should become a 2 col grid on Medium sizes, because it cramped atm on smaller sizes. On Mobile its still 1 column.
NA
Steps:
1. Set a TopicsSectionStyle to a page to compactGrid
2. Assert that the grid of card items has columns as follows: 3 on Large, 2 on medium, 1 on small.

Make compactGrid a 2 column grid on Medium sizes

---

src/components/Navigator/NavigatorDataProvider.vue
src/views/DocumentationTopic.vue
tests/unit/components/Navigator/NavigatorDataProvider.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 101803433
Fixes an issue where the navigator is closing sibling trees. This is happening because of extra computed property re-calculations, from the recent PR - #396 
The exact cause of the problem is that computed properties re-calculate themselves and all depending computeds and render functions, when any of the dependencies in the chain change.
In our case, the `technology` passed to the `NavigatorDataProvider` changes on each page navigation, even though its the same object visually, it is not the same Object reference. 
This was not such a problem before, because we used to just find the Technology with the children from the already fetched navigator data set, and that object actually never changes. The `technology` on the DocumentationTopic however does …

Fix issue with Navigator closing sibling trees

---

src/components/ContentNode/FigureCaption.vue
src/components/DocumentationTopic/ContentNode.vue

Bug/issue #, if applicable: 101632403
Adjusts the bottom margin of an `img` when it has a caption, to be close to the caption itself. Moves that spacing to the caption text so spacing is consistent. 
NA
Steps:
1. Assert that spacing of an image with or without a caption is the same, considering post/prior items.
2. Assert the caption is closer to the image, than the vertical space between the next element.

Make sure image spacing inside `figure` is consistent

---

src/components/ContentNode/Row.vue
src/components/ImageAsset.vue
src/components/Navigator/NavigatorCardItem.vue
src/components/OverridableAsset.vue
src/components/TopicTypeIcon.vue
tests/unit/components/Asset.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js
tests/unit/components/DocumentationTopic/TopicsLinkCardGridItem.spec.js
tests/unit/components/ImageAsset.spec.js
tests/unit/components/Navigator/NavigatorCardItem.spec.js
tests/unit/components/OverridableAsset.spec.js

Bug/issue #, if applicable: 101679521
This fixes issues with Navigator icons when loaded from remote servers. 
NA
Steps:
1. Assert that overloaded icons look OK in both Navigator and Cards from `@Links` directive

Fix issue with shifting icons in Navigator

---

src/components/Icons/TwoLetterSymbolIcon.vue

Bug/issue #, if applicable: 102030864
Fixes the inside spacing of TwoLetter icons.
NA
Steps:
1. Assert two letter icons in the nav look correct

Fix two letter icon spacing

---

src/components/Navigator/NavigatorCard.vue

Bug/issue #, if applicable: 102032532
Fix sidebar content jump on mobile
NA
Steps:
1. Open the navigator on a mobile screen size
2. Assert it does not cause the content to lightly jump up

Fix navigator content jump on mobile

---

src/components/ImageAsset.vue
tests/unit/components/ImageAsset.spec.js

Bug/issue #, if applicable: 102035423
Fixes an error thrown in the console, from the ImageAsset, when navigating fast across pages.
NA
Steps:
1. Navigate fast across an archive with Images in the content, that do not have width attributes.
2. Assert the console no longer shows errors from `ImageAsset.vue` component

Fix error from image width calculation, when navigating fast across pages

---

src/App.vue
src/components/OnThisPageNav.vue
src/constants/AppTopID.js
src/mixins/onThisPageRegistrator.js
tests/unit/App.spec.js
tests/unit/components/OnThisPageNav.spec.js
tests/unit/mixins/__snapshots__/onThisPageRegistrator.spec.js.snap
tests/unit/mixins/onThisPageRegistrator.spec.js

Bug/issue #, if applicable: 102188459
Adds the page H1 Title to the OnThisPage items, as a first item, serving as a ScrollToTop.
NA
Steps:
1. Load any archive and assert the Title is added to the OnThisPage component and scrolls to top

Add the page title to the OnThisPageNav items

---

src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #101382072, if applicable: 
Hide Quick Navigation if IDE is being targeted
NA
Steps:
1. Add the following to `theme-settings.json` file at public folder
```json
{
"features": {
"docs": {
"quickNavigation": {
"enable": true
}
}
}
}
```
2. Run `export VUE_APP_TARGET='ide'`
3. Run `npm run serve`
4. Assert that quick navigation and navigator are not displayed

Make sure that Quick Navigation is hidden if IDE is being targeted

---

src/components/ContentNode.vue
src/components/ContentNode/Table.vue
src/components/DocumentationTopic/ContentNode.vue
src/components/Tabnav.vue
tests/unit/components/ContentNode.spec.js

Bug/issue #, if applicable: 101955529
Fixes issues with spacing out components like `img` or `code-listing`, when in around siblings.
This should make `img` wrapped in a `figure` consistently spaced out.
Also fixes some issues from nesting elements inside `/deep/`, which we did not spot before.
NA
[build.zip](https://github.com/apple/swift-docc-render/files/9938077/build.zip)
Steps:
1. Ensure the refactored elements are now properly spaced apart from siblings.
2. Ensure images with/without figure are properly spaced out. Even if inside rows/columns/tabnavs. You can use the archive attached above.

Fix issues with spacing of sibling components 

---

src/components/Navigator/QuickNavigationModal.vue

Bug/issue #, if applicable: 102424873
This fixes an issue where quick search struggles with searching on very large frameworks. This is due to some Vue internals, like accessing a computed property that returns a none-primitive on each iteration for the collections.
NA
Steps:
1. Load the app with a very large archive
2. Assert that searching for a very common word is as fast as searching for a less common one.

Fix performance issues with quick searching on very large collections

---

src/components/Navigator/NavigatorCard.vue
src/utils/navigatorData.js

Bug/issue #, if applicable: 102430474
Fixes performance degradations with large navigator trees, that have tens of thousands of nested items.
There are 4 main changes, that improved the speed:
Especially from within loops, accessing computed props often would cause Vue to track allot of internal dependencies.
This meant storing/providing computed props/state as local vars in functions, but drastically reduces the internal Vue.js dependency tracking.
This further reduces the reacting dependency tracking, as frozen objects are not tracked internally.
In order to improve pure JS looping speed, I had to use `for` loops. `reduce` `filter` and `map` offer more readability but are generally multiple times slower. That combined with `Object.entries` on large objects and we end up with unnecessary …

Optimize the Navigator searching for large indexes

---

src/components/OnThisPageNav.vue
tests/unit/components/OnThisPageNav.spec.js

Bug/issue #, if applicable: 102897555
With the addition of page titles to the OnThisPage, there are cases where the title is just too long and requires a new line break. This PR adds that break.
NA
Use an archive that has very long page titles. Assert those dont go beyond the OnThisPageNav width.

Fix long titles for OnThisPageNav

---

src/components/DocumentationTopic/OnThisPageStickyContainer.vue

Bug/issue #, if applicable: 102988118
Fixes potential issues with the OnThisPage nav being too long and not being scrollable
NA
Steps:
1. Load a page with many headings and content
2. Assert that the OnThisPageNav can be scrolled to see all items

Fix issue with very long onThisPageNav instances

---

src/components/ImageAsset.vue
src/constants/ImageLoadingStrategy.js
src/mixins/onPageLoadScrollToFragment.js
src/stores/AppStore.js
tests/unit/components/Asset.spec.js
tests/unit/components/ImageAsset.spec.js
tests/unit/components/OverridableAsset.spec.js
tests/unit/mixins/onPageLoadScrollToFragment.spec.js

Bug/issue #, if applicable: 102985056
There may be times when a user clicks a link to a subsection of another page and isn't scrolled to the appropriate place—this issue is most likely happening more often on uncached, content heavy pages, especially with many and/or large images since the height of the images may be impacting the scroll location before they have fully loaded.
These 2 explicit changes were made to make sure that scrolling consistently goes to the right place in every scenario:
* Updated the `onpageLoadScrollToFragment` mixin so that the logic is also called in the `updated` hook and not just the `mounted` one. This is needed since following a link to a subsection of one documentation page from another actually updates the main component instead of remounting a new one
* …

Ensure user always scrolls to the right place when linking to subsections of pages

---

src/components/ContentNode/Table.vue

Bug/issue #, if applicable: 103365463
Fixes issues with table spacing introduced in #478
NA
Assert that elements after tables are properly spaced out properly

Fix table spacing between elements

---

src/components/Navigator/QuickNavigationModal.vue
tests/unit/components/Navigator/QuickNavigationModal.spec.js

Bug/issue #489, if applicable: 
When an author curates the documentation symbols these might appear repeated times in the index, even if they have different UIDs conceptually they are the same, so when filtering symbols on quick navigation we have to check path uniqueness and remove the duplicates.
In this PR I tweaked the `filteredSymbols` computed property to filter symbols by path uniqueness, removing the duplicates from the results
N/A
_Describe how a reviewer can test the functionality of your PR. Provide test content to test with if
applicable._
Steps:
1. Turn on the feature flag for Quick Navigation
2. Assert that symbols with the same path appear once on Quick Navigation results

Bugfix: Remove repeated symbols from QN search results

---

src/components/DocumentationTopic.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 103149476
The minimized view should not display the following items:
1. Title and eyebrow
2. Language Switcher
3. Availability
5. Topics section
6. Default Implementations
7. Relationships
8. See Also
Steps:
1. Test with this DocC Archive: 
[SlothCreator_Minimized_View.doccarchive.zip](https://github.com/apple/swift-docc-render/files/10240143/SlothCreator_Minimized_View.doccarchive.zip)

Minimized view should display less content 

---

tests/unit/components/Navigator/QuickNavigationModal.spec.js

Bug/issue #103533986, if applicable:
Fix warning: [Vue warn]: Invalid prop: type check failed for prop "type". Expected String, got Undefined 
when running tests
NA
Steps:
1. Run `npm run test`
2. Assert no warnings are displayed

Fix warning when running tests

---

src/utils/syntax-highlight.js
tests/unit/utils/syntax-highlight.spec.js

Bug/issue #, if applicable: 103087953
Fixes an issue where empty new lines are not rendered properly.
NA
[codesample.json.zip](https://github.com/apple/swift-docc-render/files/10277532/codesample.json.zip)
Using the example JSON above, try to copy the text into your editor.
1. Assert there is a single new line when you paste
2. Assert this works across browsers
3. Assert it does not regress

Fix issues with new lines not rendering, when multiline blocks are used

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: #503
`DeclarationSource`, when formatting for multi-param symbols, incorrectly identifies the last closing parenthesis of the entire declaration, rather than the closing parenthesis for the first opening parenthesis in the declaration.
To fix, we only set closing parenthesis index when it is previously `null`.
1. Define a public structure/object that has a method which returns a tuple, i.e:
```swift
public struct DeclarationIndentationBug<A, B> {
public static func foo(
_ a: A,
_ b: B
) -> (A, B) {
return (a, b)
}
}
```
2. Build a `.doccarchive`
3. Render the `.doccarchive` using `swift-docc-render`
| Before | After |
| --- | --- |
|<img alt="Before" src="https://user-images.githubusercontent.com/3253505/209383331-b203d52c-66f0-478c-a556-3bad73841afa.png">|<img …

Fix `DeclarationSource` inserts newline at incorrect close parenthesis

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/NavBase.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #103256123, if applicable: 
1) Localnav without navigator should take up full space.
2) Localnav without navigator on mobile viewport should be correct without toggle button
NA
Steps:
1. Run a doccarchive without navigator
2. Assert that localnav takes full space

Localnav without navigator should take up full space.

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic/DocumentationNav.spec.js
tests/unit/components/NavBase.spec.js
tests/unit/views/DocumentationTopic.spec.js

- **Explanation:** Localnav without navigator should take up full space
- **Scope:** Only users who have navigator disabled
- **Issue:** (rdar://103256123)
- **Risk:** Small potential for UI regressions in the navigator
- **Testing:** Manual testing since changes affect the UI only
- **Reviewer:** @mportiz08 @dobromir-hristov
- **Original PR:** #499

[5.8] Localnav without navigator should take up full space.

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

- **Explanation:** Fixes bug where whitespace formatting of Swift multi-param functions returning tuple types does not look right
- **Scope:** Small JS change that improves small subset of Swift symbol pages
- **Issue:** #503 (rdar://103841947)
- **Risk:** Small potential for regressions of Swift declaration whitespace formatting
- **Testing:** Added unit test and visually inspected formatting of Swift symbol declarations, verified that multi-param functions with tuple return types look to be improved and no obvious regressions for other symbols
- **Original PR:** #504

[5.8] Fix whitespace formatting of multi-param Swift functions that return tuples

---

src/components/DocumentationTopic.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/views/DocumentationTopic.spec.js

- **Explanation:** Removing unneeded content originally displayed for documentation pages for minimized mode
- **Scope:** Small changes made to conditionally display content on the documentation page.
- **Issue:** rdar://103149476
- **Risk:** Small risk for regressions of contents displayed on Documentation pages
- **Testing:** Tested for regressions via existing unit tests, added new unit tests for the minimized mode.
- **Original PR:** #498

[5.8] Minimized mode should display less content

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/styles/base/_typography.scss
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js

Bug/issue #, if applicable: 103150108
This PR covers some style updates for minimized.
Steps:
1. Manually verify that the following items are achieved when the prop `enableMinimized` is set to true:
- Use "Summary" as the heading for abstracts
- Remove extra padding at the bottom of hero section
2. Verify that we now allow browsers to set the default font size when the target is IDE (Here's the [Draft PR](https://github.com/apple/swift-docc-render/pull/500) from earlier)

`Minimized` style updates

---

src/components/Filter/FilterInput.vue
src/components/Navigator/QuickNavigationModal.vue
tests/unit/components/Filter/FilterInput.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js

Bug/issue #490, if applicable: 
With this implementation, the input text is automatically selected to overwrite it with a new query when reopening Quick Navigation after a previous search.
N/A
_Describe how a reviewer can test the functionality of your PR. Provide test content to test with if
applicable._
Steps:
1. Turn on the feature flag for Quick Navigation
2. Open the Quick Navigation search bar, type a query, and proceed to close it again
3. Open Quick Navigation and assert that the input text is selected

Select input text when opening Quick Navigation

---

src/components/ContentNode/CodeListing.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue

Bug/issue #, if applicable: 104043983
This fixes an issue In Safari where the browser scrollbar UI is not being visually clipped by rounded borders of code listings. 
By default, code listings don't have a round enough border for this problem to be observed, but it could present itself with an updated theme with a larger border radius for these elements.
Before:
After:
Steps:
1. Configure the global macOS setting as follows ` / System Settings... / Appearance / Show scroll bars` to `"Always"`
2. Run `env VUE_APP_DEV_SERVER_PROXY=https://mportiz08.github.io/swift-docc npm run serve` or run this branch with any other example content
3. Increase the default border-radii settings for testing purposes. A quick/easy way is to open the inspector and click the `<body>` element—then you can …

Ensure scrollbar is visually clipped by code listings with round borders in Safari

---

src/components/ContentNode/CodeListing.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue

- **Explanation:** Fixes bug where native scrollbar UI may extend beyond rounded corners of code listings in Safari
- **Scope:** Safari only, only impacts themes with more rounded corners of code listings, small/focused CSS only fix
- **Issue:** rdar://104043983
- **Risk:** Small potential for regression in visual of code listings that scroll
- **Testing:** Visual inspection to ensure scrollbar UI is contained in declarations and code listings, tested various code listings for any regressions.
- **Original PR:** #514

[5.8] Ensure scrollbar is visually clipped by code listings with round borders in Safari

---

src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue

Bug/issue #, if applicable: 104194977
In the latest Safari Technology Preview, the language toggle is not being re-sized as expected when toggling between languages.
This seems to be an issue with the combination of this new browser and Vue where an invisible HTML `<option>` element is not being properly updated like it should when the toggle is used. Adding a `key` attribute fixes this, because it forces Vue to not attempt to re-use the same element for unique language choices.
With the option element updating properly, the appropriate size for the dropdown can be calculated, and the visual issue is resolved.
Requirements:
1. Find content that supports both Swift and Objective-C
2. Download the latest [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) so …

Fix issue with calculating language toggle width in Safari Tech Preview

---

src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue

- **Explanation:** Fixes bug where language toggle does not resize properly in preview versions of Safari.
- **Scope:** Safari Tech Preview only, minor Vue/HTML markup change that only impacts pages that support Swift/Objective-C when toggling
- **Issue:** rdar://104194977
- **Risk:** May impact the visual appearance of the language toggle
- **Testing:** Visual inspection in various browsers, including the problematic scenario with Safari Technology Preview
- **Original PR:** #517

[5.8] Fix Safari bug with language toggle width

---

src/views/DocumentationTopic.vue

Bug/issue #, if applicable:  N/A
Introduce quick navigation as a default feature in docc-render by defaulting `getSetting` for the `enableQuickNavigation` function to true, still working as a customization point through a theme settings file.
N/A
Steps:
1. Render any archive without a theme file
2. Assert that Quick Navigation is enabled

Quick Navigation default enablement

---

src/views/DocumentationTopic.vue

- **Explanation:** Introduce quick navigation as a default feature in docc-render by defaulting `getSetting` for the `enableQuickNavigation` function to true, still working as a customization point through a theme settings file (https://forums.swift.org/t/quick-navigation-enablement-request/62523)
- **Scope:** New feature for all docs
- **Issue:** N/A
- **Risk:** 
- **Testing:** Render any archive without a theme file and assert that Quick Navigation is enabled
- **Reviewer:** @franklinsch 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/518

[5.8] Quick Navigation default enablement 

---

src/components/DocumentationTopic/PrimaryContent/ParametersTable.vue

Bug/issue #, if applicable: 103421001
Ensures columns inside the ParametersTable have the same width, even if wrapped in a `changes` class.
NA
Steps:
1. Ensure that adding a `changes` class to the `row` does not affect the width of the columns.

Make sure ParametersTable with changes has equal width columns

---

src/components/ContentNode.vue
tests/unit/components/ContentNode.spec.js

Bug/issue #, if applicable: 101369883
Bumps the TabNavigator vertical threshold to 7, as 5 was still able to fit horizontally. 
NA
Steps:
1. Test with a tabnav that has 8 tabs to go into vertical

bump TabNavigator vertical threshold to 7

---

src/components/DocumentationTopic/PrimaryContent/ParametersTable.vue

- Explanation: Ensures columns inside the ParametersTable have the same width, even if wrapped in a `changes` class.
- Scope: API changes visuals on ParameterTables in Doc pages
- Issue: rdar://103421001
- Risk: May impact the visual appearance of the ParametersTable
- Testing: visual inspection of pages with ParametersTable that have changes.
- Reviewer: @mportiz08 
- Original PR: https://github.com/apple/swift-docc-render/pull/521

[5.8] Make sure ParametersTable with changes has equal width columns

---

src/components/Asset.vue
src/components/ConditionalWrapper.vue
src/components/ContentNode.vue
src/components/ContentNode/BlockVideo.vue
src/components/ContentNode/DeviceFrame.vue
src/components/ReplayableVideoAsset.vue
src/components/VideoAsset.vue
src/constants/DeviceFrames.js
tests/unit/components/Asset.spec.js
tests/unit/components/ConditionalWrapper.spec.js
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/BlockVideo.spec.js
tests/unit/components/ContentNode/DeviceFrame.spec.js
tests/unit/components/ReplayableVideoAsset.spec.js
tests/unit/components/VideoAsset.spec.js

Bug/issue #, if applicable: 102182966
Adds support for DeviceFrames for images and videos. This PR re-adds #515 
- https://github.com/apple/swift-docc/pull/462
[simpler.json.zip](https://github.com/apple/swift-docc-render/files/10400403/simpler.json.zip) - this file is built with the docc branch above
Steps:
1. To test this you will need an archive that has `@Image` or `@Video` tags with `deviceFrames`.
2. You will also need to add deviceFrame definitions to your `theme-settings.json` file, as by default docc-render does not ship with frames. - see https://forums.swift.org/t/support-for-device-frames/62151 for more info

Add DeviceFrames support

---

CONTRIBUTING.md
README.md

Bug/issue #, if applicable: None
This PR adds a blurb to the README and CONTRIBUTING.md files about using `nvm` to handle installing Node and npm. Since Swift-DocC-Render has an `.nvmrc` file, this provides a quick way to ensure that you have the right versions of Node/npm before working on the project itself.
None
- [ n/a ] Added tests

add docs about using nvm to readme and contributing.md

---

src/components/DocumentationTopic.vue

Bug/issue #, if applicable: rdar://88423841
Adjust padding for minimized Asides to be smaller and scale to body font 
Steps:
1. Manually verify by navigating to a page with aside (ex. Deprecated Summary or Note)

Adjust padding for minimized Asides

---

src/components/ContentNode/CodeListing.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue

Bug/issue #, if applicable: 104872474
Fixes a page printing bug where code-listings where generated without code, or gradient overlays.
NA
Steps:
1. Try to print a page with a code listing

Fix printing pages with code-listings

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 104976416
Shrink minimized mode border radius for Declaration, Code Listing, and Aside
Also did a slight refactor for CSS rules for minimized mode
Steps:
1. Manually verify by navigating to any page with declaration, code listing, and aside.

Shrink minimized mode border radius for Declaration, Code Listing, and Aside

---

src/components/ContentNode/TabNavigator.vue
src/components/ImageAsset.vue
tests/unit/components/ContentNode/TabNavigator.spec.js
tests/unit/components/ImageAsset.spec.js

Bug/issue #, if applicable: 105363672
This fixes a bug where images are not rendered inside tabnavs, for Safari only.
This only happens if the image is a `display: block`, and has some element before it. Really strange, but removing the `loading: lazy` fixes it.
NA
Compile and try with this:
```md
@TabNavigator{
@Tab("Image With Title"){
**Strong Title**
@Image(source: example.png)
}
@Tab("Image with Caption"){
@Image(source: example.png){ Some text as a placeholder }
}
}
```

Fix issue with images not rendered inside a tabnav, in Safari

---

package-lock.json
package.json
src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 105885210
Ensures items get their size properly updated, when clicking around the navigator. This prevents items that grew larger, to stay large if not needed anymore.
NA
Ensure items stay the correct size, like when being bolded.

Update items size when clicking around navigator

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 100278813
Allows hiding any available tags in the NavigatorCard search
NA
To test this you would need to extend the NavigatorCard and apply the `hideAvailableTags: true` prop.
Assert no tags are shown, no matter what navigator items you have.

Allow hiding available tags in NavigatorCard.vue

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 106166386
Fix the issue where view more link is not displayed when there's no Primary Content
NA
Steps:
1.  Turn on Navigation Preview feature
2. Test with a page with no primary content

Fix View more link when there's no Primary Content

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 106383020 
Fix documentation page fails to load in minimized route for objc only pages
Load an objc only page in minimized mode

Fix documentation page fails to load in minimized route for objc only pages

---

src/components/Footer.vue
src/components/LocaleSelector.vue
src/components/Navigator/NavigatorDataProvider.vue
src/lang/locales.json
src/utils/data.js
src/utils/i18n-utils.js
src/utils/metadata.js
src/views/DocumentationTopic.vue
tests/unit/components/LocaleSelector.spec.js
tests/unit/components/Navigator/NavigatorDataProvider.spec.js
tests/unit/utils/data.spec.js
tests/unit/utils/i18n-utils.spec.js
tests/unit/utils/metadata.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #106158283, if applicable: 
Refactor for i18n utils and LocaleSelector
NA
Steps:
1. Add the following to `theme-settings.json` file at public folder
```json
{
"features": {
"docs": {
"i18n": {
"enable": true
}
}
}
}
```
3. Run `npm run serve`
2. Go to the bottom of the page and change the language in the locale selector
3. Assert that everything works properly

Refactor for i18n utils and LocaleSelector

---

src/components/DocumentationTopic.vue

Bug/issue #, if applicable: 106656319
Shrink font size of h1 in Primary Content in minimized mode

Shrink font size of h1 in Primary Content in minimized mode

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/PrimaryContent.vue

Bug/issue #, if applicable: 105804332
For historical reasons, we never needed to bother with explicit font-styles for h1 and h2 headings in authored content. This updates h1 and h2 headings in article/symbol content to use the same font-style that we use elsewhere on the same page for these elements instead of relying on the browser default styles.
Test content with custom h1 and h2 headings in an article or symbol page. Verify that the h1 font style matches the page title style and that the h2 font style matches the overview font style.

Add explicit font-styles for h1/h2 in doc content

---

src/components/DocumentationTopic/TopicsLinkCardGridItem.vue

Bug/issue #, if applicable: 106864428
Set a hard aspect ratio size of 16/9 to the cards in LinksBlock grid sections.
NA
Load an archive that has LinkBlock of type `compactGrid` and `detailedGrid`, and ensure that the generated cards are always 16/9 size.

Ensure topicLinkCard items are always 16/9 aspect ratio

---

SwiftDocCRender.docc/contributing/Internals.md
src/setup-utils/vue-config-utils.js
src/utils/syntax-highlight.js

Bug/issue #, if applicable: N/A
In some cases, documentation may use codeblocks with languages other than those enabled by default in `swift-docc-render`. In our case, we want to include Elixir codeblocks in the [LiveViewNative](https://github.com/liveview-native/liveview-client-swiftui) docs.
This PR makes it possible to build with a custom set of supported languages which are added to the default set with an environment variable:
```sh
VUE_APP_HLJS_LANGUAGES=elixir npm run build
```
Multiple languages can be added with a comma-separated list:
```sh
VUE_APP_HLJS_LANGUAGES=elixir,haskell npm run build
```
Now codeblocks for Elixir are properly highlighted!
I used webpack's `ContextReplacementPlugin` to ensure only the necessary languages are included in the bundle. This replaces the …

Make highlight.js languages user-configurable

---

src/stores/AppStore.js
tests/unit/stores/AppStore.spec.js

Bug/issue #, if applicable: rdar://107320467
Images should be allowed to eagerly load by default in IDE mode.

Images can eagerly load in IDE mode

---

src/components/DocumentationTopic/ViewMore.vue

Bug/issue #, if applicable: rdar://107077994
Match the `ViewMore` link font size with the `Declared in` link.
Steps:
1. Manually verify in minimized views

Reduce `ViewMore` link font size

---

src/stores/AppStore.js
tests/unit/stores/AppStore.spec.js

- Explanation: Allow images to eagerly load in IDE mode
- Scope: IDE mode only
- Issue: rdar://106656319
- Risk: Small
- Testing: Test in IDE mode
- Reviewer: @mportiz08 @dobromir-hristov 
- Original PR: https://github.com/apple/swift-docc-render/pull/560

[5.9] Images can eagerly load in IDE mode

---

src/components/DocumentationTopic/PrimaryContent/ParametersTable.vue

- Explanation: Fix a spacing issue with ParametersTable and API changes
- Scope: Doc pages
- Issue: rdar://103421001
- Risk: Small
- Testing: Test doc pages that have Parameter Table sections and API changes in them.
- Original PR: https://github.com/apple/swift-docc-render/pull/540

[5.9] fix spacing issue with api changes and ParametersTable

---

src/components/DocumentationTopic/TopicsLinkCardGridItem.vue

- Explanation: Sets the card items in Links component to 16/9 aspect ratio
- Scope: Doc pages with `@Links` component
- Issue: rdar://106864428
- Risk: Small, css only
- Testing: Test pages that have `@Links` components and the `grid` or `detailedGrid` type
- Original PR: https://github.com/apple/swift-docc-render/pull/553

[5.9] ensure Links card items are always 16/9 aspect ratio

---

src/components/Card.vue
src/components/CardCover.vue
src/components/OverridableAsset.vue
tests/unit/components/Card.spec.js
tests/unit/components/CardCover.spec.js
tests/unit/components/OverridableAsset.spec.js

- Explanation: Renders the `alt` text on overridden assets
- Scope: Doc pages with asset overrides in the Navigator or `@Links` via `@PageImage`
- Issue: rdar://106633366
- Risk: Small
- Testing: Assert `alt` text provided to `@PageImage` tag is rendered where necessary.
- Reviewer: @marinaaisa 
- Original PR: https://github.com/apple/swift-docc-render/pull/548

[5.9] Provide alt text to overridable assets

---

src/components/ContentNode/Row.vue
src/components/DocumentationTopic/TopicsLinkCardGridItem.vue
src/styles/core/colors/_dark.scss
src/styles/core/colors/_light.scss

- Explanation: Adds a very faint border to the cards in @links directive. Adds extra space around the Row component
- Scope: Doc pages
- Issue: rdar://107269619
- Risk: Small, css only
- Testing: Visually assert styling is applied.
- Reviewer: @hqhhuang 
- Original PR: https://github.com/apple/swift-docc-render/pull/558

[5.9] minor styling fixes to spacing and colors

---

src/components/DocumentationTopic/ViewMore.vue

- Explanation: Reduce font size for the “view more” link 
- Scope: minimized mode only, minor CSS change
- Issue: rdar://107077994
- Risk: Small
- Testing: Verify link font size in Quick Nav preview
- Reviewer: @mportiz08  
- Original PR: https://github.com/apple/swift-docc-render/pull/561

[5.9] Reduce ViewMore Link font

---

src/components/ContentNode/CodeListing.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
src/components/Tutorial/Step.vue
src/styles/core/_helpers.scss

Bug/issue #, if applicable: 104872474
This extracts and modifies the existing functionality needed to establish a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) without altering any visuals, which is used in various places to work around browser specific issues related to overflow and border-radii.
The [previous method](https://github.com/apple/swift-docc-render/pull/514) has issues with the "Export as PDF" feature of Safari, possibly because of the way it handles transparent background images for that kind of rendering output, and it cannot be avoided with media queries the same way that it can when "printing" to PDF.
Follow the same testing steps as https://github.com/apple/swift-docc-render/pull/514 …

Extract helper for establishing a new stacking context

---

src/utils/router-utils.js
tests/unit/utils/router-utils.spec.js

- Explanation: Prevent scroller from scrolling during the navigation event if setting is turned on
- Scope: routes with the `preventScrolling` set to `true`
- Issue: rdar://103146273
- Risk: Small
- Testing: add `preventScrolling` to the `meta` field for routes, set it to `true` and test with emitting `navigation` event.
- Reviewer: @dobromir-hristov 
- Original PR: https://github.com/apple/swift-docc-render/pull/563

[5.9] Prevent scrolling if router `meta` field `preventScrolling` is `true`

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

- Explanation:  Conditionally hide the “ViewMore” link
- Scope: Minimized mode only
- Issue: rdar://106860554
- Risk: Small
- Testing: 
1. Manually add hasNoExpandedDocumentation to the metadata field of a renderJSON, and set it to true.
2. Test in Quick Nav that the link is hidden.
- Reviewer: @dobromir-hristov 
- Original PR: https://github.com/apple/swift-docc-render/pull/562

[5.9] hide view more link if no expanded documentation (#562)

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

Bug/issue #, if applicable: 107581728
Stops removing the color from the intro section based on the topicSectionsStyle
NA
Steps:
1. Render a page using the topicSectionsStyle that is either a `grid` or `detailedGrid`
2. Assert the intro section is still colored for pages that support it.

Remove the topicSectionsStyle limitation for the doc intro section

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue

Bug/issue #, if applicable: 107692636
Removes a top-padding from the nav that we are only conditionally removing anyway.
It was probably left from one of the recent refactors @marinaaisa did to clean the nav up.
NA
Assert there are no visual regressions in the nav on any of our page types.

refactor: remove unnecessary top padding

---

src/App.vue
src/components/Footer.vue
src/lang/index.js
tests/unit/App.spec.js
tests/unit/components/Footer.spec.js

Bug/issue #107566850, if applicable: 
Refactor: enablei18n centralized in App.vue
NA
Steps:
1. Check that enablei18n feature flag works as expected

Refactor: enablei18n centralized in App.vue

---

src/components/Icons/PauseIcon.vue
src/components/ReplayableVideoAsset.vue
src/lang/locales/en-US.json
tests/unit/components/ReplayableVideoAsset.spec.js

- Explanation: Allow pausing a video while its playing
- Scope: All places the video tag is used (docs, tutorials)
- Issue: rdar://107269394
- Risk: Medium
- Testing: Assert videos can be paused and resumed. Assert there is no no regression in visuals and functionality 
- Reviewer: @marinaaisa 
- Original PR: https://github.com/apple/swift-docc-render/pull/559

[5.9] Add a Pause state to the ReplayableVideoAsset

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

- Explanation: Stops removing the color from the intro section based on the `@TopicsVisualStyle`
- Scope: Doc hero section
- Issue: rdar://107581728
- Risk: Small
- Testing: Assert pages that use `@TopicsVisualStyle` directive still can render a colored Intro section.
- Reviewer: @SamLanier @hqhhuang 
- Original PR: https://github.com/apple/swift-docc-render/pull/581

[5.9] Remove the topicSectionsStyle limitation for the doc intro section

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue

- Explanation: Removes an unnecessary top padding from the nav bar that we are removing everywhere anyway.
- Scope: All pages
- Issue: rdar://107692636
- Risk: Small
- Testing: There should be no visual change in doc and tutorial pages
- Reviewer: @marinaaisa @SamLanier 
- Original PR: https://github.com/apple/swift-docc-render/pull/583

[5.9] Remove unnecessary top padding in navigation bar

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/components/TopicTypeIcon.vue
src/constants/StandardColors.js
src/styles/core/colors/_light.scss
tests/unit/components/DocumentationTopic/DocumentationHero.spec.js
tests/unit/components/TopicTypeIcon.spec.js

- Explanation: Adds support to the new `@PageColor` directive
- Scope: Doc pages
- Issue: rdar://107241548
- Risk: Small
- Testing: Assert Doc pages can change the Intro section color, specified in `@PageColor` directive.
- Reviewer: @mportiz08 @SamLanier 
- Original PR: https://github.com/apple/swift-docc-render/pull/582

[5.9] Allow customising the Intro section via `@PageColor` directive

---

src/App.vue
src/components/Footer.vue
src/lang/index.js
tests/unit/App.spec.js
tests/unit/components/Footer.spec.js

- Explanation: Refactor: enablei18n centralized in App.vue
- Scope: All code blocks
- Issue: rdar://107566850
- Risk: Small
- Testing: Make sure everything works as expected
- Reviewer: @dobromir-hristov 
- Original PR: https://github.com/apple/swift-docc-render/pull/584

[5.9] Refactor: enablei18n centralized in App.vue 

---

src/components/Navigator/QuickNavigationModal.vue
src/views/DocumentationTopic.vue
tests/unit/components/Navigator/QuickNavigationModal.spec.js

Bug/issue #, if applicable: NA
Removes the feature flag for the quicknav preview functionality and enables it by default.
Verify that the quicknav preview features, even without theme-settings file.

Remove feature flag for quicknav preview

---

src/components/ContentNode/TabNavigator.vue
tests/unit/components/ContentNode/TabNavigator.spec.js

- Explanation: Added logic to select tabs when new tabs are added / removed
- Scope: TabNavigator component only
- Issue: rdar://108013117
- Risk: Low
- Testing:
1. All unit tests should still pass.
2. Verify that for documentation pages using TabNavs, this change doesn’t introduce regression
- Reviewer: @mportiz08 @dobromir-hristov @marinaaisa 
- Original PR: https://github.com/apple/swift-docc-render/pull/601

[5.9] Set tabnav to the tab with latest title update

---

src/components/ContentNode/TabNavigator.vue
tests/unit/components/ContentNode/TabNavigator.spec.js

Bug/issue #, if applicable: 108013117
We should set the current tab of TabNav to the tab that just got added or just had its title updated.

Set tabnav to the tab with latest title update

---

src/components/Navigator/QuickNavigationModal.vue
src/views/DocumentationTopic.vue
tests/unit/components/Navigator/QuickNavigationModal.spec.js

- **Explanation:** Removes feature flag for Quick Navigation preview functionality
- **Scope:** Small JS conditional logic change
- **Issue:** rdar://108375829
- **Risk:** Low, minor conditional logic changes
- **Testing:** Updated unit tests and manually verified that the feature is now enabled by default.
- **Original PR:** #602

[5.9] Remove feature flag for quicknav preview

---

src/components/DocumentationTopic.vue
src/components/DocumentationTopic/DocumentationHero.vue
src/styles/base/_reset.scss
src/styles/core/_breakpoints.scss

- Explanation: Remove breakpoint in Minimized mode & updated padding
- Scope: Minimized mode in Quick Nav
- Issue: rdar://108391432
- Risk: Low
- Testing: Ensure there's no regression in Quick Nav and the padding is updated.
- Original PR: https://github.com/apple/swift-docc-render/pull/610

[5.9] Remove breakpoint in Minimized mode & update padding

---

src/components/Navigator/QuickNavigationPreview.vue
tests/unit/components/Navigator/QuickNavigationPreview.spec.js

Bug/issue #, if applicable: 108479392
Fixes the QuickNav preview references by providing its own clone of the DocTopic store.
NA
Assert the QuickNav Preview works as expected, and links + images are properly rendered.

Fix quick nav preview references

---

src/components/Navigator/QuickNavigationPreview.vue
tests/unit/components/Navigator/QuickNavigationPreview.spec.js

- Explanation: Fixes the QuickNav preview references by providing its own clone of the DocTopic store.
- Scope: Quick Nav
- Issue: rdar://108479392
- Risk: Low
- Testing:
1. Assert that QuickNav Preview properly renders images and links when navigating up/down the search results.
- Reviewer: @mportiz08 
- Original PR: https://github.com/apple/swift-docc-render/pull/612

[5.9] Fix quick nav preview references

---

src/components/AdjustableSidebarWidth.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

- **Explanation:** Fixes an edge case where on Safari, the navigator search bar gets cutoff
- **Scope:** Navigator
- **Issue:** rdar://108279303
- **Original PR:** #599

[5.9] fix stale AdjustableSidebarWidth transitioning state

---

src/components/DocumentationTopic/TopicLinkBlockIcon.vue
tests/unit/components/DocumentationTopic/TopicLinkBlockIcon.spec.js

- **Explanation:** Adds an icon for top-level collections curated in Topics section.
- **Scope:** Minor JS change to add mapping for the icon
- **Issue:** rdar://107729097
- **Original PR:** #615

[5.9] Use technology icon for collections in Topics section

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: 108412440
Updates the formatting logic for Swift declarations to break each [attribute][1] onto its own line.
Example:
```swift
// before
@discardableResult @objc(baz) func foobarbaz() -> Int
// after
@discardableResult
@objc(baz)
func foobarbaz() -> Int
```
\cc @ethan-kusters 
Steps:
1. Configure [swift-docc-plugin][2] for a new or existing swift package that has examples of Swift symbols with attributes
2. Build this branch and note the location of `dist`
3. Run `DOCC_HTML_DIR=/path/to/dist swift package --disable-sandbox preview-documentation --target [target]` to preview it and verify that the symbols now have each attribute on its own line.
Here is an example package (target `AttributeExamples`) for convenience: …

Improve swift attribute formatting

---

src/components/Navigator/NavigatorCardItem.vue
src/lang/locales/ja-JP.json
src/lang/locales/zh-CN.json
tests/unit/components/Navigator/NavigatorCardItem.spec.js

- **Explanation:** Refactor ariaDescribedBy computed property in NavigatorCardItem to provide a better i18n and AX experience
- **Scope:** Navigator
- **Issue:** rdar://105598877
- **Original PR:** https://github.com/apple/swift-docc-render/pull/593

[5.9] Refactor ariaDescribedBy computed property in NavigatorCardItem to provide a better i18n and AX experience

---

src/styles/base/_reset.scss
src/styles/core/_breakpoints.scss

Bug/issue #, if applicable: rdar://108569652
Restore breakpoint for small quick nav windows, which sets the proper min-width when the window is narrow.
Manual testing

Restore breakpoint for small quick nav windows

---

src/components/DocumentationTopic/ViewMore.vue

Bug/issue #, if applicable: rdar://108577661
Minimized mode bottom margin should scale as font size increase & match the side padding.

Minimized mode bottom margin should match side padding

---

src/components/ContentNode/TabNavigator.vue
tests/unit/components/ContentNode/TabNavigator.spec.js

Bug/issue #, if applicable: 108379797
Changes the TabNav content rendering to be v-show based, so images can be pre-loaded and wont flash when changing tabs.
NA
1. Load an archive with a tabnav that has mostly images
2. Assert images no longer flash when changing active tab

Change the tab-nav rendering to be v-show based

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

- **Explanation:** Improves Swift declaration formatting by rendering each attribute on its own line
- **Scope:** Small targeted JS change that runs for every Swift decl
- **Issue:** rdar://108412440
- **Risk:** Medium, small change but impacts all Swift decls
- **Testing:** Added unit tests and manually tested various kinds of declarations with attributes to look for any obvious regressions in formatting
- **Original PR:** #618

[5.9] Improve swift attribute formatting

---

src/styles/base/_reset.scss
src/styles/core/_breakpoints.scss

- **Explanation:** Fixes regression where Quick Nav content is cut off when window is small
- **Scope:** Quick Nav only
- **Issue:** rdar://108569652
- **Reviewer:** @mportiz08  
- **Original PR:** #619

[5.9] Restore breakpoint for small quick nav windows

---

src/components/DocumentationTopic/ViewMore.vue

- **Explanation:** Quick Nav bottom margin should also increase when font size increases
- **Scope:** Quick Nav only
- **Issue:** rdar://108577661
- **Reviewer:** @mportiz08  
- **Original PR:** #617

[5.9] Minimized mode bottom margin should match side padding

---

src/App.vue

- **Explanation:** VO should not pick up “Skip Navigation” in IDE
- **Scope:** IDE mode only
- **Issue:** rdar://108634054
- **Reviewer:** @dobromir-hristov @marinaaisa 
- **Original PR:** #622

[5.9] Disable `skip-nav` VO link in IDE 

---

src/components/ContentNode/TabNavigator.vue
tests/unit/components/ContentNode/TabNavigator.spec.js

- **Explanation:** Fixes the issue where images in TabNav does not load fast enough and causes a jump
- **Scope:** TabNav only
- **Issue:** rdar://108379797
- **Reviewer:** @hqhhuang (original PR authored by Dobri) 
- **Original PR:** #613

[5.9] Change the tab-nav rendering to be v-show based

---

src/components/DocumentationTopic/PrimaryContent/Declaration.vue

Bug/issue #, if applicable: 105460303
Reduces the space between Declaration and the conditional constraint to 20px from 30px.
NA
Assert the space is correct

Reduce the Declaration conditional constraint spacing to 20px

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: 108798969
This changes the behavior introduced with #618 to render all attributes on a single line as opposed to each one getting its own line.
Example:
```swift
// before
@discardableResult @objc(baz) func foobarbaz() -> Int
// after
@discardableResult @objc(baz)
func foobarbaz() -> Int
```
Same testing instructions as #618 but verify that attributes are now all on one line as opposed to each getting their own line.

Render all attributes for Swift symbol declarations on a single line

---

src/components/DocumentationTopic/PrimaryContent/DeclarationToken.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationToken/LinkableToken.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken/LinkableToken.spec.js

Bug/issue #, if applicable: 108472125
This adds support for rendering certain attribute tokens as links to symbols instead of just plaintext.
As a basic example, DocC would generate a linkable `@StringBuilder` token in the contrived `buildABC` function here:
```swift
@resultBuilder
public struct StringBuilder {
static func buildBlock(_ parts: String...) -> String {
parts.joined(separator: "\n")
}
}
@StringBuilder public func buildABC() -> String {
"a"
"b"
"c"
}
```
https://github.com/apple/swift/pull/63637
To test this using swift-docc-plugin, you may need a recent 5.9 toolchain version of Swift to ensure that the symbol graph tokens get generated with the data for linking (see above dependency).
Steps:
1. Build this branch with `npm run build`
2. Preview docs for an example package that …

Support linkable attribute tokens

---

src/components/Navigator/QuickNavigationModal.vue
src/utils/scroll-lock.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js
tests/unit/utils/scroll-lock.spec.js

Bug/issue #, if applicable: 108269711
Fixes the QuickNav Preview scrolling issue on iPad, by adding exclusion zones to the scroll-locking.
This should be carefully merged with #634 
NA
1. Open the app on iPad and then toggle QuickNav
2. Search for something vague, so you can see a scroll area for the content and suggestions
3. Assert you can scroll both while the background is still not scrollable.

Fix QuickNav Preview scrolling issue on iOS mobile device

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: 108472125
Fixes issue where parameters that start with attributes are not properly indented onto the next line like ones without attributes are.
Before:
```swift
// func qux(a: String, b: String, @StringBuilder c: () -> String) 
func qux(
a: String,
b: String, @StringBuilder c: () -> String
)
```
After:
```swift
// func qux(a: String, b: String, @StringBuilder c: () -> String)
func qux(
a: String,
b: String,
@StringBuilder c: () -> String
)
```
Steps:
1. Build this branch with `npm run build`
2. Preview example package with `env DOCC_HTML_DIR=/path/to/dist swift package --disable-sandbox preview-documentation --target [TARGET]`
3. Find/create a function with multiple parameters where one of the parameters starts with an attribute—verify that it gets indented …

Fix indentation formatting for params with attributes

---

src/components/Navigator/QuickNavigationModal.vue
src/utils/scroll-lock.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js
tests/unit/utils/scroll-lock.spec.js

- **Explanation:** Fixes the QuickNav Preview scrolling issue on iPad, by adding exclusion zones to the scroll-locking.
- **Scope:** Docs pages with QuickNav on iPad
- **Issue:** rdar://108269711
- **Testing:** Added/updated unit tests and manually tested iPad
- **Original PR:** #638

[5.9] Fix QuickNav Preview scrolling issue on iOS mobile device

---

src/components/AdjustableSidebarWidth.vue
tests/unit/components/AdjustableSidebarWidth.spec.js

- **Explanation:** Refactors the default sidebar width on large and ultra wide screens.
- **Scope:** Minor JS change to the Docs Navigator
- **Issue:** rdar://105566775
- **Original PR:** #607

[5.9] Default sidebar width on large and ultrawide screens

---

src/components/DocumentationTopic/PrimaryContent/DeclarationToken.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationToken/LinkableToken.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken/LinkableToken.spec.js

- **Explanation:** Adds support for linkable attributes in Swift declarations.
- **Scope:** Impacts all pages with Swift declarations w/ linkable types
- **Issue:** rdar://108472125
- **Risk:** Medium, small change but impacts all Swift decls
- **Testing:** Added/updated unit tests and manually tested various kinds of declarations with linkable/non-linkable types and attributes
- **Reviewer:** @dobromir-hristov and @hqhhuang 
- **Original PR:** #636

[5.9] Support linkable attribute tokens

---

src/components/ContentNode.vue
src/components/ContentNode/Reference.vue
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Reference.spec.js

Bug/issue #, if applicable: #632 (108515663)
This resolves #632, which is a bug where code voice is automatically applied to a symbol link that has a custom title, even if it doesn't use any code voice itself.
If a custom title is used for a markdown link to a DocC symbol, the inline markdown formatting of that title should be respected as-is.
**Example:**
```markdown
/// Default, should use code voice: ``StringBuilder``
///
/// Custom title, should use code voice: [`custom text`](doc:StringBuilder)
///
/// Custom title, should not use code voice: [custom text](doc:StringBuilder)
///
/// Custom title, should use italics and bold: [_**custom text**_](doc:StringBuilder)
```
Steps:
1. Build this branch with `npm run build`
2. Download/unzip example Swift package [`AttributeExamples.zip`][1] …

Respect formatting of links to symbols using custom titles

---

src/components/Navigator/QuickNavigationModal.vue
src/utils/scroll-lock.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js
tests/unit/utils/scroll-lock.spec.js

- **Explanation:** Fixes the QuickNav Preview scrolling issue on iPad, by adding exclusion zones to the scroll-locking.
- **Scope:** Docs pages with QuickNav on iPad
- **Issue:** rdar://108269711
- **Testing:** Added/updated unit tests and manually tested iPad
- **Original PR:** #638

[5.9-05012023] Fix scrolling QuickSearch previews on iPad

---

src/components/ContentNode.vue
src/components/ContentNode/Reference.vue
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Reference.spec.js

- **Explanation:** Fixes bug where code voice is incorrectly applied to links with custom titles/formatting which point to symbols. Now the inline formatting of the custom links will be respected as-is.
- **Scope:** Impacts all DocC links with custom titles/formatting
- **Issue:** rdar://108515663
- **Risk:** Low, added flag/logic for links with custom titles
- **Testing:** Added/updated unit tests and manually tested various kinds of DocC links to verify that the formatting is appropriate.
- **Reviewer:** @dobromir-hristov and @marinaaisa 
- **Original PR:** #647

[5.9] Respect formatting of links to symbols using custom titles

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

- **Explanation:** Fixes issue with indenting parameters that start with attributes in Swift symbols.
- **Scope:** Impacts all Swift declarations with multiple params that contain attributes.
- **Issue:** rdar://108472125
- **Risk:** Medium, small change but impacts all Swift decls
- **Testing:** Added/updated unit tests and manually tested various kinds of declarations with varying number of params both with and without attributes.
- **Original PR:** #642

[5.9] Fix indentation formatting for params with attributes

---

src/components/ContentNode/FigureCaption.vue
tests/unit/components/ContentNode/FigureCaption.spec.js

Bug/issue #, if applicable: 109060293
Fixes an issue where captions without titles have an unnecessary leading whitespace character, which may slightly impact the alignment of the text.
Steps:
1. Verify that captions without titles don't have leading whitespace anymore
2. Verify that captions with titles still have a whitespace between the caption title and content.

Remove accidental leading whitespace for some captions

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: 108167163
Fixes an issue where attributes are being incorrectly indented.
This happens because the existing logic for indenting parameters simply looks for the first opening `(` character to indent the first param of a multi-param symbol—this doesn't work when a symbol is prefixed with an attribute that takes arguments, since it also uses parenthesis.
To fix it—the logic has been updated to look for the first `(` character _that follows the first keyword token_.
**Example:**
```swift
// original declaration
@objc(quxA:B:) func quxqux(a: Int, b: Int) -> Int
// formatted declaration before this fix
@objc(quxA:B:
)
func quxqux(a: Int,
b: Int) -> Int
// formatted declaration after this fix
@objc(quxA:B:)
func quxqux(
a: Int,
b: Int
) -> Int
```
**Notes:**
The diff …

Fix param formatting with complex attributes

---

src/components/ContentNode/FigureCaption.vue
tests/unit/components/ContentNode/FigureCaption.spec.js

- **Explanation:** Fixes issue where captions without titles have leading whitespace character when they shouldn't.
- **Scope:** Impacts pages with figure captions that have no titles
- **Issue:** rdar://109060293
- **Risk:** Low, minor HTML layout adjustment
- **Testing:** Updated unit tests and visually inspected alignment of captions without titles.
- **Original PR:** #655

[5.9] Remove accidental leading whitespace for certain captions

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

- **Explanation:** Fixes issue where attributes with arguments break the indentation formatting of multi-parameter symbols.
- **Scope:** Impacts any Swift function/initializer/macro/subscript taking multiple parameters that is prefixed with an attribute that takes arguments.
- **Issue:** rdar://108167163
- **Risk:** Medium, small JS logic change that impacts all Swift declarations
- **Testing:** Added unit tests and manually tested various kinds of Swift declarations that have attributes and varying number of parameters.
- **Original PR:** #656

[5.9] Fix param formatting with complex attributes

---

CONTRIBUTING.md
README.md

JIRA is no longer used for Swift, references updated to GitHub

Remove references to JIRA in the README

---

src/lang/locales/ja-JP.json
src/lang/locales/zh-CN.json

Bug/issue #108904481, if applicable: 
Add translated strings
NA
Steps:
1. Add the following to `theme-settings.json` file at public folder
```json
{
"features": {
"docs": {
"i18n": {
"enable": true
}
}
}
}
```
3. Run `npm run serve`
4. Go to the bottom of the page and change the language in the locale selector to Chinese and Japanese
5. Assert that strings are correct

Add translated strings

---

src/components/ContentNode/Table.vue

- **Explanation:** It prevents breaking words inside header cell in an HTML tables
- **Scope:** Tables
- **Issue:** rdar://107874086
- **Risk:** Low, only config change
- **Testing:** Verifies that table title don't allow words to break
- **Reviewer:** @hqhhuang @dobromir-hristov 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/661

[5.9] It prevents breaking words inside header cell in an HTML tables

---

src/components/ContentNode/Table.vue

Bug/issue #107874086, if applicable: 
It prevents breaking words inside header cell in an HTML tables.
In Japanese alphabet, words were being broken making reading difficult.
NA
[SlothCreatori18n.doccarchive.zip](https://github.com/apple/swift-docc-render/files/11466531/SlothCreatori18n.doccarchive.zip)
Steps:
1. Use the doccarchive attached above
2. Go to http://localhost:8080/ja-JP/documentation/slothcreator
3. Assert that the table displayed at Overview in Japanese don't break their words 

It prevents breaking words inside header cell in an HTML tables.

---

src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js

Bug/issue #, if applicable: 109681482
Fixes a regression that was introduced in #564 where multi-parameter Objective-C functions/initializers are not being formatted onto newlines anymore.
This happened because the code relies on a reference to a DOM node, and that PR introduced an additional layer of indirection where the reference is now a Vue component, requiring the need to also call `.$el` on that updated ref.
\cc @ethan-kusters 
Steps:
1. Find any Objective-C symbol that has multiple parameters
2. Verify that the symbol is now being broken onto multiple lines instead of being on a single line

Fix regression with Objective-C api whitespace formatting

---

src/components/ContentNode/CodeListing.vue
src/components/DocumentationTopic/ContentNode.vue
src/components/Tutorial/CodePreview.vue
src/utils/syntax-highlight.js
tests/unit/components/ContentNode/CodeListing.spec.js
tests/unit/utils/syntax-highlight.spec.js

closes #662 
rdar://109756906
This PR refactors the css styling of the CodeListing in order to properly render new lines coming from code.
- This builds upon #663
- probably fixes #502 properly
This PR should be tested with as many examples as possible, across Tutorials and Doc pages.
We should test with scrollable content, multi-line content, and any combination of them.

Code listing style fixes, remove extra line management

---

src/components/DocumentationTopic/OnThisPageStickyContainer.vue
src/components/OnThisPageNav.vue

- **Explanation:** Fixes the spacings on the OnThisPage Nav component, so they align better with the Navigator
- **Scope:** Impacts docs pages with enabled OnThisPageNav
- **Issue:** rdar://107572361
- **Risk:** Low, css only
- **Testing:** Manually verify in browser
- **Reviewer:** @mportiz08 @SamLanier 
- **Original PR:** #586

[5.9] Fix onThisPageNav top spacing

---

src/components/ContentNode/CodeListing.vue
src/components/DocumentationTopic/ContentNode.vue
src/components/Tutorial/CodePreview.vue
src/utils/syntax-highlight.js
tests/unit/components/ContentNode/CodeListing.spec.js
tests/unit/utils/syntax-highlight.spec.js

- **Explanation:** Fixes issues with CodeListings and empty lines from highlighted elements that span across lines.
- **Scope:** CSS fix, that Impacts all pages with code listings
- **Issue:** rdar://109756906
- **Risk:** Medium, its a CSS only fix, but we have lots of use cases for that component.
- **Testing:** Verified manually in browser
- **Reviewer:** @mportiz08  and @marinaaisa 
- **Original PR:** #667

[5.9] Code listing style fixes, remove extra line management

---

src/lang/locales/en-US.json

- **Explanation:** Updates text from "Read only" to "Read-only"
- **Scope:** Impacts docs for REST APIs with read-only object fields
- **Issue:** rdar://107896158
- **Risk:** Low, only config change
- **Testing:** Verified that new string renders where expected for a REST API
- **Reviewer:** @dobromir-hristov and @marinaaisa 
- **Original PR:** #668

[5.9] "Read only" ❌ "Read-only" ✅

---

src/components/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js

- **Explanation:** Enable screen readers to skip 'main' in IDE mode 
- **Scope:** IDE mode only
- **Issue:** rdar://107573378
- **Testing:** Manually verify in IDE
- **Original PR:** #658

[5.9] Enable screen readers to skip 'main' in IDE mode 

---

src/components/ContentNode.vue
src/components/ContentNode/Caption.vue
src/styles/core/typography/_font-styles.scss
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Caption.spec.js

- **Explanation:** Refactor tables to have better AX
- **Scope:** tables
- **Issue:** rdar://30234820
- **Testing:** Unit testing
- **Original PR:** https://github.com/apple/swift-docc-render/pull/40

[5.9] <table> should be taken out of <figure> and the <figcaption> should become the table’s <caption>

---

src/setup-utils/SwiftDocCRenderi18n.js

- **Explanation:** Add support for dateTimeFormats in VueI18n
- **Scope:** i18n settings
- **Issue:** rdar://09731672
- **Testing:** Verified manually in browser
- **Original PR:** https://github.com/apple/swift-docc-render/pull/678

[5.9] Add support for dateTimeFormats in VueI18n

---

src/styles/base/_typography.scss
src/styles/core/_vars.scss
src/styles/core/typography/_font-style-utils.scss

Bug/issue #108129110, if applicable: 
Add support for localized font families
NA
Steps:
1. Make sure current fonts look correct 

Add support for localized font families

---

src/styles/core/typography/_font-style-utils.scss

Bug/issue #, if applicable: 110021706
This is a slight update to #677 to fix an issue where localized variants of normal body text fonts are mistakenly overriding the monospaced font variant, as we don't support localized monospaced variants (yet).
Steps:
1. Configure a localized font for body text
2. View a page with both body text and code-voice text
3. Verify that only the body text gets the localized font and not the code-voice text

Don't override monospaced font with localized body text font variant

---

src/components/ContentNode/Caption.vue

Bug/issue #, if applicable: 110085109
Fixes a minor typography issue introduced with #40 where a font-style was renamed, but the place where it was used was not updated to use the new name.
Steps:
1. Run `npm run serve` and verify that no sass warning messages are emitted
2. Find example content with a captioned figure and verify that it now has the smaller font-size that it did previously

Update reference to renamed font style

---

src/components/ContentNode/Caption.vue

- **Explanation:** Fixes issue where a font-style was renamed but a reference to the old name was not properly updated, resulting in unexpectedly large text for figure captions.
- **Scope:** Impacts any caption for a figure.
- **Issue:** rdar://110085109
- **Risk:** Low, single word/argument change
- **Testing:** Verified that warning is no longer emitted in console and verified that caption text is back to its expected size.
- **Original PR:** #683

[5.9] Update reference to renamed font style

---

src/components/ContentNode.vue
src/components/ContentNode/Caption.vue
src/components/ContentNode/FigureCaption.vue
src/styles/core/typography/_font-styles.scss
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/FigureCaption.spec.js

This PR reverts #674 and #686 
#674 introduces a regression that prevents certain pages from rendering (and #686 was only introduced to fix a separate regression that #674 also introduced.)
\cc @marinaaisa @dobromir-hristov

[5.9] Revert #674 and #686

---

src/components/ContentNode.vue
src/components/ContentNode/Caption.vue
src/components/ContentNode/FigureCaption.vue
src/styles/core/typography/_font-styles.scss
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/FigureCaption.spec.js

This PR reverts #40 and #683
#40 introduces a regression that prevents certain pages from rendering (and #683 was only introduced to fix a separate regression that #40 also introduced.)
\cc @marinaaisa @dobromir-hristov

Revert #40 and #683

---

src/components/Navigator/NavigatorCard.vue
src/components/Navigator/QuickNavigationModal.vue

Bug/issue #, if applicable: 108916627
Adjusts the minimum filter width in the Navigator, so you can always see parts of the picked tags, on empty input.
closes #603 
NA
1. Make screen very narrow and then make the Navigator as narrow as possible.
2. Then try to pick a tag from the list
3. Assert at least some part of the tag is visible

Ensure the navigator filter picked tags are slightly visible, even on very narrow screens.

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue

Bug/issue #, if applicable: 109801256
Fixes a small possible issue with nav dropdown menus becoming too large
NA
Ensure there are no regressions with one or many lang options for docs.

Fix small css issue with nav secondary menus becoming too bing

---

src/components/Article.vue
src/components/DocumentationTopic.vue
src/components/Navigator/QuickNavigationPreview.vue
src/components/Tutorial.vue
src/components/TutorialsOverview.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/Navigator/QuickNavigationPreview.spec.js

Bug/issue #, if applicable: 109856608
Moves the setting of the references back into the `components/DocumentationTopic` instead of the `view`.
This should fix potential rendering issues in Safari.
NA
Ensure all links and interact-able elements on pages are rendered properly and console has no errors.

Move the references setting back to the DocTopic component

---

src/components/Article.vue
src/components/DocumentationTopic.vue
src/components/Navigator/QuickNavigationPreview.vue
src/components/Tutorial.vue
src/components/TutorialsOverview.vue
src/views/DocumentationTopic.vue
tests/unit/components/DocumentationTopic.spec.js
tests/unit/components/Navigator/QuickNavigationPreview.spec.js

- **Explanation:** Fixes a bug with in Safari where links in bullet points were miss-aligned
- **Scope:** DocumentationTopic pages
- **Issue:** rdar://109856608
- **Testing:** Manual and automated testing in all modes
- **Original PR:** #693

[5.9] Move the references setting back to the DocTopic component

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue

- **Explanation:** Fixes a small possible issue with nav dropdown menus becoming too large
- **Scope:** Documentation Pages
- **Issue:** rdar://109801256
- **Testing:** Manual in the browser
- **Reviewer:** @marinaaisa
- **Original PR:** #684

[5.9] Small css issue with nav secondary menus becoming too long

---

src/App.vue
src/components/Article.vue
src/components/DocumentationTopic.vue
src/components/Footer.vue
src/components/LocaleSelector.vue
src/components/Tutorial.vue
src/components/TutorialsOverview.vue
src/lang/locales/en-US.json
src/stores/AppStore.js
src/views/NotFound.vue
src/views/ServerError.vue
tests/unit/App.spec.js
tests/unit/components/Footer.spec.js
tests/unit/components/LocaleSelector.spec.js
tests/unit/stores/AppStore.spec.js
tests/unit/views/NotFound.spec.js

- **Explanation:** Updates existing locale selector behavior so that it only displays when multiple locales are available for a given page.
- **Scope:** Impacts state JS logic used for all top-level page types
- **Issue:** rdar://109166355
- **Risk:** Medium, potential for regressions with locale selector and/or other issues with page navigation
- **Testing:** Added/updated unit tests and verified that the selector only shows up when multiple locales are available for a given page
- **Reviewer:** @mportiz08, @dobromir-hristov 
- **Original PR:** #687

Only enable locale selector when multiple are available

---

src/components/OnThisPageNav.vue
src/mixins/onThisPageRegistrator.js
tests/unit/components/OnThisPageNav.spec.js
tests/unit/mixins/__snapshots__/onThisPageRegistrator.spec.js.snap
tests/unit/mixins/onThisPageRegistrator.spec.js

Bug/issue #, if applicable: 107193315
Only utilize word break hints for the title of a symbol page to avoid unnecessary breaking of prose-like content.
This is an alternate implementation of #587 that I think should be more flexible and work with a majority of content.
Steps:
1. Preview docs using this branch of the renderer
2. Verify that the first title in the on-this-page utilizes `<wbr>` hints only when the page is for a symbol.
3. Check for any other regressions with the on-this-page text

[on-this-page] Only use word break hints for symbol title

---

src/components/CodeBlock.vue

Bug/issue #, if applicable: 110741983
Fixes a bug on Safari, where if the last line in a codeblock is very long, the `after` accessibility pseudo element helper gets pushed to the side, causing the browser to render hirozontal scrollbars.
NA
Load a page with a codeblock that has very long last line
Steps:
1. Assert in Safari there are no horizontal scrollbars

Fix horizontal scrollbars on Safari when code blocks are very long

---

src/components/CodeBlock.vue

- **Explanation:** Fixes an issue where pages with long code listings make the page scroll horizontally in Safari when it shouldn't
- **Scope:** Impacts pages with long code listings in Safari only
- **Issue:** rdar://110741983
- **Risk:** Low, single CSS property addition
- **Testing:** Tested problematic pages to verify that the page no longer scrolls past the expected layout and verified that there are no other regressions for other pages in Safari and other browsers
- **Reviewer:** @mportiz08 and @hqhhuang 
- **Original PR:** #700

[5.9] Fix horizontal scrollbars on Safari when code blocks are very long

---

src/components/CodeBlock.vue

- **Explanation:** Fixes an issue where pages with long code listings make the page scroll horizontally in Safari when it shouldn't
- **Scope:** Impacts pages with long code listings in Safari only
- **Issue:** rdar://110741983
- **Risk:** Low, single CSS property addition
- **Testing:** Tested problematic pages to verify that the page no longer scrolls past the expected layout and verified that there are no other regressions for other pages in Safari and other browsers
- **Reviewer:** @mportiz08 and @hqhhuang 
- **Original PR:** #700

[5.9-0626] Fix horizontal scrollbars on Safari when code blocks are very long

---

src/components/OnThisPageNav.vue
src/mixins/onThisPageRegistrator.js
tests/unit/components/OnThisPageNav.spec.js
tests/unit/mixins/__snapshots__/onThisPageRegistrator.spec.js.snap
tests/unit/mixins/onThisPageRegistrator.spec.js

- **Explanation:** Updates "on this page" affordance to only add word break hints to the first title of symbol pages, instead of applying them to all items in the list.
- **Scope:** Impacts the "on this page" affordance on all pages
- **Issue:** rdar://107193315
- **Risk:** Low, focused change to on-this-page component and related function
- **Testing:** Updated unit tests and manually verified with a large number of example pages that the hints are only utilized for the title heading of symbol pages
- **Original PR:** #701

[5.9] [on-this-page] Only use word break hints for symbol title

---

src/components/ContentNode/LinkableHeading.vue
src/lang/locales/en-US.json
src/styles/base/_typography.scss
tests/unit/components/ContentNode/LinkableHeading.spec.js

Bug/issue #111006953, if applicable: 
Aria-label that indicates scrolling behaviour interferes in headings content for screen readers
It's been fixed by restructuring how the anchor link is set and adding AX description that should read: Content of heading + "in page link" to describe that the link is within the page.
NA
Steps:
1. Run any doccarchive
2. Go to section title
3. Assert that you can read its content using VoiceOver

Aria-label that indicates scrolling behaviour interferes in headings content for screen readers

---

src/components/ContentNode/LinkableHeading.vue
src/lang/locales/en-US.json
tests/unit/components/ContentNode/LinkableHeading.spec.js

- **Explanation:** 
- **Scope:** Headings' AX
- **Issue:** rdar://111006953
- **Testing:** Tested that headings work well and are accessible for VoiceOver
- **Reviewer:** @mportiz08
- **Original PR:** [#700 ](https://github.com/apple/swift-docc-render/pull/698)

[5.9] Aria-label that indicates scrolling behaviour interferes in headings content for screen readers

---

src/components/ContentNode.vue
src/components/ContentNode/Caption.vue
src/components/ContentNode/Figure.vue
src/components/ContentNode/FigureCaption.vue
src/styles/core/typography/_font-styles.scss
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/Caption.spec.js
tests/unit/components/ContentNode/FigureCaption.spec.js

Bug/issue #, if applicable: 30234820
Use `<caption>` for tables instead of `<figcaption>`.
Tables with captions will no longer be embedded in a `<figure>` with a `<figcaption>`. Instead, the `<table>` will simply have a `<caption>` as its first element when needed.
For table captions, the position of the caption must be done in CSS since the `<caption>` is always required to be the first element of the `<table>` and cannot be moved to the end like they can with figure captions.
Steps:
1. Find a page with a captioned table
2. Verify that the DOM structure now looks like `<table><caption>` instead of `<figure><figcaption><table>`
3. Verify that there are no visual regressions with figures, captions, or tables
Make sure you check off the following items. If they cannot be completed, provide …

Use <caption> for table captions instead of <figcaption>

---

src/styles/core/_syntax.scss
src/styles/core/colors/_light.scss

Bug/issue #, if applicable: #712 
Maps the appropriate colors for the "addition" and "deletion" syntax nodes when highlighting code listings of language "diff" or "patch".
Before:
After:
Resolves #712 
Example code listing:
```diff
diff --git a/1.txt b/2.txt
index de98044..6372083 100644
--- a/1.txt
+++ b/2.txt
@@ -1,3 +1,3 @@
a
-b
c
+d
```
Steps:
1. Copy the contents of the example diff from above to a fenced code block with language "diff" in the markdown (or use any other example diff).
2. Verify that the lines starting with "+" are now in green
3. Verify that the lines starting with "-" are now in red

Add syntax colors for diff additions/deletions.

---

src/styles/core/_syntax.scss
src/styles/core/colors/_light.scss

- **Explanation:** Adds missing color mappings for code listings with `diff` language
- **Scope:** Impacts any pages with a code listing with language `diff`
- **Issue:** rdar://105420253 (#712 )
- **Risk:** Low, 2 added CSS variables for syntax span nodes
- **Testing:** Verify that red/green added/deleted lines are now visible in code listings of language `diff`
- **Original PR:** #713

[5.9] Add syntax colors for diff additions/deletions

---

src/components/ContentNode.vue
tests/unit/components/ContentNode.spec.js

- **Explanation:** Adds support for rendering hard line breaks within individual paragraphs of content
- **Scope:** Impacts pages where `\` character is used to hard break lines in the markdown input
- **Issue:** rdar://101684224 (#697)
- **Risk:** Low, minor JS logic change for mapping text nodes to HTML
- **Testing:** Verify that hard line breaks from markdown sources now appear on subsequent lines instead of getting collapsed into a single space or another paragraph in the rendered page
- **Reviewer:** @dobromir-hristov and @Kyle-Ye 
- **Original PR:** #714

[5.9] Add support for hard line breaks from markdown text

---

src/components/TutorialsOverview.vue

Bug/issue #, if applicable: 108634043
In situations with no footer and a long viewport height and little actual content, the background of the empty space will be white.
It should be a darker fill color in any light/dark/auto appearance since that page purposefully has an "always-dark" design theme.
Steps:
1. Open an existing tutorials overview page and remove any chapters it has, if any.
2. Render that page with this branch using `VUE_APP_TARGET=ide` and verify that the empty space in a tall viewport appears dark instead of light, regardless of the user's overall light/dark/auto preference.

Fix edge case issue where tutorials-overview bg may appear light

---

src/components/ContentNode/CodeListing.vue

Bug/issue #, if applicable: 112272083
Removes an unnecessary `min-height` rule for code listing containers.
This rule causes an issue when a listing is in a DocC `@Col` directive where the listing is rendered too big and on top of the content below it.
Example before/after screenshots:
**Before**
**After**
Steps:
1. Add a `@Row` with 2 `@Col` above some existing content where each column has a code listing. As an example, you can apply this [patch][1] to add some example content to the `SwiftDocCRender.docc` docs in this repo.
2. Verify that the code listings get rendered as expected, without covering up the content below it. If you're using the example patch, you can test this with `DOCC_HTML_DIR=/path/to/swift-docc-render/dist npm run docs:preview` (remember to build this branch first) …

Fix issue where code listings in columns can obscure subsequent content

---

jest.config.js
src/setup-utils/vue-config-utils.js
src/utils/syntax-highlight.js

Bug/issue #, if applicable: 113252221
Fixes and issue with webpack pulling in more highlight.js files than it should + fixes the node modules path
NA
Steps:
1. Ensure when building, we build the correct set of language files
2. Ensure the new import path does not cause errors when referenced by extending docc-render

Ensure highlight.js builds only the files that are imported

---

src/utils/custom-highlight-lang/swift.js
tests/unit/utils/syntax-highlight.spec.js

Bug/issue #, if applicable: 102993199
Fixes an issue demonstrated in the following screenshots where the syntax highlighting looks broken for Swift code listings with multi-line string literals that have backslash newline delimiters.
Before:
After:
This happens because the HTML `<span>` for the "subst" token representing the backslash also includes the newline whitespace, and that causes issue when our line-by-line logic for multi-line syntax encounters this span that is broken onto multiple lines.
To fix it, we are simply overriding the default sub-mode from highlight.js for this token to _not_ include the newline characters in the resulting `<span>`.
Steps:
1. Checkout this branch and run the dev server with `VUE_APP_DEV_SERVER_PROXY=https://docs.swift.org/swift-book npm run serve`
2. …

Fix issue where backslash newline delimiters in multiline Swift string literals break syntax highlighting

---

src/setup-utils/SwiftDocCRenderRouter.js
tests/unit/setup-utils/SwiftDocCRenderRouter.spec.js

Bug/issue #, if applicable: 113289632 (#722)
This fixes an issue where the wrong component is used to render a documentation article if it has the name "Tutorials".
This happens because the locale-specific tutorials-overview route matches the URL for this article before the expected route for documentation topics matches it. To fix it, I simply have re-ordered the routes definition so that the locale-specific versions come after the normal ones instead of before.
\cc @jiachenyee
Steps:
1. Checkout this branch and run the dev server with `VUE_APP_DEV_SERVER_PROXY=https://bug.jiachen.app npm run serve`
2. Open http://localhost:8080/documentation/tutorials and verify that it gets rendered as a normal documentation article and doesn't appear to be a blank tutorials-overview page anymore
3. …

Ensure articles with the name "Tutorials" render with the right component

---

src/components/ContentNode/LinkableHeading.vue
tests/unit/components/ContentNode/LinkableHeading.spec.js

Bug/issue #, if applicable: 115140459
Prevents an issue where the text _"in page link"_ is unexpectedly included when selecting and copy/pasting a linkable heading.
Steps:
1. Run `VUE_APP_DEV_SERVER_PROXY=https://mportiz08.github.io/swift-docc npm run serve` and open http://localhost:8080/documentation/docc (or any content with linkable subheadings)
2. Use the mouse to select and copy/paste the text of a linkable heading, like [this one](http://localhost:8080/documentation/docc#structure-and-formatting)
3. Verify that the pasted text matches the heading and does not include the text "in page link" at the end anymore

Disallow selection of invisible text for linkable headings

---

src/utils/syntax-highlight.js

[5.10] Fix broken import for non-custom syntax langs

---

src/components/ContentNode/Reference.vue
src/components/ContentNode/ReferenceExternalSymbol.vue
src/components/DocumentationTopic/RelationshipsList.vue
tests/unit/components/ContentNode/Reference.spec.js
tests/unit/components/ContentNode/ReferenceExternalSymbol.spec.js
tests/unit/components/DocumentationTopic/RelationshipsList.spec.js

Bug/issue #, if applicable: 112048068
This PR allows for handling external links in the "Relationships" section when provided by the compiler.
It also handles the case when an external link has been categorized as a symbol, so these kinds of external links can be rendered with code voice.
Steps:
1. Find a page with external links in its "Relationships" section.
2. Verify that a normal `<a>` tag is used to render it, rather than a `<router-link>`.

Allow external links in "Relationships" section

---

src/components/ColorSchemeToggle.vue
src/components/Tutorial/Assessments/Quiz.vue
src/lang/locales/en-US.json
tests/unit/components/ColorSchemeToggle.spec.js
tests/unit/components/Tutorial/Assessments/Quiz.spec.js

Explanation: Add legend and fieldset to Quiz assessment and Color scheme Toggle
Scope: Impacts only to Quiz assessment and Color scheme Toggle
Issue: rdar://115116952
Risk: Low, minor change for AX
Testing: Added/updated unit tests and manual testing
Reviewer: @dobromir-hristov
Original PR: https://github.com/apple/swift-docc-render/pull/732

[5.10] Add legend and fieldset to Quiz assessment and Color scheme Toggle

---

src/components/ColorSchemeToggle.vue
src/components/Tutorial/Assessments/Quiz.vue
src/lang/locales/en-US.json
tests/unit/components/ColorSchemeToggle.spec.js
tests/unit/components/Tutorial/Assessments/Quiz.spec.js

Bug/issue #115116952, if applicable: 
Add legend and fieldset to Quiz assessment and Color scheme Toggle
NA
Steps:
1. Go to a page with a Quiz assessment
2. Open VO
3. Assert that before going into the answers of the quiz, VO describes "Possible answers"
4. Go to the bottom of the page
5. Assert that before the color schemes, VO reads "Select a color scheme preference"

Add legend and fieldset to Quiz assessment and Color scheme Toggle

---

src/components/Tutorial/Assessments/Quiz.vue
src/lang/locales/en-US.json
tests/unit/components/Tutorial/Assessments/Quiz.spec.js

Bug/issue #115116964, if applicable: 
Expose answer content to VoiceOver in Tutorials' Quiz
NA
Steps:
0. Turn VoiceOver on
1. Go to a page with a Quiz
2. Select an incorrect answer
3. Submit
4. Assert that VoiceOver reads: "Answer [content of the answer] is [result]"

Expose answer content to VoiceOver in Tutorials' Quiz

---

src/components/Card.vue
src/components/ContentNode.vue
src/components/LocaleSelector.vue
src/components/Navigator/BaseNavigatorCard.vue
src/components/Navigator/BaseNavigatorCardItem.vue
src/components/Navigator/NavigatorCardItem.vue
src/components/TutorialsOverview/ChapterTopicList.vue
src/components/TutorialsOverview/ResourcesTile.vue
src/styles/base/_typography.scss
src/styles/core/_typography.scss

- Explanation: Inline links need to be underline under WCAG 2.2 compliance
- Scope: All project
- Issue: rdar://115116961
- Risk: Low
- Testing: Tested manually since they are style changes
- Reviewer: @hqhhuang @dobromir-hristov 
- Original PR: https://github.com/apple/swift-docc-render/pull/733

[5.10] Underline inline links

---

src/components/DocumentationTopic/ViewMore.vue
src/components/Navigator/QuickNavigationModal.vue
src/components/Navigator/QuickNavigationPreview.vue
src/lang/locales/en-US.json
tests/unit/components/DocumentationTopic/ViewMore.spec.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js
tests/unit/components/Navigator/QuickNavigationPreview.spec.js

Bug/issue #106379419, if applicable: 
We added a few new hard-coded strings recently and we should add them to the locales.
NA
Steps:
1. Assert that Quick Navigation strings and View More in docs are rendering well in English

Add QuickNav and View More strings to i18n

---

src/components/DocumentationTopic/ViewMore.vue
src/components/Navigator/QuickNavigationModal.vue
src/components/Navigator/QuickNavigationPreview.vue
src/lang/locales/en-US.json
tests/unit/components/DocumentationTopic/ViewMore.spec.js
tests/unit/components/Navigator/QuickNavigationModal.spec.js
tests/unit/components/Navigator/QuickNavigationPreview.spec.js

- Explanation: Add QuickNav and View More strings to i18n
- Scope: Quick Navigation
- Issue: rdar://106379419
- Risk: Low
- Testing: Tested manually and updated unit tests
- Reviewer: @mportiz08 
- Original PR: https://github.com/apple/swift-docc-render/pull/747

[5.10] Add QuickNav and View More strings to i18n

---

src/components/ContentNode/DeviceFrame.vue
tests/unit/components/ContentNode/DeviceFrame.spec.js

Bug/issue #, if applicable: 115480995
Removes the rounding from the DeviceFrames screen calcs, because they are causing weird rounding issues in browsers, while resizing. 
The percentages are never visually rendered, so it does not matter how many decimals there are.
NA
Steps:
1. Load a page with device frames
2. Ensure frames from leak background colors, are off positioned, etc.

Remove rounding from device frame calculations

---

src/components/Navigator/QuickNavigationModal.vue
tests/unit/components/Navigator/QuickNavigationModal.spec.js

Bug/issue #111742596, if applicable: 
Quick Navigation user should be able to tab from list of results to preview and use arrow keys within the list, to avoid tabbing all the list
NA
Steps:
1. Go to any documentation page
2. Open Quick Navigation
3. Assert that you can tab from the list of results to the preview without tabbing all the list
4. Assert that you can move in the list of results using your arrow keys

Quick Navigation user should be able to tab from list of results to preview and use arrow keys within the list

---

src/components/ImageAsset.vue
src/components/Tutorial/SectionSteps.vue
src/components/VideoAsset.vue
src/utils/assets.js
tests/unit/components/ImageAsset.spec.js
tests/unit/components/VideoAsset.spec.js
tests/unit/utils/assets.spec.js

- **Explanation:** Adjusts layout of tutorial page to allow for landscape assets to better fill the step preview container when possible, resulting in larger, easier to see images depending on the dimensions.
- **Scope:** Added JS logic that impacts images/videos and CSS that only impacts tutorial step preview container
- **Issue:** rdar://117555171
- **Risk:** Low, minimal logic added for assets, style changes scoped to one component
- **Testing:** Updated unit tests, visually tested tutorials with varying images/videos/viewport sizes, checked that images/videos in other places are unchanged
- **Original PR:** #752

[5.10] Improve layout for landscape tutorial step assets

---

src/components/Navigator.vue
src/components/Navigator/NavigatorCard.vue
src/views/DocumentationTopic.vue
tests/unit/components/Navigator.spec.js
tests/unit/components/Navigator/NavigatorCard.spec.js
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 117442044
If we are on a specific overload page and it doesn't exist in the navigator, we should attempt to match for its generic item as well.
Branch: [combine-overloads-navigator](https://github.com/hqhhuang/swift-docc-render/tree/combine-overloads-navigator)
Test manually
Steps:
1. Verify if the specific overload page is not curated in the navigator, generic page is highlighted
2. If it is curated, then it should be highlighted as usual. (No behavior change)

Match for generic item in the navigator

---

src/components/ContentNode/DeviceFrame.vue
tests/unit/components/ContentNode/DeviceFrame.spec.js

- Explanation: Removes the rounding from the DeviceFrames screen calcs, because they are causing weird rounding issues in browsers, while resizing.
- Scope: Device Frames
- Issue: rdar://115480995
- Risk: Low
- Testing: Tested manually and updated unit tests
- Reviewer: @marinaaisa  
- Original PR: https://github.com/apple/swift-docc-render/pull/750

[5.10] Remove rounding from device frame calculations

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #, if applicable: 110732384
Adds a new "Web Service Endpoints" tag to filter navigator items in REST API projects. This can be used to more easily narrow down all the REST HTTP endpoint pages in a given project.
Steps:
1. Use this branch to render any REST API project with endpoint documentation pages
2. Open any documentation page and verify that the navigator now has a "Web Service Endpoints" tag in the navigator filter and that it properly filters the navigator to only show endpoint pages
3. Ensure the new tag doesn't show up for projects without endpoint pages
4. Check for any other regressions with existing navigator filter behavior

Expose "Web Service Endpoints" as new filter tag in navigator

---

src/lang/index.js
src/lang/locales.json
src/lang/locales/ja-JP.json
src/lang/locales/ko-KR.json
src/lang/locales/zh-CN.json
tests/unit/components/LocaleSelector.spec.js

Bug/issue #117588570, if applicable: 
Add Korean locale & new strings for Japanese and Chinese
NA
Steps:
1. Assert that strings are correct in different languages

[i18n] Add Korean locale & new strings for Japanese and Chinese

---

src/components/Tutorial/Hero.vue

- **Explanation:** Fixes issue where the colors for some elements like asides look broken in the tutorial intro in light mode
- **Scope:** CSS-only change that impacts the tutorial intro element
- **Issue:** rdar://118359891
- **Risk:** Low, minor CSS-only change
- **Testing:** Visually tested that asides are using the right colors in all color scheme modes and checked for any regressions with other colors in the tutorial intro
- **Original PR:** #760

[5.10] Ensure dark colors are always used in tutorial hero

---

src/components/Tutorial/SectionSteps.vue

- **Explanation:** Fixes spacing between consecutive asides in a step caption
- **Scope:** Only impacts certain content in tutorial step captions
- **Issue:** rdar://118356255
- **Risk:** Low, minor CSS-only change
- **Testing:** Visually tested that the spacing between consecutive asides looks right now and no regressions with other element spacing in step captions
- **Original PR:** #761

[5.10] Adjust spacing between consecutive asides within steps

---

src/components/DocumentationTopic/OnThisPageStickyContainer.vue
tests/unit/components/DocumentationTopic/OnThisPageStickyContainer.spec.js

Bug/issue #, if applicable: 109407291
In certain viewport widths in IDE targets, there sometimes is no space between the documentation content and the on-this-page element, if enabled. This change adds some spacing to address that specific issue without impacting the width of the element or the spacing in any other environments.
Steps:
1. View content with the on-this-page element enabled in an IDE target and verify that the documentation content always has space between it and the on-this-page element, regardless of the viewport size
2. Verify that there are no other spacing/size regressions with the on-this-page element in other environments

Adjust on-this-page spacing in IDE targets

---

src/components/DocumentationTopic/OnThisPageStickyContainer.vue
tests/unit/components/DocumentationTopic/OnThisPageStickyContainer.spec.js

- **Explanation:** Fixes issue where there sometimes isn't enough space between doc content and the on-this-page element in IDE targets at certain viewport widths
- **Scope:** CSS-only change that impacts doc pages w/ on-this-page enabled
- **Issue:** rdar://109407291
- **Risk:** Low, minor/scoped CSS-only change
- **Testing:** Visually tested that there is always space between doc content and on-this-page at any viewport width in IDE targets and ensured that there are no styling changes for on-this-page in other environments
- **Original PR:** #768

[5.10] Adjust on-this-page spacing in IDE targets

---

src/components/DocumentationTopic.vue
src/lang/locales/en-US.json
tests/unit/components/DocumentationTopic.spec.js

**Explanation:** Use localized string format for "other declaration" button.
**Bug/Issue #**: rdar://119615630
**Scope:** Small
**Risk:** No risk, just 1 string config change for other declarations
**Testing:** Updated unit test and manual testing
**Reviewed By:** @mportiz08
NA
Verify the english version of the string is still rendered correctly, follow testing instructions [here](https://github.com/apple/swift-docc-render/pull/762)

Use localized string format for "other declaration" button

---

src/components/DocumentationTopic/TopicLinkBlockIcon.vue
src/components/DocumentationTopic/TopicsLinkBlock.vue
tests/unit/components/DocumentationTopic/TopicLinkBlockIcon.spec.js
tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js

Bug/issue #, if applicable: 120670171
Due to limitations with remote SVG assets, there can be an issue where the color of a custom icon may be present in multiple locations using the same color, which results in a less than ideal experience.
Current known workarounds for this issue would necessitate server side headers for cross origin resource sharing, which DocC-Render can't control since it is a client-side only tool—with that in mind, it makes more sense to remove the ability for overriding the icon here and leaving it as something to customize in the hero element only for now.
Steps:
1. Add the following snippet to an existing documentation catalog, with the referenced icon asset.
```
@Metadata {
@PageImage(purpose: icon, source: "example-custom-icon.svg", alt: "icon")
}
```
2. …

Remove ability to override icons in "Topics" section

---

src/components/Asset.vue
src/components/ReplayableVideoAsset.vue
src/components/VideoAsset.vue
src/lang/locales/en-US.json
tests/unit/components/Asset.spec.js
tests/unit/components/ReplayableVideoAsset.spec.js
tests/unit/components/VideoAsset.spec.js

Bug/issue #120903895, if applicable: 
Add aria tags to improve AX in videos.
A visually hidden text is being referenced as description for the video and its custom controls using `aria-describedby` tag.
More info: https://www.w3.org/WAI/PF/HTML/wiki/Media_Alt_Technologies 
- Add `aria-describedby` to the video element: it describes the content video using a visually hidden text that is being referenced in the video element. In case an screen reader cannot read the description, it will still read the text content.
- Add `aria-label` to the video element: it indicates how the user should interact when there are custom controls. This is not added if video uses the default controls because it's not needed.
- Add `aria-roledescription` to the video element: it describes that the element is a …

Add alt text for screen readers to describe video content

---

src/components/Card.vue
src/components/DocumentationTopic/TopicsLinkCardGrid.vue
src/components/Pager.vue
src/components/PagerControl.vue
src/styles/core/_helpers.scss
src/styles/core/_vars.scss
tests/unit/components/DocumentationTopic/TopicsLinkCardGrid.spec.js

Bug/issue #122817341, if applicable: 
Updates the UI in the medium viewport:
1. There should only be 2 rows max
2. The pagination dots should disappear in this viewport
3. Both of the chevrons should appear at the same time, and one of them should be disabled if there's no more cards in that "direction"
It also moves the `static-card-size` var into a global scope.

Pager UI updates

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue
src/components/NavBase.vue
src/styles/core/_nav.scss
tests/unit/components/DocumentationTopic/DocumentationNav/LanguageToggle.spec.js

Bug/issue #122676572, if applicable: 
Update styles for language toggle:
- Semibold font-weight and underline to links of the language list in small viewports if page has multiple languages to select from
- Semibold font-weight in links for the language dropdown in large viewports
- Light and dark mode for border colors
- Nav-menu-label-margin should be 5px
NA
Steps:
1. Go to a page with only one language available and assert that the summary specs are correct
2. Go to a page with multiple languages available and assert that the summary specs are correct

Update styles for language toggle

---

src/components/ContentNode.vue
src/components/ContentNode/ThematicBreak.vue
tests/unit/components/ContentNode.spec.js
tests/unit/components/ContentNode/ThematicBreak.spec.js

Bug/issue #, if applicable: 125507297
Adds support for rendering "thematic breaks" within content using the `<hr>` element.
With the corresponding Swift-DocC PR, the markdown syntax for horizontal rules can be used in content to indicate a thematic break within content, and this PR adds rendering support for this.
**Example Markdown:**
```diff
diff --git a/SwiftDocCRender.docc/contributing/Internals.md b/SwiftDocCRender.docc/contributing/Internals.md
index d3054747..2500a12d 100644
--- a/SwiftDocCRender.docc/contributing/Internals.md
+++ b/SwiftDocCRender.docc/contributing/Internals.md
@@ -6,6 +6,8 @@ Learn how DocC-Render is built internally, the principles behind its structure,
DocC-Render supports rendering reference pages, tutorials, and articles to document your project in a …
```

Support thematic breaks

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue

Bug/issue #, if applicable: 123086813
This refactors the way that the right-hand-side spacing is applied between the sidebar toggle and other content so that it only applies when the toggle is present and visible.
The previous implementation was done in the more generic nav component, which may not always include a sidebar toggle, so there could be unexpected spacing in those situations.
Steps:
1. Checkout this branch and use it to preview any documentation page.
2. Verify that there is still sufficient spacing between the sidebar navigator toggle button and the "Documentation" link/text in all viewport sizes.
3. Preview other kinds of pages and verify that this same spacing is not present if the sidebar navigator toggle is not present.
Make sure you check off the following items. If they …

Make sidebar toggle margin more explicit

---

src/components/DocumentationTopic/PrimaryContent.vue
src/components/DocumentationTopic/PrimaryContent/Attributes.vue
src/constants/ContentSectionAnchors.js
src/constants/PrimaryContentSection.js
src/lang/locales/en-US.json
tests/unit/components/DocumentationTopic/PrimaryContent.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/Attributes.spec.js

Bug/issue #, if applicable: 123114458
Add support for rendering a top-level "Attributes" section in the primary content area of documentation pages for any topic that has this kind of data (examples: default values, min/max values, etc).
This is the same kind of data that is already rendered within tables for individual REST parameters or object properties.
Steps:
1. Checkout this branch and use it to render example pages with attributes section data
2. Verify that a new top-level "Attributes" section is rendered for the page

Render top-level "Attributes" primary content section when relevant

---

src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue

- **Explanation:** Fixes an issue where excess spacing may occur when sidebar toggle is not displayed
- **Scope:** Impacts pages where the sidebar toggle is not displayed
- **Issue:** rdar://123086813
- **Risk:** Low, small CSS change to how spacing is applied for isolated button
- **Testing:** Manually tested that the spacing looks correct for variations of the sidebar with/without toggle in varying browser viewport sizes
- **Original PR:** #796

[6.0] Make sidebar toggle margin more explicit

---

src/components/DocumentationTopic/PrimaryContent.vue
src/components/DocumentationTopic/PrimaryContent/Attributes.vue
src/constants/ContentSectionAnchors.js
src/constants/PrimaryContentSection.js
src/lang/locales/en-US.json
tests/unit/components/DocumentationTopic/PrimaryContent.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/Attributes.spec.js

- **Explanation:** Adds support for rendering top-level "Attributes" section
- **Scope:** Impacts REST API object or plist key pages with top-level attributes data
- **Issue:** rdar://123114458
- **Risk:** Low, additive-only changes to render uncommonly used primary content section
- **Testing:** Added/updated unit tests, verified that the new section renders as expected with existing data
- **Original PR:** #797

[6.0] Render top-level "Attributes" primary content section when relevant

---

src/components/DocumentationTopic/PrimaryContent/RestResponses.vue
tests/unit/components/DocumentationTopic/PrimaryContent/RestResponses.spec.js

Bug/issue #, if applicable: 124300035
Adds a workaround to handle an issue where some REST content may sometimes be provided using the incorrect spelling of `mimetype` instead of `mimeType` in Render Node JSON.
Until the problematic provider can be updated, the renderer will now support both `mimetype` and `mimeType` spellings when dealing with data for REST responses content to maximize compatibility.
Steps:
1. Checkout this branch and use it to preview REST responses content with both spellings of mime-type data
2. Verify that the data is rendered in both scenarios

Handle multiple spellings of mime-type JSON data

---

src/components/DocumentationTopic/PrimaryContent/RestResponses.vue
tests/unit/components/DocumentationTopic/PrimaryContent/RestResponses.spec.js

- **Explanation:** Adds workaround for situation where data key may be spelled differently
- **Scope:** Impacts pages with HTTP response sections with content-type data
- **Issue:** rdar://124300035
- **Risk:** Low, minor isolated JS changes to handle data presented in any of 2 key names
- **Testing:** Added/updated unit tests, manually tested that the same data is rendered as expected, regardless of whether the JSON key is spelled `mimeType` or `mimetype`
- **Original PR:** #801

[6.0] Handle multiple spellings of mime-type JSON data

---

src/mixins/multipleSelection.js
tests/unit/components/Filter/FilterInput.spec.js

- **Explanation:** Don't emit selectedTags if there are no tags to paste
- **Scope:** Small
- **Issue:**  rdar://125844017
- **Risk:** Low, only affects pasting text in the navigator filter
- **Testing:** Added/updated unit tests
- **Reviewer:** @mportiz08  
- **Original PR:** #806

[6.0] Don't emit selectedTags if there are no tags to paste

---

src/mixins/multipleSelection.js
tests/unit/components/Filter/FilterInput.spec.js

Bug/issue #125844017, if applicable: 
Don't emit selectedTags if there are no tags to paste.
Emitting an empty selected tags array to the NavigatorCard was affecting the filter functionality.
NA
Steps:
1. Go to any documentation page with navigator
2. Copied a text
3. Paste it in the navigator's filter
4. Assert that filtering works well

Don't emit selectedTags if there are no tags to paste

---

src/components/DocumentationTopic.vue
src/constants/SymbolKind.js
tests/unit/components/DocumentationTopic.spec.js

rdar://125512559
Does not show a Mentioned In section on module pages, although it's possible in the future as the logic for collection mentions changes, along with its placement, so making this change in the renderer for now.
Testing: Manual testing with swift-markdown and unit test added.

Omit Mentioned In section on module pages

---

src/components/DocumentationTopic.vue
src/constants/SymbolKind.js
tests/unit/components/DocumentationTopic.spec.js

rdar://125512559
This is a cherry-pick of #811 to `release/6.0`.
- **Explanation**: Omits the Mentioned In section on module pages. This section might be included in the future as the mention logic changes, so this change is in the renderer for now.
- **Scope**: Impacts all module documentation pages when `--enable-experimental-mentioned-in` is used with DocC.
- **Issue**: rdar://125512559
- **Risk**: Low. This is a small scope change with specific options enabled.
- **Testing**: Added unit test; manual testing with Swift Markdown.
- **Reviewer**: @mportiz08 
- **Original PR**: https://github.com/apple/swift-docc-render/pull/811

[6.0] Omit Mentioned In section on module pages (#811)

---

src/components/DocumentationLayout.vue
tests/unit/components/DocumentationLayout.spec.js

- **Explanation:** Add prop to DocumentationLayout to be able to modify the Navigator's fixed width
- **Scope:** S, adding a prop to a component
- **Issue:** rdar://126869289
- **Testing:** Unit testing
- **Original PR:** https://github.com/apple/swift-docc-render/pull/822

[6.0] Add prop to DocumentationLayout to be able to modify the Navigator's fixed width

---

src/components/DocumentationLayout.vue
tests/unit/components/DocumentationLayout.spec.js

Bug/issue #, if applicable: 
Add navigatorFixedWidth prop to DocumentationLayout to be able to modify the Navigator's fixedWidth prop
NA
Steps:
1. Assert that everything works as expected

Add prop to DocumentationLayout to be able to modify the Navigator's fixed width

---

src/components/DocumentationTopic/Hero/Title.vue
src/views/DocumentationTopic.vue

- **Explanation:** Adds a configurable property to disable documentation hero background
- **Scope:** Impacts documentation pages
- **Issue:** rdar://127009817
- **Risk:** Low, minor JS property addition with sensible default
- **Testing:** Verified that existing hero background behavior persists and can be overwritten by changing default value.
- **Original PR:** #816

[6.0] Add `disableHeroBackground` property to `DocumentationTopic` view

---

src/App.vue
src/components/AdjustableSidebarWidth.vue
tests/unit/App.spec.js

Bug/issue #128197719, if applicable: 
Make sure the page is fully loaded before storing top offset in AdjustableSidebarWidth
NA
Steps:
1. Run a doccarchive with a navigator
2. Make sure that the navigator works as expected

Prevent issues when storing the top offset in AdjustableSidebarWidth

---

src/App.vue
tests/unit/App.spec.js

- **Explanation:** Fixes an issue where pixel offset value for navigator may be calculated incorrectly
- **Scope:** Impacts clicking links in navigator
- **Issue:** rdar://128197719
- **Risk:** Low, HTML element moved to different location in DOM
- **Testing:** Added unit test, verified that there are no regressions with loading pages or clicking items in navigator
- **Reviewer:** @mportiz08, @hqhhuang 
- **Original PR:** #826 

[6.0] Prevent issues when storing the top offset in AdjustableSidebarWidth

---

src/components/DocumentationTopic/DecoratedTopicTitle.vue

- **Explanation:** Revert underlined style for decorated topic titles
- **Scope:** decorated topic titles
- **Issue:** rdar://128096499
- **Risk:** Low, just affecting style for decorated topic titles
- **Testing:** Manually verify
- **Original PR:** https://github.com/apple/swift-docc-render/pull/833

[6.0] Revert underlined style for decorated topic titles

---

src/components/Navigator/NavigatorCard.vue
src/components/Navigator/NavigatorCardItem.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #122911237, if applicable: 
Transform item's path to lowercase in navigator, so if symbols have a path with capital letters, the highlighting of the active element in the navigator continues working
NA
Steps:
1. Run a doccarchive with a navigator
2. Make sure that everything works as expected

Transform item's path to lowercase in navigator

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

Bug/issue #128559835, if applicable: 
We have a function called `getChildPositionInScroller` that was meant to scroll items in the navigator into little by little, when focused, instead of jumping to the middle of the navigator scrollarea. More info: https://github.com/apple/swift-docc-render/pull/247
This function was being called in programmatic focus changes, instead of the initial keyboard navigation purpose, so I'm preventing it from happening.
NA
Steps:
1. Run a doccarchive with a navigator
2. Assert that you can open and close nested symbols using the arrow keys without the navigator changing your focus
3. Assert that you can scroll long lists of symbols using keyboard navigation (arrow keys)
Make sure you check off the following items. If they cannot be completed, provide a …

Prevent programmatic focus change from bubbling in handleFocusIn

---

src/components/Card.vue

Bug/issue #127050244, if applicable: 
Delete max-width in small viewports for Cards
NA
Steps:
1. Go to a technology with Cards
2. Assert that in small viewports they don't have a max-width on it

Delete max-width in small viewports for Cards

---

src/components/Navigator/NavigatorCard.vue
tests/unit/components/Navigator/NavigatorCard.spec.js

- **Explanation:** Fixes navigation issues related to focus events.
- **Scope:** Impacts clicking links in navigator
- **Issue:** rdar://128559835
- **Risk:** Low, single JS event handler change
- **Testing:** Updated unit tests, manually tested navigating across pages using sidebar
- **Reviewer:** @mportiz08, @eango 
- **Original PR:** #835 

[6.0] Prevent programmatic focus change from bubbling in handleFocusIn

---

src/components/Card.vue

- **Explanation:** Removes max-width for cards in small viewports
- **Scope:** Impacts pages with card content viewed in small viewport widths
- **Issue:** rdar://127050244
- **Risk:** Low, single CSS property removal
- **Testing:** Manually tested that pages with card content look good on varying viewport width sizes
- **Reviewer:** @mportiz08
- **Original PR:** #840

[6.0] Delete max-width in small viewports for Cards

---

src/components/Card.vue
src/styles/core/_helpers.scss

Bug/issue #128642639, if applicable: 
Make Card's link position to be relative instead of absolute. This is because when details in cards were long, the UI would get broken because the link was in a absolute position.
NA
Steps:
1. Run a doccarchive with normal and floating cards
2. Assert that cards look correct, regardless of how long the content is

Make Card's link position to be relative instead of absolute

---

src/components/Card.vue
src/styles/core/_helpers.scss

- **Explanation:** Updates card abstract/title/link positioning and layout
- **Scope:** Impacts pages using cards, especially in smaller viewport widths
- **Issue:** rdar://128642639
- **Risk:** Low, focused CSS-only changes to specific component
- **Testing:** Manually checked that smaller viewport positioning is improved and no regressions with styling of cards across varying viewport sizes
- **Reviewer:** @mportiz08
- **Original PR:** #837 

[6.0] Make Card's link position to be relative instead of absolute

---

src/components/DocumentationTopic/PrimaryContent/DeclarationList.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationToken.vue
src/components/DocumentationTopic/PrimaryContent/DeclarationToken/Highlighted.vue
src/styles/core/colors/_dark.scss
src/styles/core/colors/_light.scss
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationToken/Highlighted.spec.js

- **Explanation:** Updates UI to highlight differing parts of declarations
- **Scope:** Impacts pages for overloaded symbols built with the `--enable-experimental-overloaded-symbol-presentation` DocC compiler flag
- **Issue:** rdar://117503463
- **Risk:** Low, focused changes to render new declaration token
- **Testing:** Added/updated unit tests, manually verified that overloaded symbols render with expected declaration highlights
- **Original PR:** #841 
\cc @QuietMisdreavus

[6.0] Highlight unique components of overloaded declarations

---

src/components/DocumentationLayout.vue
src/components/DocumentationTopic/DocumentationNav.vue
src/components/NavBase.vue
src/components/Navigator.vue
src/components/Navigator/BaseNavigatorCard.vue
src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #128955252, if applicable: 
- Delete cursor default
- Change nav-title to be h2
NA
Steps:
1. Run a doccarchive
2. Go to any documentation page
3. Assert that Nav's title has a cursor when hovering
4. Assert that Nav's title is a h2

Fix Nav title's cursor and tag

---

src/components/TopicTypeIcon.vue

Bug/issue #127621275, if applicable: 
Prevent icons in Navigator from being smooshed
NA
Steps:
1. Run a doccarchive that has icons in the navigator
2. Assert that icons aren't being smooshed

Prevent icons in Navigator from being smooshed

---

src/components/TopicTypeIcon.vue

- **Explanation:** Prevent icons in Navigator from being smooshed
- **Scope:** only sidebar icons
- **Issue:** rdar://127621275
- **Risk:** Low, styles changes only in the sidebar icons
- **Testing:** Manually verified
- **Reviewer:** @mportiz08 @SamLanier 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/848

[6.0] Prevent icons in Navigator from being smooshed

---

src/components/Card.vue

- **Explanation:** Remove Card's shadow when hovering
- **Scope:** only card's shadow
- **Issue:** rdar://128943066
- **Risk:** Low, only card's shadow
- **Testing:** Manually verified
- **Reviewer:** @mportiz08 @SamLanier 
- **Original PR:** https://github.com/apple/swift-docc-render/pull/851

[6.0] Remove Card's shadow when hovering

---

src/utils/indentation.js
tests/unit/utils/indentation.spec.js

Bug/issue #, if applicable: 129590639
This prevents bugs where the indentation formatting code is mistakenly executed with declarations that are not Objective-C methods.
Since this formatting code was designed for only those kinds of method declarations, this added check will enforce this requirement more strictly, preventing bugs where this code may currently execute with other kinds of Objective-C (or other C family) symbols.
Steps:
1. Verify that there are no regressions with the way that Objective-C instance/class methods are formatted—the colon character is aligned across multiple lines when methods have multiple parameters.
2. Verify that there are no unexpected newlines introduced for other kinds of C-family declarations that may have parameters but aren't Objective-C …

Only indent Objective-C method declarations

---

src/utils/indentation.js
tests/unit/utils/indentation.spec.js

- **Explanation:** Fixes issue where some declarations render with unexpected newlines
- **Scope:** Impacts the declaration rendering for any C-family symbol
- **Issue:** rdar://129590639
- **Risk:** Low, single conditional added to make formatting logic more restrictive to ObjC methods
- **Testing:** Added unit test, manually tested that C++ symbol with unexpected formatting is resolved with this change, verified that there are no regressions with the formatting of Objective-C method declarations.
- **Original PR:** #860

[6.0] Only indent Objective-C method declarations

---

src/components/ContentNode.vue
src/mixins/metadata.js
tests/unit/components/ContentNode.spec.js
tests/unit/mixins/metadata.spec.js

Bug/issue #, if applicable: 129801569, #856
Fixes a bug where the logic that populates `<meta name="description">` content doesn't include the text for any referenced items.
Steps:
1. Use a link to a symbol in first paragraph abstract for a documentation page.
2. Verify that the text for the referenced symbol is now included in the `<meta name="description">` tag in the resulting HTML

Include code and referenced text in metadata description

---

src/components/ContentNode.vue
src/mixins/metadata.js
tests/unit/components/ContentNode.spec.js
tests/unit/mixins/metadata.spec.js

- **Explanation:** Fixes issue where inline references and code are not included in HTML metadata
- **Scope:** Impacts `<meta name="description">` tag for any pages with links/code in abstract paragraph
- **Issue:** rdar://129801569
- **Risk:** Low, small addition to focused logic for generating plaintext content
- **Testing:** Added unit tests, manually tested that expected inline text is now being included in metadata and there are no other regressions to metadata for other pages
- **Original PR:** #862

[6.0] Include code and referenced text in metadata description (#862)

---

src/components/Navigator.vue
tests/unit/components/Navigator.spec.js

- **Explanation:** Prevent NavigatorCard from re-render when fetching data
- **Scope:** Impacts Navigator
- **Issue:** rdar://130012107
- **Risk:** Medium, affects loading of Navigator
- **Testing:** Added unit tests, manually tested
- **Original PR:** https://github.com/apple/swift-docc-render/pull/865

[6.0] Prevent NavigatorCard from re-render when fetching data

---

src/components/Navigator.vue
tests/unit/components/Navigator.spec.js

Bug/issue #130012107, if applicable: 
Prevent NavigatorCard from re-render when fetching data
NA
Steps:
- Run any doccarchive
- Assert that there is no performance issues with the navigator when fetching data

Prevent NavigatorCard from re-render when fetching data

---

src/App.vue
src/components/Article.vue
src/components/DocumentationTopic.vue
src/components/Tutorial.vue
src/components/TutorialsOverview.vue
src/styles/_base.scss
src/styles/base/_reset.scss
tests/unit/App.spec.js
tests/unit/components/DocumentationTopic.spec.js

- **Explanation:** Fixes issue where link to subsection titled "main" doesn't work
- **Scope:** Impacts linking behavior and skip navigation functionality
- **Issue:** #788, rdar://110847532
- **Risk:** Low, small HTML attribute change
- **Testing:** Updated unit tests, manually verified that link works as expected now, no regressions with "skipnav" behavior tied to old ID value
- **Reviewer:** @hqhhuang  
- **Original PR:** #869

[6.0] Rename `#main` to `#app-main` for better compatibility with content

---

src/mixins/referencesProvider.js
tests/unit/mixins/referencesProvider.spec.js

Bug/issue #, if applicable: #885, 133444687
Fixes a [regression][885] introduced by #878 where external links are now rendering as plaintext strings instead of clickable links.
Resolves #885 
[885]: https://github.com/swiftlang/swift-docc-render/issues/885
Steps:
1. Checkout this branch and run the dev server with `VUE_APP_DEV_SERVER_PROXY=https://jverkoey.github.io/slipstream npm run serve`
2. Open http://localhost:8080/documentation/slipstream/slipstreamforswiftuidevelopers#Stacks and verify that the `HStack` and `VStack` strings are clickable links now (compare with main branch where they are plaintext)
3. Repeat testing instructions from #878 to ensure that functionality is not impacted by this change
Make sure you check off the following items. If they cannot be completed, provide a …

Fix regression where external links are rendering as plaintext

---

src/mixins/referencesProvider.js
tests/unit/mixins/referencesProvider.spec.js

- **Explanation:** Fixes regression where external links render as plaintext
- **Scope:** Impacts pages with links to external sources
- **Issue:** rdar://133444687
- **Risk:** Low, focused change to make JS logic more strict when stripping link data
- **Testing:** Updated unit tests, manually tested pages with internal and external link content, verified that known external links are still purposefully rendered as plaintext in the scenario from #878
- **Original PR:** #886

[6.0] Fix regression where external links are rendering as plaintext

---

bin/build-docs
bin/rundocc
bin/serve-docs

Bug/issue #, if applicable: 
This fixes a minor issue with some scripts in `bin/` that use the shebang line `#!/usr/bin/env sh`.
When running on a system with an actual `sh` implementation, these scripts fail due to a syntax issue with the `function` keyword (apparently a `bash` specific thing). This is easy to miss on platforms where `sh` is just a link to `bash`, so using `bash` will ensure that the scripts work without changes on all platforms.
Steps:
1. Run `npm run docs` to exercise all these scripts and ensure they are still functional.

Use bash for scripts instead of sh

---

src/components/DocumentationTopic/Summary/AvailabilityRange.vue
src/lang/locales/en-US.json
src/lang/locales/ja-JP.json
src/lang/locales/ko-KR.json
src/lang/locales/zh-CN.json
tests/unit/components/DocumentationTopic/Summary/AvailabilityRange.spec.js

Bug/issue #, if applicable: 135420580
This makes the `AvailabilityRange.introducedAt` prop optional instead of required.
This adds support for indicating that a symbol is available on a certain platform, even if there are no additional details on the specific version of that platform when it was first introduced.
For an example platform of _foo_, this is how it should now render:
**text**
_foo_ (instead of _foo 2.0+_)
**title** (hover text)
_Available on foo_ (instead of _Available on foo 2.0 and later_)
**aria-label**
_foo, Available on foo_ (same pattern of combining text/title)
Steps:
1. Test that the availability strings work the same as today without regressions with symbols that have version details
2. Test for the above string patterns after removing the `introducedAt` value from …

Render availability items without version range details

---

src/components/TutorialsOverview.vue
src/components/TutorialsOverview/Hero.vue

Bug/issue #, if applicable: 137430837
Fixes an issue where certain colors may look off when viewing a tutorials overview page with a light system/user appearance.
This problem/solution is very similar to #760, just in a different "always dark" component.
Steps:
1. Add some aside content to a tutorial overview page and view it in light mode

Ensure dark colors are always used in tutorials overview hero

---

src/components/DocumentationTopic/PrimaryContent/ParameterAttributes.vue
src/lang/locales/en-US.json
tests/unit/components/DocumentationTopic/PrimaryContent/ParameterAttributes.spec.js

Bug/issue #, if applicable: 131432834
This adds support for distinct `minimumLength` and `maximumLength` attributes within the top-level, primary "Attributes" section that may be rendered for REST documentation pages.
Steps:
1. Verify that the "Minimum Length" and "Maximum Length" fields show up in the "Attributes" section for a page with relevant data

Support min/max length data in "Attributes" section

---

src/components/DocumentationTopic/Summary/AvailabilityRange.vue
src/lang/locales/en-US.json
src/lang/locales/ja-JP.json
src/lang/locales/ko-KR.json
src/lang/locales/zh-CN.json
tests/unit/components/DocumentationTopic/Summary/AvailabilityRange.spec.js

- **Explanation:** Adds support for indicating that a symbol is available on a certain platform, even if there are no additional details on the specific version of that platform when it was first introduced.
- **Scope:** Impacts availability items with no version range information.
- **Issue:** rdar://139423135
- **Risk:** Small, makes the `AvailabilityRange.introducedAt` prop optional instead of required
- **Testing:** Detailed in original PR.
- **Reviewer:** @marinaaisa  
- **Original PR:** #891

[6.0] Render availability items without version range details

---

src/components/ContentNode/LinkableHeading.vue
tests/unit/components/ContentNode/LinkableHeading.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/PropertyTable.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestParameters.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestResponses.spec.js

Bug/issue #137046794, if applicable: 
Anchor links shouldn't overwrite query parameters. For the Routerlink component to preserve the query, we need to pass the
routers query as a query parameter to the "to" prop.
NA
Steps:
1. Run this project using any .doccarchive
2. Add any query in the URL, example: `?context=foo`
3. Click in a title anchor
4. Assert that the query in the URL doesn't get overwritten

Anchor links shouldn't overwrite query parameters

---

src/utils/navigatorData.js
tests/unit/utils/navigatorData.spec.js

Bug/issue #, if applicable: 140370212
This re-introduces logic removed by #904 that was needed to handle an edge case where the navigator needs to decide between data for 2 distinct navigation trees in the rare scenario where it is provided in the IndexJSON by DocC.
There will usually only be data for a single tree provided, but in the rare scenario where multiple are provided, we should prefer the tree with the `"module"` root.
Steps:
1. Verify that there are no regressions in behavior with loading/displaying data from Index JSON in the sidebar navigator.

Fix regression with edge case where navigator may display wrong data

---

src/stores/DocumentationTopicStore.js

Bug/issue #, if applicable: 141015022
The theme import variant allows this behavior to be adjusted if desired.
Steps:
1. Verify that there are no changes in behavior to the existing logic for filtering external references.

Use theme import for `filterInactiveReferences`

---

src/components/AdjustableSidebarWidth.vue
src/components/DocumentationLayout.vue

Bug/issue #141189589, if applicable: 
In 2022 we introduced a delay to hide the content of the navigator in [this commit](https://github.com/swiftlang/swift-docc-render/pull/296/commits/adce95906737362cfa16c2522bd0e6778bb2b0f2).
It was intended [to delay closing the navigator](https://github.com/swiftlang/swift-docc-render/pull/296#discussion_r871228205), so the horizontal transitions we have for the aside element would still work and we would also prevent keyboard navigation for AX reasons.
There are 2 transitions happening:
1) The `aside` element moves to the left
2) The navigator content gets hidden. We need this navigator content to hide for AX reasons explained [here](https://github.com/swiftlang/swift-docc-render/pull/296#discussion_r873715761).
Disclaimer: In the following videos I …

Unify time transitions across the Navigator

---

src/utils/navigatorData.js
tests/unit/utils/navigatorData.spec.js

Bug/issue #143323864, if applicable: 
If an interfaceLanguage is empty, the navigator will skip it.
NA
[index.json.zip](https://github.com/user-attachments/files/18540584/index.json.zip)
Steps:
1. Use the `index.json` file attached to this PR as the index for your navigator
2. Assert that you can visualize the navigator for the swift language 

Navigator skips empty languages

---

src/components/ContentNode/LinkableHeading.vue
tests/unit/components/ContentNode/LinkableHeading.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/PropertyTable.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestParameters.spec.js
tests/unit/components/DocumentationTopic/PrimaryContent/RestResponses.spec.js

- **Explanation:** Fixes issue where query params may unexpectedly go away when following hash links.
- **Scope:** Impacts all clickable section headings
- **Issue:** rdar://137046794
- **Risk:** Low, minor focused change to add additional context to link destinations
- **Testing:** Updated unit tests, manually tested problematic scenario
- **Original PR:** https://github.com/swiftlang/swift-docc-render/pull/914

[6.1] Anchor links shouldn't overwrite query parameters

---

src/utils/navigatorData.js
tests/unit/utils/navigatorData.spec.js

- **Explanation:** Fixes regression where navigator may display wrong tree when provided multiple options from Index JSON
- **Scope:** Impacts the sidebar navigator in rare cases
- **Issue:** rdar://140370212
- **Risk:** Low, small additional code change to make preferred choice when provided multiple trees of data
- **Testing:** Unit tests added, manually tested with problematic content and existing content without problematic content
- **Reviewer:** Hanqing Huang
- **Original PR:** https://github.com/swiftlang/swift-docc-render/pull/916

[6.1] Fix regression with edge case where navigator may display wrong data

---

src/stores/DocumentationTopicStore.js

- **Explanation:** Allows behavior of `filterInactiveReferences` function to be adjusted if configured
- **Scope:** Impacts app-wide logic that may result in links being disabled in certain contexts
- **Issue:** rdar://141015022
- **Risk:** Low, single import source change that has no direct impact on the existing codebase
- **Testing:** Existing unit tests continue to pass, no disruption to existing linking behavior
- **Reviewer:** @eango 
- **Original PR:** https://github.com/swiftlang/swift-docc-render/pull/917

[6.1] Use theme import for `filterInactiveReferences`

---

src/utils/navigatorData.js
tests/unit/utils/navigatorData.spec.js

- **Explanation:** Navigator skips empty interfaceLanguage
- **Scope:** Navigator
- **Issue:** rdar://143323864
- **Risk:** Low, focused change to the navigator when this one has multiple interface languages
- **Testing:** Unit tests added, manually tested too
- **Original PR:** https://github.com/swiftlang/swift-docc-render/pull/922

[6.1] Navigator skips empty languages

---

src/utils/navigatorData.js
tests/unit/utils/navigatorData.spec.js

Bug/issue #, if applicable: 142337934
This updates the logic used to choose between multiple top-level trees of data for the sidebar navigator:
Before, it would pick the first `module` in the list. (see #916)
Now, it will pick the first node with a path prefix matches the path prefix of the current URL.
This logic should only apply to rare scenarios where multiple trees of index data are included in a single Index JSON file.
Steps:
1. Verify that there are no regressions with loading sidebar data in common, single-root scenarios.
2. Verify that the data loaded for the index generally matches what would be expected given the current URL in scenarios where there are multiple roots of index data.

Rely on URL paths when choosing among multiple indices

---

src/components/SVGIcon.vue
tests/unit/components/SVGIcon.spec.js

Bug/issue #146669359, if applicable: 
In case we render a SVG passing a iconURL or by the theme-settings json file, we need to normalize the path to add any possible baseUrl to it.
NA
Steps:
1. Use a doccarchive that contains SVG icons paths to render
2. Run the server passing a baseUrl to it `BASE_URL='/foo/' npm run serve`
3. Assert that the icons paths are being prefixed, along with the rest of the app

Normalize path of icon URL

---

src/components/DocumentationTopic/PrimaryContent/PropertyListKeyType.vue
tests/unit/components/DocumentationTopic/PrimaryContent/PropertyListKeyType.spec.js

Bug/issue #, if applicable: 139449414
This adds some small sanitization logic to the `PropertyListKeyType` component to better handle situations where it may get `baseType` data that has extraneous leading/trailing whitespace. See the added unit test for an example—in that example, the UI should render "array of dictionaries" instead of "array of dictionary".
Steps:
1. See unit test for example.

Handle malformed baseType data with extraneous whitespace

---

src/components/NavBase.vue
src/components/Tutorial/NavigationBar.vue

Bug/issue #137436968, if applicable: 
This is a small change to make the nav-title to be 100% width in mobile viewport instead of 90%.
There was no reason for it to be 90% instead.
NA
Steps:
1. Go to any documentation or tutorial page
2. Assert that the nav title looks correct in mobile viewport

Make nav-title 100% width in mobile viewport

---

src/mixins/indexDataFetcher.js

Bug/issue #, if applicable: #919 (rdar://147239963)
Fixes a regression with the performance of the sidebar hover animation that can be very slow for large projects with many sidebar items.
This regression was introduced with #904.
The cause of the poor performance turned out to be a big jump in memory usage, which noticeably impacted the performance of hovering over sidebar items. By utilizing `Object.freeze` again, we prevent Vue from creating a large number of proxy items that it would normally use to track changes to state data and thereby keep the memory usage down for projects with many index nodes. Since we don't modify this data after fetching/deserializing it, this should be an acceptable tradeoff.
In the future if we need to handle even larger amounts of data or need to track …

[Regression] [Performance] Fix delayed sidebar hover animation for large projects

---

CONTRIBUTING.md
bin/check-source

A small change to tweak the CONTRIBUTING.md guide to reference looking for issues tagged "good first issue" instead of "StarterBug" to be consistent with the rest of the swiftlang organization repositories.

updates contributing guide to use 'good first issue' instead of StarterBug to be consistent with the rest of swiftlang repositories

---

src/utils/navigatorData.js
tests/unit/utils/navigatorData.spec.js

Bug/issue #, if applicable: 147829785
Fixes an edge case for #929 where the added logic doesn't apply cleanly when the node path in some Index JSON data includes some prefix before the `/documentation` segment.
By using the `endsWith` comparison instead of `===`, this logic can properly apply to that edge case without impacting the normal scenario with no base URLs.
Steps:
1. Ensure #929 testing steps still work as expected
2. Test some content where the Index JSON has multiple top-level trees of data and the node paths include a path prefix before /documentation

Compare page and node URLs less strictly when choosing between multiple indices

---

src/components/DocumentationTopic/Hero/DocumentationHero.vue
src/components/Tutorial.vue
src/components/Tutorial/Hero.vue
src/components/TutorialsOverview.vue
src/components/TutorialsOverview/LearningPath.vue
src/styles/core/colors/_light.scss
tests/unit/components/DocumentationTopic/Hero/DocumentationHero.spec.js
tests/unit/components/Tutorial.spec.js
tests/unit/components/TutorialsOverview.spec.js
tests/unit/components/TutorialsOverview/LearningPath.spec.js

CCC:
- Explanation: Add HTML data attributes to background and hero elements
- Scope: HMTL markup
- Issue: rdar://149293880
- Risk: Low, focused changes in the HMTL markup
- Testing: Added unit tests and manually tested

[6.2-20250502] Add HTML data attributes to background and hero elements

---

src/components/DocumentationTopic/Hero/DocumentationHero.vue
src/components/Tutorial.vue
src/components/Tutorial/Hero.vue
src/components/TutorialsOverview.vue
src/components/TutorialsOverview/LearningPath.vue
src/styles/core/colors/_light.scss
tests/unit/components/DocumentationTopic/Hero/DocumentationHero.spec.js
tests/unit/components/Tutorial.spec.js
tests/unit/components/TutorialsOverview.spec.js
tests/unit/components/TutorialsOverview/LearningPath.spec.js

CCC:
- Explanation: Add HTML data attributes to background and hero elements
- Scope: HMTL markup
- Issue: rdar://149293880
- Risk: Low, focused changes in the HMTL markup
- Testing: Added unit tests and manually tested

[6.2] Add HTML data attributes to background and hero elements

---

src/components/DocumentationTopic/Hero/DocumentationHero.vue
src/components/Tutorial.vue
src/components/Tutorial/Hero.vue
src/components/TutorialsOverview.vue
src/components/TutorialsOverview/LearningPath.vue
src/styles/core/colors/_light.scss
tests/unit/components/DocumentationTopic/Hero/DocumentationHero.spec.js
tests/unit/components/Tutorial.spec.js
tests/unit/components/TutorialsOverview.spec.js
tests/unit/components/TutorialsOverview/LearningPath.spec.js

Bug/issue #149293880, if applicable: 
We want to add HTML data attributes https://developer.mozilla.org/en-US/docs/Web/HTML/How_to/Use_data_attributes to background and hero elements across all the pages to be able to recognise them. We are only interested in the heroes that have an enhance background, so in the case that it doesn't have it, the data attribute won't be rendered.
NA
Steps:
1. Run this project with any doccarchive
2. Assert that everything works as normal and expected

Add HTML data attributes to background and hero elements

---

src/components/TutorialsOverview.vue

- **Explanation:** Fixes issue where body bg color may be light in certain situations
- **Scope:** Only impacts tutorial-overview pages, small CSS addition
- **Issue:** rdar://151701111
- **Risk:** Low, minor CSS addition to specific page type
- **Testing:** Manually tested that body bg is always dark, regardless of system/user appearance settings
- **Original PR:** #943

[6.2-20250502] Ensure body bg is always dark for tutorials-overview page

---

src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

Bug/issue #, if applicable: 154225522
When viewing the Objective-C variant of a documentation page, the renderer may crash when navigating to a different part of the page using a hash fragment, like when clicking a subheading for example.
This happens because there is a patch of data used to transform the original Swift Render JSON into the Objective-C variant—this patch is mistakenly getting applied twice when navigating from the Objective-C version to a different location on the same page using on-page links.
Steps:
1. Find an example symbol documentation page which has both Swift and Objective-C variants and switch to the Objective-C variant.
2. Find a link to something on the same page like a subheading and click it.
3. Verify that the renderer no longer crashes.
4. Verify that there …

Fix crash when subheading is clicked on ObjC page

---

src/views/DocumentationTopic.vue
tests/unit/views/DocumentationTopic.spec.js

- **Explanation:** Fixes issue where clicking a link to a target on the same page of an Objective-C API may crash the renderer.
- **Scope:** Impacts DocC generated API symbol pages with ObjC variants that have links to fragment identifiers.
- **Issue:** rdar://154225522
- **Risk:** Low, single addition to conditional for specific kinds of pages
- **Testing:** Added unit tests, manually tested that jumping between sections of an ObjC symbol page doesn't crash anymore and there are no regressions switching between Swift/ObjC pages.
- **Original PR:** #951

[6.2] Fix crash when subheading is clicked on ObjC page

---

src/setup-utils/vue-config-utils.js
src/utils/syntax-highlight.js

extends the list of highlighted languages to include YAML by default
resolves #959

adds YAML to list of automatically highlighted languages for code blocks
