swiftlang/swift-docc-render

src/styles/core/_helpers.scss
Bug/issue #, if applicable: 78324484
This is just cleaning up unused code.
NA
NA
=> Cleanup unused code

src/components/Navigator.vue, src/components/Navigator/NavigatorCard.vue, src/components/Navigator/NavigatorCardItem.vue, tests/unit/components/Navigator.spec.js, tests/unit/components/Navigator/NavigatorCard.spec.js, tests/unit/components/Navigator/NavigatorCardItem.spec.js
Bug/issue #, if applicable: 88194935
This PR improves the AX on the sidebar
NA
Make sure you download and unzip the .doccarchive - [SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8082216/SlothCreator.doccarchive.1.zip)
Steps:
1. run VUE_APP_DEV_SERVER_PROXY=/path/to/SlothCreator.doccarchive npm run serve
2. Visit http://localhost:8080/documentation/slothcreator
3. Try using Tabbing or VO
=> Add sidenav AX improvements

src/components/Navigator.vue, src/components/Navigator/NavigatorCard.vue, src/components/Navigator/NavigatorCardItem.vue, src/components/Navigator/NavigatorDataProvider.vue, src/mixins/apiChangesObserving.js, src/stores/ApiChangesStoreBase.js, src/styles/core/_changes.scss, src/views/DocumentationTopic.vue, tests/unit/components/Navigator.spec.js, tests/unit/components/Navigator/NavigatorCard.spec.js, tests/unit/components/Navigator/NavigatorCardItem.spec.js, tests/unit/components/Navigator/NavigatorDataProvider.spec.js, tests/unit/mixins/apiChangesObserving.spec.js, tests/unit/stores/ApiChangesStoreBase.spec.js, tests/unit/views/DocumentationTopic.spec.js
Bug/issue #, if applicable: 83858869
Adds basic diffing support to the sidebar
NA
NA
=> Adds diff support to the sidebar

src/styles/core/_breakpoints.scss, src/styles/core/_vars.scss
Bug/issue #, if applicable: rdar://90844182
Update padding in S viewport to use variable
=> Update padding in S viewport

src/components/Navigator/NavigatorCardItem.vue
Bug/issue #, if applicable: 91775087
This PR cleans up the changes related styling in the navigator, to align with latest design specs.
This PR further continues fixes like #173 
NA
=> Adjust the styling for API diffs in the navigator

src/components/Navigator/NavigatorCardItem.vue
- **Rationale:** Cleans up the changes related styling in the navigator, updates the icons and size of icons, to align with latest design specs.
- **Risk Detail:** Isolated CSS changes in the navigator.
- **Reward Details:** UI is closer to the design specs
- **Original PR:** https://github.com/apple/swift-docc-render/pull/189
- **Issue:** rdar://91775087
- **Code Reviewed By:** @hqhhuang @SamLanier 
- **Testing Details:** Updated the styling and visually tested
=> [5.7] Adjust the icons for API diffs in the navigator (#189)

src/components/ContentNode/CodeListing.vue, src/components/ContentNode/CollapsibleCodeListing.vue, src/components/DocumentationTopic/PrimaryContent/DeclarationDiff.vue, src/components/DocumentationTopic/PrimaryContent/DeclarationGroup.vue, src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue, src/components/DocumentationTopic/TopicsLinkBlock.vue, src/styles/base/_changes.scss, src/styles/core/_changes.scss, src/styles/core/_vars.scss, src/styles/core/colors/_light.scss
- **Rationale:** The styling for API changes has been cleaned up and these updates implement those changes.
- **Risk:** Mid
- **Risk Detail:** Mostly CSS changes related to border-radius or minor background changes, which although small, touch allot of places.
- **Reward Details:** UI is closer to the design specs
- **Original PR:** https://github.com/apple/swift-docc-render/pull/173
- **Issue:** rdar://91417770
- **Code Reviewed By:** @hqhhuang @SamLanier 
- **Testing Details:** Updated the styling and visually tested
=> [5.7] Update the styling related to API changes

src/components/DocumentationTopic/PrimaryContent.vue, src/constants/ContentSectionAnchors.js, src/views/DocumentationTopic.vue
Fixes a few forgotten import paths
NA
Assert it builds correct.
=> Fix bad import paths

src/App.vue
Bug/issue #, if applicable: 103147259
Fixes potential issues with the layout, when the page content is too short, especially when the navigator is completely disabled.
NA
Steps:
1. Make sure no regressions are visible. 
2. Try with an old doccarchive, that has no Navigator data at all.
3. Try with and without a custom header
=> Fix potential app css layout issues

src/components/DocumentationTopic.vue, src/components/DocumentationTopic/DocumentationHero.vue, src/styles/base/_reset.scss, src/styles/core/_breakpoints.scss
Bug/issue #, if applicable: 106876743
Adds an extra small breakpoint for IDE mode, update padding for minimized in IDE mode.
Manually test; Padding should be 15px in Minimized view in IDE mode.
=> Update padding & add breakpoint for Minimized in IDE mode

src/components/Navigator/NavigatorCard.vue
- Explanation: Perf improvements to the Navigator when navigating links
- Scope: Doc pages
- Issue: rdar://105184773
- Risk: Small
- Testing: Manual testing on Doc pages
- Reviewer: @marinaaisa 
- Original PR: #541
=> [5.9] Navigator performance improvements

src/components/Filter/FilterInput.vue, src/components/GenericModal.vue, src/components/Navigator.vue, src/components/Navigator/BaseNavigatorCard.vue, src/components/Navigator/NavigatorCard.vue, src/components/Navigator/QuickNavigationButton.vue, src/components/Navigator/QuickNavigationModal.vue, src/lang/locales/en-US.json, src/views/DocumentationTopic.vue, tests/unit/components/Filter/FilterInput.spec.js, tests/unit/components/GenericModal.spec.js, tests/unit/components/Navigator/NavigatorCard.spec.js, tests/unit/components/Navigator/QuickNavigationButton.spec.js, tests/unit/components/Navigator/QuickNavigationModal.spec.js, tests/unit/views/DocumentationTopic.spec.js
- **Explanation:** Updates the UI for accessing the "Quick Navigation" feature
- **Scope:** HTML/JS/CSS changes that impacts all /documentation pages
- **Issue:** rdar://101336103
- **Risk:** Medium, removes the existing navbar toggle and adds a new button to the sidebar, small potential for regressions in the existing "Quick Navigation" experience or other modal functionality
- **Testing:** Updated/added unit tests. Manually tested that the new affordance works as expected with example content, both with/without the additional preview experience enabled with a feature flag.
- **Reviewer:** @dobromir-hristov, @biamx3
- **Original PR:** #487
=> [5.9] UI Updates to Quick Navigation

src/components/DocumentationTopic.vue, src/components/DocumentationTopic/DocumentationHero.vue, src/styles/base/_reset.scss, src/styles/core/_breakpoints.scss
Bug/issue #, if applicable: 108391432
Remove breakpoint in Minimized mode & update padding
Steps:
1.  Manual testing
=> Remove breakpoint in Minimized mode & update padding

src/components/DocumentationTopic/TopicsLinkCardGridItem.vue, src/lang/locales/en-US.json, tests/unit/components/DocumentationTopic/TopicsLinkCardGridItem.spec.js
Bug/issue #108050564, if applicable: 
Add i18n string from TopicsLinkCardGridItem
NA
Steps:
1. Assert everything looks correct
=> Add i18n string from TopicsLinkCardGridItem

src/components/DocumentationTopic/TopicsLinkCardGridItem.vue, src/lang/locales/en-US.json, tests/unit/components/DocumentationTopic/TopicsLinkCardGridItem.spec.js
- **Explanation:** It adds i18n string from TopicsLinkCardGridItem
- **Scope:** TopicsLinkCardGridItem component
- **Issue:** rdar://108050564
- **Original PR:** https://github.com/apple/swift-docc-render/pull/621
=> [5.9] Add i18n string from TopicsLinkCardGridItem

src/App.vue
Bug/issue #, if applicable: rdar://108634054
Disable `skip-nav` VO link in IDE
=> Disable `skip-nav` VO link in IDE

src/components/Navigator/QuickNavigationModal.vue
Bug/issue #108019962, if applicable: 
Move scrollbar to list view in Quick Navigation
NA
Steps:
1. Open Quick Navigation
2. Turn scrollbars to "Always" inside System Preferences -> General -> Show scroll bars
=> Move scrollbar to list view in Quick Navigation

src/components/DocumentationTopic/PrimaryContent/Declaration.vue
- **Explanation:** Reduces the space of the conditional constraint under the Declaration by 10px
- **Scope:** Declarations
- **Issue:** rdar://105460303
- **Reviewer:** @hqhhuang
- **Original PR:** #631
=> [5.9] reduce the Declaration conditional constraint spacing to 20px

src/components/Navigator/QuickNavigationModal.vue
- **Explanation:** Move scrollbar to list view in Quick Navigation
- **Scope:** Quick Navigation
- **Issue:** rdar://108019962
- **Original PR:** [#631  ](https://github.com/apple/swift-docc-render/pull/634)
=> [5.9] Move scrollbar to list view in Quick Navigation

src/components/Navigator/QuickNavigationModal.vue
=> fix: import path

src/components/Navigator/QuickNavigationModal.vue
- **Explanation:** Fixes location of a scrollbar in Quick Navigation modal
- **Scope:** Impacts Quick Nav when content scrolls
- **Issue:** rdar://108019962
- **Risk:** Small, minor CSS change
- **Testing:** Manually tested scrolling quicknav to verify that scrollbars are in the right location.
- **Reviewer:** @mportiz08 and @dobromir-hristov 
- **Original PR:** #634
=> [5.9-05012023] Move scrollbar to list view in Quick Navigation

src/lang/locales/ja-JP.json, src/lang/locales/zh-CN.json
- **Explanation:** Adds translated strings for Chinese and Japanese
- **Scope:** Config-only change for localization purposes
- **Issue:** rdar://108904481
- **Risk:** Low, only config change
- **Testing:** Verified that new strings render in place of English equivalents
- **Reviewer:** @mportiz08  
- **Original PR:** #653
=> [5.9] Add translated strings

src/components/DocumentationTopic.vue, src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue, src/components/DocumentationTopic/Summary/LanguageSwitcher.vue, src/components/ImageAsset.vue, src/components/Tutorial/Hero.vue, src/components/VideoAsset.vue, src/utils/assets.js, src/utils/data.js, src/utils/theme-settings.js, src/utils/url-helper.js, tests/unit/components/DocumentationTopic/Summary/LanguageSwitcher.spec.js, tests/unit/utils/assets.spec.js, tests/unit/utils/data.spec.js, tests/unit/utils/metadata.spec.js, tests/unit/utils/theme-settings.spec.js, tests/unit/utils/url-helper.spec.js
- **Explanation:** Refactor normalize URLs
- **Scope:** data fetching features
- **Issue:** rdar://96841531
- **Testing:** Unit testing
- **Original PR:** https://github.com/apple/swift-docc-render/pull/596
=> [5.9] Refactor: URL utils

src/setup-utils/SwiftDocCRenderi18n.js
Bug/issue #109731672, if applicable: 
Add support for dateTimeFormats in VueI18n
NA
Steps:
1. Assert that everything works as expected
=> Add support for dateTimeFormats in VueI18n

vue.config.js
Bug/issue #, if applicable: 
N/A
Make variable of statement
N/A
_Describe any dependencies this PR might have, such as an associated branch in another repository._
Look at source (?)
=> chore: extract env to var

src/components/DocumentationTopic.vue, src/components/DocumentationTopic/PrimaryContent/DeclarationGroup.vue, src/components/DocumentationTopic/PrimaryContent/DeclarationSource.vue, src/components/DocumentationTopic/RelationshipsList.vue, src/components/DocumentationTopic/TopicsLinkBlock.vue, src/constants/multipleLines.js, src/mixins/apiChangesHelpers.js, src/styles/base/_changes.scss, src/utils/multipleLines.js, tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationGroup.spec.js, tests/unit/components/DocumentationTopic/PrimaryContent/DeclarationSource.spec.js, tests/unit/components/DocumentationTopic/RelationshipsList.spec.js, tests/unit/components/DocumentationTopic/TopicsLinkBlock.spec.js, tests/unit/mixins/apiChangesHelpers.spec.js, tests/unit/utils/multipleLines.spec.js
- **Explanation:** Wraps declaration when there's no "smart wrapping" when in both minimized and IDE mode
- **Scope:** Declaration section in minimized & IDE mode
- **Issue:** rdar://106567892
- **Testing:** Manual testing in minimized & IDE mode
- **Original PR:** #646
=> [5.9] Wrap Declarations in Minimized and IDE mode

src/components/ContentNode/LinkableHeading.vue, tests/unit/components/ContentNode/LinkableHeading.spec.js
=> [5.10] Disallow selection of invisible text for linkable headings

src/constants/router.js, src/routes.js, src/setup-utils/SwiftDocCRenderRouter.js, tests/unit/components/ContentNode/Reference.spec.js
=> [5.10] Remove localized "server-error" route

src/components/ContentNode/Reference.vue, src/components/ContentNode/ReferenceExternalSymbol.vue, src/components/DocumentationTopic/RelationshipsList.vue, tests/unit/components/ContentNode/Reference.spec.js, tests/unit/components/ContentNode/ReferenceExternalSymbol.spec.js, tests/unit/components/DocumentationTopic/RelationshipsList.spec.js
- **Explanation:** Adds support for rendering links to external locations in the "Relationships" section
- **Scope:** Impacts link component used across the app
- **Issue:** rdar://112048068
- **Risk:** Low, minor change to reference component, small change to Relationships component
- **Testing:** Added/updated unit tests, tested Relationships section in scenarios with/without external links, checked for general regressions with links
- **Original PR:** #737
=> [5.10] Allow external links in "Relationships" section

src/components/Tutorial/Assessments/Quiz.vue, src/lang/locales/en-US.json, tests/unit/components/Tutorial/Assessments/Quiz.spec.js
Explanation: Expose answer content to VoiceOver in Tutorials' Quiz
Scope: Tutorials' Quiz
Issue: rdar://115116964
Risk: Low, minor change for AX
Testing: Added/updated unit tests and manual testing
Reviewer: @dobromir-hristov
Original PR: https://github.com/apple/swift-docc-render/pull/731
=> [5.10] Expose answer content to VoiceOver in Tutorials' Quiz

src/components/Navigator/QuickNavigationModal.vue, tests/unit/components/Navigator/QuickNavigationModal.spec.js
- Explanation: Improves keyboard navigation (AX) features in Quick Navigation
- Scope: Quick Navigation
- Issue: rdar://111742596
- Risk: Low
- Testing: Added/updated unit tests, tested manually with keyboard
- Reviewer: @mportiz08 
- Original PR: https://github.com/apple/swift-docc-render/pull/736
=> [5.10] Quick Navigation user should be able to tab from list of results to preview and use arrow keys within the list

src/components/Badge.vue, src/components/DocumentationTopic.vue, src/components/DocumentationTopic/Hero/Title.vue, src/components/DocumentationTopic/Summary/Availability.vue, src/components/DocumentationTopic/Summary/AvailabilityRange.vue, src/components/Navigator/NavigatorCard.vue, src/styles/core/colors/_dark.scss, src/styles/core/colors/_light.scss, tests/unit/components/DocumentationTopic/Summary/Availability.spec.js
Bug/issue #, if applicable: 122130081
Update style of Availability in the Hero and Badges.
NA
Manual testing, check:
1. badges in the navigator, nav bar, and the availability pill
2. availability pills in the hero section
=> Update Hero Availability & Badge style

src/components/VideoAsset.vue
Bug/issue #, if applicable: 124102221
This fixes an issue where a video does not automatically switch to the expected variant (if multiple are available) when a user toggles from "Light" to "Dark" mode or vice-versa. After refreshing the page, the initial variant is always the correct one, but it does not dynamically switch as expected when using the color scheme toggle.
I'd love to hear if there is a better way to fix this or if I'm missing something obvious, because I don't think a `key` _should_ strictly be needed in this situation, but I may be overlooking something. I tried a couple of other things that seemed like more appropriate fixes, but neither worked:
* add a new `normalizedPath` variable to `data` and update it using a watcher on the `videoAttributes` computed property—it …
=> Ensure video variants update in sync with a color scheme change

src/components/DocumentationTopic/Description/Abstract.vue, src/components/DocumentationTopic/Hero/Hierarchy.vue, src/styles/core/typography/_font-styles.scss
Bug/issue #, if applicable: rdar://123779770
Change eyebrow font to `body-reduced` and add a new font `intro` for availability info.
Test Manually
=> Update font size for hero

src/components/DocumentationTopic/PrimaryContent/Attributes.vue
=> Fix import syntax

src/components/DocumentationTopic/DocumentationNav/LanguageToggle.vue, src/components/Footer.vue, src/components/Navigator/NavigatorCard.vue, src/components/Navigator/QuickNavigationButton.vue, src/components/SuggestLang.vue, src/styles/core/_vars.scss, src/views/DocumentationTopic.vue
- **Explanation:** Add padding to top of filter bar in S/M viewport in the navigator
- **Scope:** Small
- **Issue:** rdar://124561315
- **Risk:** Low, only affects navigator filter in S/M vp
- **Reviewer:** @marinaaisa   
- **Original PR:** #808
=> [6.0] Add padding between nav and filter in S/M Viewport

src/lang/locales/ja-JP.json, src/lang/locales/ko-KR.json, src/lang/locales/zh-CN.json
- **Explanation:** Update new i18n strings
- **Scope:** i18n strings across the app
- **Issue:** rdar://125252837
- **Risk:** Low, just new strings
- **Testing:** Manually verify
- **Original PR:** https://github.com/apple/swift-docc-render/pull/828
=> [6.0] Update new i18n strings

src/components/AdjustableSidebarWidth.vue, tests/unit/components/AdjustableSidebarWidth.spec.js
- **Explanation:** Update navigator max/min width
- **Scope:** only navigator
- **Issue:** rdar://127753154
- **Risk:** Low, just affecting the navigator
- **Testing:** Manually verify, updated tests
- **Reviewer:** @mportiz08
- **Original PR:** https://github.com/apple/swift-docc-render/pull/831
=> [6.0] Update navigator max/min width

src/components/Navigator/NavigatorCard.vue, tests/unit/components/Navigator/NavigatorCard.spec.js
Explanation: Transform item's path to lowercase in navigator
Scope: only affects the Technology title
Issue: rdar://122911237
Risk: Low, it only affects the Technology title
Testing: Manually verify, updated tests
Reviewer: @mportiz08
Original PR: https://github.com/apple/swift-docc-render/pull/836
=> [6.0] Transform item's path to lowercase in navigator

tests/unit/components/ContentNode.spec.js
Fix test warning introduced by #862
=> Fix test warning from prop validation.

package-lock.json, package.json
Fixes Bug #930
Updating tree-sitter dependencies.
This fix is the blocker to https://github.com/swiftlang/vscode-swift/issues/1173
Existing test cases should pass, as the PR contains no code changes
Steps:
1. Run `npm install`
=> Update tree-sitter dependencies

src/components/DocumentationLayout.vue, src/components/Navigator/QuickNavigationModal.vue, src/lang/locales/en-US.json
Bug/issue #, if applicable: rdar://139682470 
Create 2 more props to allow customizing of Quick Navigation:
1. What we search on
2. Placeholder text
Also fixes grammar for the placeholder text.
NA
Steps:
1. Ensure no regressions
=> Allow customization for QuickNavigation
